In [1]:
# DMG Formula
dmg = attack*(100/(100+defense))

NameError: name 'attack' is not defined

In [2]:
# Kalender
# tanggal = 1 - 30
# bulan = 1 - 12

# Umur Stabil 10 sampai 40
# Umur 10 Penentuan Fighter atau bukan
# anak-anak (1-7), Remaja (8-16), dewasa Muda(17-25), Dewasa Tua(26-40), Lansia(41-100)

In [ ]:
# Sistem Damage
# Sistem Duel
# Sistem Level
# Sistem Umur
# Sistem Stamina
# Sistem Makan
# Sistem Keuangan
# Sistem Daily
# Sistem Kelas Otomatis (Awal di buat)
# Sistem Kelas Otomatis (Setelah 10 Tahun)
# Sistem Pemberian Roles (King/Queen, Panglima, Prajurit, Fighter, Penduduk)

In [66]:
karakter_list =[karakter("gerald", 20), karakter("plakasa", 19)]
for i in range(360):
    karakter_list = daily(karakter_list)
    karakter_list[0].info()
    print(" ")
  
  # karakter_list[1].info()

Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 0
Coin : 750
ATK : 16
DEF : 3
SPD : 10
Health : 960
Stamina : 107
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 0
Coin : 254
ATK : 16
DEF : 3
SPD : 10
Health : 960
Stamina : 107
EXP : 28


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 0
Coin : 187
ATK : 16
DEF : 3
SPD : 10
Health : 960
Stamina : 107
EXP : 68


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 0
Coin : 130
ATK : 16
DEF : 3
SPD : 10
Health : 960
Stamina : 107
EXP : 84


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 149
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 188
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 19


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 91
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 31


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 84
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 45


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 52
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 84


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 110
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 108


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 68
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 118


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 1
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 160


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 1
Coin : 64
ATK : 26
DEF : 23
SPD : 12
Health : 1023
Stamina : 111
EXP : 174


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : 22
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -50
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 31


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -117
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 80


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -117
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 80


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -169
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 121


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -68
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 156


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -957
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 175


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -1009
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 175


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -1061
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 194


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -437
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 248


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 2
Coin : -372
ATK : 34
DEF : 34
SPD : 15
Health : 1063
Stamina : 113
EXP : 296


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : -360
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : -333
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 39


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 184
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 119


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 102
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 159


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 119
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 217


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 163
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 238


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 123
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 238


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 18
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 288


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 42
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 320


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : 49
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 380


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 3
Coin : -21
ATK : 49
DEF : 45
SPD : 18
Health : 1123
Stamina : 117
EXP : 390


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1073
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 19


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1140
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 29


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1125
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 64


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1185
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 64


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1270
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 87


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1259
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 138


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1193
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 196


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1122
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 252


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -951
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 314


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -931
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 344


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -971
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 344


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -974
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 371


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -999
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 415


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1963
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 415


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1948
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 449


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1919
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 478


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 4
Coin : -1981
ATK : 61
DEF : 54
SPD : 25
Health : 1201
Stamina : 119
EXP : 498


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2063
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 29


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2105
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 57


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2180
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 82


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2160
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 103


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2054
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 146


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2046
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 200


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1534
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 313


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1506
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 338


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1530
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 383


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1605
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 432


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1694
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 455


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -1577
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 477


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2516
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 502


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2521
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 523


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2524
ATK : 81
DEF : 66
SPD : 30
Health : 1254
Stamina : 129
EXP : 577


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 5
Coin : -2500
ATK : 81
DEF : 66

SPD : 30
Health : 1254
Stamina : 129
EXP : 593


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2738
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2818
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2868
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 47


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2958
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 102


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2960
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 146


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -3000
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 193


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2995
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 238


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2230
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 328


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2265
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 358


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2254
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 364


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -2251
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 387


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1678
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 465


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1718
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 489


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1704
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 496


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1640
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 526


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1675
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 541


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1757
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 563


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1874
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 606


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1909
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 669


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 6
Coin : -1986
ATK : 95
DEF : 85
SPD : 32
Health : 1341
Stamina : 134
EXP : 669


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -2923
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 30


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -2894
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 46


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -2247
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 123


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -2324
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 123


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -2315
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 166


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1761
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 250


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1826
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 273


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1254
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 347


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1229
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 390


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1151
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 458


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -1181
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 469


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -457
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 568


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : -512
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 603


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : 41
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 662


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : 166
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 762


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 7
Coin : 160
ATK : 110
DEF : 98
SPD : 36
Health : 1403
Stamina : 136
EXP : 791


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 154
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 34
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 24


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1124
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 192


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1127
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 214


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1242
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 273


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1202
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 273


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1125
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 326


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1107
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 351


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1122
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 384


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1087
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 404


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 1080
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 423


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 385
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 445


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 310
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 445


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 270
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 470


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 276
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 520


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 236
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 520


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 742
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 571


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 730
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 590


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 765
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 607


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 859
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 651


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 824
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 651


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 857
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 688


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 762
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 749


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 742
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 760


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 741
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 806


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 8
Coin : 850
ATK : 120
DEF : 117
SPD : 44
Health : 1463
Stamina : 138
EXP : 840


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1451
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1386
ATK : 139

DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 24


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1382
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 53


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1302
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 102


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1277
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 102


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1210
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 134


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1130
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 181


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1048
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 222


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1680
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 300


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1655
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 321


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1616
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 359


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1556
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 371


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1514
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 385


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1553
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 420


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1526
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 478


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1186
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 562


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 1249
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 595


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 390
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 621


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 382
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 633


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 342
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 633


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 302
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 633


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 319
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 691


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 294
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 691


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 239
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 691


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 214
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 706


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 237
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 763


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 208
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 786


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 283
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 827


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 329
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 883


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 287
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 910


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : 257
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 910


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : -311
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 931


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : -416
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 957


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 9
Coin : -451
ATK : 139
DEF : 127
SPD : 51
Health : 1540
Stamina : 142
EXP : 989


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -501
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 14


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -1301
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 37


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -1356
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 87


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -1306
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 143


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -1348
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 181


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -1398
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 201


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -950
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 273


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -886
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 341


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -386
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 392


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -351
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 423


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -344
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 462


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -369
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 476


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -282
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 517


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : -248
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 570


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 261
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 636


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 231
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 670


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 180
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 687


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 171
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 727


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 190
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 763


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 190
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 763


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 88
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 796


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 13
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 853


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 11
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 859


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 77
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 902


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 134
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 933


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 68
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 986


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 10
Coin : 115
ATK : 148
DEF : 136
SPD : 60
Health : 1603
Stamina : 146
EXP : 1007


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 712
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 804
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 71


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 749
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 112


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 824
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 140


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 742
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 194


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 662
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 216


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 696
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 248


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1178
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 314


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1211
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 320


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1161
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 320


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1274
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 381

Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 327
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 389


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 262
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 413


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 701
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 494


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 726
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 531


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 748
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 587


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1341
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 669


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1357
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 682


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1954
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 742


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 1946
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 774


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2524
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 855


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2512
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 893


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2442
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 893


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2385
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 925


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2454
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 953


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2918
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 1047


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2976
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 1088


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 2960
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 1110


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 3447
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 1164


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 11
Coin : 3463
ATK : 168
DEF : 149
SPD : 64
Health : 1680
Stamina : 155
EXP : 1196


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3423
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 20


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3439
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 39


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3355
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 83


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3427
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 108


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3511
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 168


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3471
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 168


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3503
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 182


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4111
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 285


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4049
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 295


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4100
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 306


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4025
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 333


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4000
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 381


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3991
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 410


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 3951
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 446


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4019
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 479


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4644
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 598


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4552
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 626


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5060
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 695


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5059
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 721


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5032
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 740


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5039
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 787


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4979
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 817


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5472
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 880


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5465
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 942


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5466
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 973


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5552
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 984


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5605
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1039


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5545
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1062


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 4922
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1084


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5062
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1175


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5055
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1203


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 12
Coin : 5079
ATK : 183
DEF : 158
SPD : 69
Health : 1754
Stamina : 157
EXP : 1253


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5122
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5133
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 56


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5093
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 56


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5063
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 86


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5021
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 107


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4954
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 130


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4938
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 180


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4961
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 210


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4320
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 210


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4250
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 235


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4904
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 299


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4925
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 333


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4978
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 378


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4980
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 420


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4235
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 431


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4264
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 478


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4243
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 493


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4288
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 532


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4261
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 549


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4370
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 586


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5062
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 711


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5154
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 759


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5172
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 821


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5147
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 863


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5087
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 882


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5135
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 899


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4111
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 912


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4695
ATK : 198
DEF : 177
SPD : 72

Health : 1825
Stamina : 160
EXP : 1006


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4670
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1037


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5331
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1095


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5333
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1105


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5308
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1129


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5303
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1175


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5268
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1188


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4629
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1205


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 4567
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1251


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 13
Coin : 5164
ATK : 198
DEF : 177
SPD : 72
Health : 1825
Stamina : 160
EXP : 1331


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5641
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5641
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 18


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5732
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 50


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6234
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 155


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6164
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 169


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6169
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 253


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6087
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 281


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6045
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 304


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 6042
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 336


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5940
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 349


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5905
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 368


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5993
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 416


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5316
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 416


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5336
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 476


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5371
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 507


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5513
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 531


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5494
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 536


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5452
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 551


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5497
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 613


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5410
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 643


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4589
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 654


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4588
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 661


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4627
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 703


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4502
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 724


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4390
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 762


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4891
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 826


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4797
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 860


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5350
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 926


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5323
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 946


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4579
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 946


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4485
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 963


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4523
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 990


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4575
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1012


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4576
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1107


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4622
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1134


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4543
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1197


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4545
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1225


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4597
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1254


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4475
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1266


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 5001
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1354


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 3985
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1380


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 14
Coin : 4539
ATK : 209
DEF : 191
SPD : 74
Health : 1871
Stamina : 170
EXP : 1480


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4608
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 0


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4639
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 25


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5188
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 120


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5204
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 129


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5196
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 161


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5156
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 180


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5096
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 180


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5145
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 205


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5610
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 328


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5568
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 328


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5612
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 366


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5520
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 452


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 5448
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 452


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4876
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 452


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4830
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 505


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4838
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 566


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4925
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 581


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4955
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 595


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4959
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 631


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4951
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 701


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4927
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 712


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4997
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 731


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4995
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 792


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4940
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 792


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4969
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 831


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4999
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 890


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4939
ATK : 225
DEF : 207
SPD : 83
Health : 1952
Stamina : 177
EXP : 890


Name : gerald
Age : 20
Kelamin : Perempuan
sex_Role : Dewasa Muda
Level : 15
Coin : 4869
ATK : 225
DEF : 207
SPD : 83
Health : 1952

Stamina : 177
EXP : 912

# **Comparation Code**

In [65]:
import timeit
import numpy as np
from timeit import Timer

def ageUp1():
    karakter_list = []
    karakter_info = [[],[],[],[],[],[],[],[],[],[]]
    for i in range(6000):
        if i < 2400:
            umur = random.randint(15, 40)
        else:
            umur = random.randint(1, 99)
        karakter_list.append(karakter("user-"+str(i+1),umur))
        karakter_info[0].append(karakter_list[i].name)
        karakter_info[1].append(karakter_list[i].age)
        karakter_info[2].append(karakter_list[i].power.atk)
        karakter_info[3].append(karakter_list[i].power.defend)
        karakter_info[4].append(karakter_list[i].power.health)
        karakter_info[5].append(karakter_list[i].power.spd)
        karakter_info[6].append(karakter_list[i].power.stamina)
        karakter_info[7].append(0)
        karakter_info[8].append(0)
        karakter_info[9].append("-")
        df = pd.DataFrame(karakter_info)
        df = df.transpose()
        df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose", "Class"], axis=1)

def ageUp2():
    karakter_list = [karakter("user-"+str(i+1),1) for i in range(6000)]
    karakter_info = [[],[],[],[],[],[],[],[],[],[]]
    for char in karakter_list:
        karakter_info[0].append(char.name)
        karakter_info[1].append(char.age)
        karakter_info[2].append(char.power.atk)
        karakter_info[3].append(char.power.defend)
        karakter_info[4].append(char.power.health)
        karakter_info[5].append(char.power.spd)
        karakter_info[6].append(char.power.stamina)
        karakter_info[7].append(0)
        karakter_info[8].append(0)
        karakter_info[9].append("-")
        df = pd.DataFrame(karakter_info)
        df = df.transpose()
        df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose", "Class"], axis=1)

expSize = 100

t1 = Timer("ageUp1()", "from __main__ import ageUp1")
st1 = t1.timeit(number=expSize)
print("Pertama ",st1, "milliseconds")

t2 = Timer("ageUp2()", "from __main__ import ageUp2")
print("Kedua ",t2.timeit(number=expSize), "milliseconds")

KeyboardInterrupt:

# **Import**

In [79]:
import random
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
import joblib, math

# **Main System**

In [174]:
makanan = {"Rendang":[20,62], "Sate":[15,57], "Nasi Goreng":[10,52], "Steak":[22,64], "Bakwan":[5,47], "Ayam Goreng":[7,49]}

def ageUpList(karakter_list):
    for char in karakter_list:
        char.age += 1

def ageUp(karakter):
    if karakter.age < 10:
        karakter.coin += 500
    karakter.age += 1
    return karakter

def gaji(karakter_list):
    for i in range(len(karakter_list)-1):
        if karakter_list[i].role == "King" or karakter_list[i].role == "Queen":
            karakter_list[i].coin += 2500
        elif karakter_list[i].role == "Panglima":
            karakter_list[i].coin += 1000
        elif karakter_list[i].role == "Prajurit":
            karakter_list[i].coin += 500
        else:
            karakter_list[i].coin += 100

def daily(karakter_list):
    for char in karakter_list:
        char.setSexRole()
        temp_stamina = char.power.stamina
        karakter_atk = [char2.power.atk for char2 in karakter_list]
        rerata_atk = int(sum(karakter_atk)/len(karakter_atk))
        # Di ulang terus sampai stamina habis
        while(temp_stamina > 0):

            if char.batas_hungry < 0:
                char.batas_hungry = 0
            elif char.batas_hungry < 30:
                char.batas_hungry = char.makan()
            elif char.batas_hungry > 100:
                char.batas_hungry = 100
            else:
                if char.power.stamina < 25:
                    stamina = char.power.stamina
                    hungry = 1
                else:
                    stamina = random.randint(25, char.power.stamina)
                    hungry = random.randint(10, 30)

                temp_stamina -= stamina
                char.batas_hungry -= hungry

                kegiatan = random.randint(0, 100)

        #         if char.power.atk > rerata_atk:
        #           kegiatan = random.randint(0, 100)
        #         else:
        #           kegiatan = random.randint(11, 100)
        
                # Jika umur di bawah 10 hanya latihan jika tidak random
                if char.age < 15:
                    if kegiatan <= 50:
                        char.latih()
                    else:
                        pass
                else:
                    if kegiatan <= 1:
                        char.foyaFoya()
                    elif kegiatan <= 6:
                        char.boss()
                    elif kegiatan <= 36:
                        char.latih()
                    elif kegiatan <= 66:
                        char.hunt()
                    else:
                        pass

    return karakter_list

def duel(karakterA, karakterB):
    healthA = karakterA.power.health
    healthB = karakterB.power.health

    if(karakterA.power.spd >= karakterB.power.spd):
        while(healthA > 0 and healthB > 0):
            dmg = karakterA.serang(karakterB)
            healthB -= dmg
            dmg = karakterB.serang(karakterA)
            healthA -= dmg
    else:
        while(healthA > 0 and healthB > 0):
            dmg = karakterB.serang(karakterA)
            healthA -= dmg
            dmg = karakterA.serang(karakterB)
            healthB -= dmg
      
    if(healthA <= 0):
        # print(karakterB.name+" Winner")
        # exp_duel = random.randint(30, 50)
        # ExpUp(karakterB, exp_duel)
        # exp_duel = random.randint(10, 30)
        # ExpUp(karakterA, exp_duel)
        return karakterB.name
    else:
        # print(karakterA.name+" Winner")
        # exp_duel = random.randint(30, 50)
        # ExpUp(karakterA, exp_duel)
        # exp_duel = random.randint(10, 30)
        # ExpUp(karakterB, exp_duel)
        return karakterA.name

def ExpUp(karakter, exp_new):
    karakter.power.exp += exp_new
    if karakter.power.exp >= karakter.power.batas_exp:
        levelUp(karakter)

def levelUp(karakter):

  # get new Stats
    if karakter.age < 10:
        health_new = random.randint(10, 50)
        spd_new = random.randint(1, 5)
        defend_new = random.randint(1, 8)
        atk_new = random.randint(1, 8)
        stamina_new = random.randint(0, 2)
    else:
        health_new = random.randint(40, 90)
        spd_new = random.randint(2, 10)
        defend_new = random.randint(8, 20)
        atk_new = random.randint(8, 20)
        stamina_new = random.randint(2, 10)

    # plus new Stats
    karakter.power.health += health_new
    karakter.power.spd += spd_new
    karakter.power.defend += defend_new
    karakter.power.atk += atk_new
    karakter.power.stamina += stamina_new

    karakter.level += 1
    karakter.power.batas_exp += 100
    karakter.power.exp = 0

def cariPasangan(karakter_list):
    
    karakter_list_berumur = []
    karakter_list_berumur = [char for char in karakter_list if char.age >= 18 and char.age <= 50 and char.siap_pasangan == False]
    if len(karakter_list_berumur) > 0:
        karakter_siap = random.choices(karakter_list_berumur, k=math.ceil(len(karakter_list_berumur)*0.01))
        karakter_list_berumur_p = [char for char in karakter_siap if char.sex == "Perempuan"]
        karakter_list_berumur_l = [char for char in karakter_siap if char.sex == "Laki-laki"]
        banyak_pasangan = min([len(karakter_list_berumur_p), len(karakter_list_berumur_l)])
        if banyak_pasangan > 0:
            # keluarga_list
            for i in range(banyak_pasangan):

                perempuan = random.choices(karakter_list_berumur_p)[0]
                karakter_list_berumur_p.remove(perempuan)
                laki = random.choices(karakter_list_berumur_l)[0]
                karakter_list_berumur_l.remove(laki)
                laki.pasangan = perempuan.name
                laki.siap_pasangan = True
                perempuan.pasangan = laki.name
                perempuan.siap_pasangan = True
                keluarga_list.append(Keluarga(laki, perempuan))

def updateKeluarga(karakter_list, keluarga_list, list_girl, list_boy):
    for keluarga in keluarga_list:
        int_anak = random.randint(0, 100)
        if len(keluarga.anak) >= 3:
            batas_persen = 5
        else:
            batas_persen = 20
        if int_anak < batas_persen:
            kelamin = random.randint(0, 10)
            if kelamin < 5:
                sex = "Laki-laki"
                nama = random.choices(list_boy)[0]
                list_boy.remove(nama)
            else:
                sex = "Perempuan"
                nama = random.choices(list_girl)[0]
                list_girl.remove(nama)

            karakter_list.append(keluarga.createAnak(nama, 1, sex))
    return karakter_list, keluarga_list, list_girl, list_boy

def dead(karakter_list):
    int_mati = random.randint(0, 100)
    if int_mati < 1:
        jumlah_mati = random.randint(1, 5)
        for i in range(jumlah_mati):
            char_mati = random.choices(karakter_list)[0]
            karakter_list.remove(char_mati)
            print(char_mati.name + " Mati Random")
        
    karakter_list_berumur = [char for char in karakter_list if char.age >= 100]
    for char in karakter_list_berumur:
        int_mati = random.randint(0, 100)
        if int_mati < 5:
            karakter_list.remove(char)
            print(char.name + " Mati!!!")

class kekuatan:

    def __init__(self, age):
        self.atk = random.randint(1, 20)
        self.defend = random.randint(0, 20)
        self.health = random.randint(200, 1000)
        self.spd = random.randint(0, 10)
        self.exp = 0
        self.batas_exp = 100
        if age < 15:
            self.stamina = int(random.randint(25, 75) * (age - 1)/(14 - 1)) + 1
        elif age >= 15 and age <= 40 :
            self.stamina = random.randint(75, 150)
        else:
            self.stamina = int((random.randint(25, 75) / ((age - 40)/(100 - 40))) / 10)

class karakter:

    def __init__(self, name, age, sex):
        self.name = name
        if age <= 0:
            age = 1
        elif age > 100:
            age = 100
        self.age = age
        
        self.setSexRole()
        
        self.power = kekuatan(age)
        self.level = 0
        self.coin = 750
        self.batas_hungry = 100
        self.sex = sex
        self.role = "Penduduk"
        
        self.pasangan = None
        self.siap_pasangan = False
    
    def setSexRole(self):
        if self.age < 7:
            self.sex_role = "Anak-anak"
        elif self.age < 15:
            self.sex_role = "Remaja"
        elif self.age < 30:
            self.sex_role = "Dewasa Muda"
        elif self.age < 60:
            self.sex_role = "Dewasa Tua"
        else:
            self.sex_role = "Lansia"
  
    def latih(self):
        if self.age < 10:
              exp_latihan = random.randint(2, 10)
        else:
              exp_latihan = random.randint(10, 30)
        ExpUp(self, exp_latihan)
  
    def hunt(self):
        self.coin += random.randint(50, 100)
        exp_hunt = random.randint(5, 40)
        ExpUp(self, exp_hunt)

    def boss(self):
        self.coin += random.randint(500, 700)
        exp_boss = random.randint(50, 70)
        ExpUp(self, exp_boss)

    def foyaFoya(self):
        self.coin -= random.randint(500, 2000)

    def serang(self, musuh):
        dmg = self.power.atk*(100/(100+musuh.power.defend)) * random.uniform(0.75, 1.25)
        critical = random.randint(0, 100)
        miss = random.randint(0, 100)
        if critical <= 20:
              dmg *= 2
        if miss <= 20:
              dmg *= 0
        return dmg

    def makan(self):
        keys = list(makanan.keys())
        makan_pilihan = random.randint(0, len(keys)-1)
        if self.age > 10:
            self.batas_hungry += (makanan.get(keys[makan_pilihan])[1] - 30)
            self.coin -= (makanan.get(keys[makan_pilihan])[0] + 20)
        else:
            self.batas_hungry += makanan.get(keys[makan_pilihan])[1]
            self.coin -= makanan.get(keys[makan_pilihan])[0]
        return self.batas_hungry

    def info(self):
        print("Name : "+self.name)
        print("Age : "+str(self.age))
        print("Kelamin : "+self.sex)
        print("sex_Role : "+self.sex_role)
        print("Pasangan : "+str(self.pasangan))
        print("Level : "+str(self.level))
        print("Coin : "+str(self.coin))
        print("ATK : "+str(self.power.atk))
        print("DEF : "+str(self.power.defend))
        print("SPD : "+str(self.power.spd))
        print("Health : "+str(self.power.health))
        print("Stamina : "+str(self.power.stamina))
        print("EXP : "+str(self.power.exp))
        print(" ")

class Keluarga:
    
    def __init__(self, suami, istri):
        self.suami = suami
        self.istri = istri
        self.anak = []
        
    def suamiInfo(self):
        self.suami.info()
    def istriInfo(self):
        self.istri.info()
    def anakInfo(self):
        for ank in self.anak:
            ank.info()
            print("-----------")
            
    def createAnak(self, nama, umur, sex):
        anak = karakter(nama, umur, sex)
        self.anak.append(anak)
        return anak

# **Set People**

In [81]:
df_girl = pd.read_csv("nama_girl.csv")
list_girl = list(df_girl["Name"])
list_girl

['Mary',
 'Anna',
 'Emma',
 'Elizabeth',
 'Minnie',
 'Margaret',
 'Ida',
 'Alice',
 'Bertha',
 'Sarah',
 'Annie',
 'Clara',
 'Ella',
 'Florence',
 'Cora',
 'Martha',
 'Laura',
 'Nellie',
 'Grace',
 'Carrie',
 'Maude',
 'Mabel',
 'Bessie',
 'Jennie',
 'Gertrude',
 'Julia',
 'Hattie',
 'Edith',
 'Mattie',
 'Rose',
 'Catherine',
 'Lillian',
 'Ada',
 'Lillie',
 'Helen',
 'Jessie',
 'Louise',
 'Ethel',
 'Lula',
 'Myrtle',
 'Eva',
 'Frances',
 'Lena',
 'Lucy',
 'Edna',
 'Maggie',
 'Pearl',
 'Daisy',
 'Fannie',
 'Josephine',
 'Dora',
 'Rosa',
 'Katherine',
 'Agnes',
 'Marie',
 'Nora',
 'May',
 'Mamie',
 'Blanche',
 'Stella',
 'Ellen',
 'Nancy',
 'Effie',
 'Sallie',
 'Nettie',
 'Della',
 'Lizzie',
 'Flora',
 'Susie',
 'Maud',
 'Mae',
 'Etta',
 'Harriet',
 'Sadie',
 'Caroline',
 'Katie',
 'Lydia',
 'Elsie',
 'Kate',
 'Susan',
 'Mollie',
 'Alma',
 'Addie',
 'Georgia',
 'Eliza',
 'Lulu',
 'Nannie',
 'Lottie',
 'Amanda',
 'Belle',
 'Charlotte',
 'Rebecca',
 'Ruth',
 'Viola',
 'Olive',
 'Amelia',
 'Hannah',
 'Jane',
 'Virginia',
 'Emily',
 'Matilda',
 'Irene',
 'Kathryn',
 'Esther',
 'Willie',
 'Henrietta',
 'Ollie',
 'Amy',
 'Rachel',
 'Sara',
 'Estella',
 'Theresa',
 'Augusta',
 'Ora',
 'Pauline',
 'Josie',
 'Lola',
 'Sophia',
 'Leona',
 'Anne',
 'Mildred',
 'Ann',
 'Beulah',
 'Callie',
 'Lou',
 'Delia',
 'Eleanor',
 'Barbara',
 'Iva',
 'Louisa',
 'Maria',
 'Mayme',
 'Evelyn',
 'Estelle',
 'Nina',
 'Betty',
 'Marion',
 'Bettie',
 'Dorothy',
 'Luella',
 'Inez',
 'Lela',
 'Rosie',
 'Allie',
 'Millie',
 'Janie',
 'Cornelia',
 'Victoria',
 'Ruby',
 'Winifred',
 'Alta',
 'Celia',
 'Christine',
 'Beatrice',
 'Birdie',
 'Harriett',
 'Mable',
 'Myra',
 'Sophie',
 'Tillie',
 'Isabel',
 'Sylvia',
 'Carolyn',
 'Isabelle',
 'Leila',
 'Sally',
 'Ina',
 'Essie',
 'Bertie',
 'Nell',
 'Alberta',
 'Katharine',
 'Lora',
 'Rena',
 'Mina',
 'Rhoda',
 'Mathilda',
 'Abbie',
 'Eula',
 'Dollie',
 'Hettie',
 'Eunice',
 'Fanny',
 'Ola',
 'Lenora',
 'Adelaide',
 'Christina',
 'Lelia',
 'Nelle',
 'Sue',
 'Johanna',
 'Lilly',
 'Lucinda',
 'Minerva',
 'Lettie',
 'Roxie',
 'Cynthia',
 'Helena',
 'Hilda',
 'Hulda',
 'Bernice',
 'Genevieve',
 'Jean',
 'Cordelia',
 'Marian',
 'Francis',
 'Jeanette',
 'Adeline',
 'Gussie',
 'Leah',
 'Lois',
 'Lura',
 'Mittie',
 'Hallie',
 'Isabella',
 'Olga',
 'Phoebe',
 'Teresa',
 'Hester',
 'Lida',
 'Lina',
 'Winnie',
 'Claudia',
 'Marguerite',
 'Vera',
 'Cecelia',
 'Bess',
 'Emilie',
 'John',
 'Rosetta',
 'Verna',
 'Myrtie',
 'Cecilia',
 'Elva',
 'Olivia',
 'Ophelia',
 'Georgie',
 'Elnora',
 'Violet',
 'Adele',
 'Lily',
 'Linnie',
 'Loretta',
 'Madge',
 'Polly',
 'Virgie',
 'Eugenia',
 'Lucile',
 'Lucille',
 'Mabelle',
 'Rosalie',
 'Kittie',
 'Meta',
 'Angie',
 'Dessie',
 'Georgiana',
 'Lila',
 'Regina',
 'Selma',
 'Wilhelmina',
 'Bridget',
 'Lilla',
 'Malinda',
 'Vina',
 'Freda',
 'Gertie',
 'Jeannette',
 'Louella',
 'Mandy',
 'Roberta',
 'Cassie',
 'Corinne',
 'Ivy',
 'Melissa',
 'Lyda',
 'Naomi',
 'Norma',
 'Bell',
 'Margie',
 'Nona',
 'Zella',
 'Dovie',
 'Elvira',
 'Erma',
 'Irma',
 'Leota',
 'William',
 'Artie',
 'Blanch',
 'Charity',
 'Lorena',
 'Lucretia',
 'Orpha',
 'Alvina',
 'Annette',
 'Catharine',
 'Elma',
 'Geneva',
 'Janet',
 'Lee',
 'Leora',
 'Lona',
 'Miriam',
 'Zora',
 'Linda',
 'Octavia',
 'Sudie',
 'Zula',
 'Adella',
 'Alpha',
 'Frieda',
 'George',
 'Joanna',
 'Leonora',
 'Priscilla',
 'Tennie',
 'Angeline',
 'Docia',
 'Ettie',
 'Flossie',
 'Hanna',
 'Letha',
 'Minta',
 'Retta',
 'Rosella',
 'Adah',
 'Berta',
 'Elisabeth',
 'Elise',
 'Goldie',
 'Leola',
 'Margret',
 'Adaline',
 'Floy',
 'Idella',
 'Juanita',
 'Lenna',
 'Lucie',
 'Missouri',
 'Nola',
 'Zoe',
 'Eda',
 'Isabell',
 'James',
 'Julie',
 'Letitia',
 'Madeline',
 'Malissa',
 'Mariah',
 'Pattie',
 'Vivian',
 'Almeda',
 'Aurelia',
 'Claire',
 'Dolly',
 'Hazel',
 'Jannie',
 'Kathleen',
 'Kathrine',
 'Lavinia',
 'Marietta',
 'Melvina',
 'Ona',
 'Pinkie',
 'Samantha',
 'Susanna',
 'Chloe',
 'Donnie',
 'Elsa',
 'Gladys',
 'Matie',
 'Pearle',
 'Vesta',
 'Vinnie',
 'Antoinette',
 'Clementine',
 'Edythe',
 'Harriette',
 'Libbie',
 'Lilian',
 'Lue',
 'Lutie',
 'Magdalena',
 'Meda',
 'Rita',
 'Tena',
 'Zelma',
 'Adelia',
 'Annetta',
 'Antonia',
 'Dona',
 'Elizebeth',
 'Georgianna',
 'Gracie',
 'Iona',
 'Lessie',
 'Leta',
 'Liza',
 'Mertie',
 'Molly',
 'Neva',
 'Oma',
 'Alida',
 'Alva',
 'Cecile',
 'Cleo',
 'Donna',
 'Ellie',
 'Ernestine',
 'Evie',
 'Frankie',
 'Helene',
 'Minna',
 'Myrta',
 'Prudence',
 'Queen',
 'Rilla',
 'Savannah',
 'Tessie',
 'Tina',
 'Agatha',
 'America',
 'Anita',
 'Arminta',
 'Dorothea',
 'Ira',
 'Luvenia',
 'Marjorie',
 'Maybelle',
 'Mellie',
 'Nan',
 'Pearlie',
 'Sidney',
 'Velma',
 'Clare',
 'Constance',
 'Dixie',
 'Ila',
 'Iola',
 'Jimmie',
 'Louvenia',
 'Lucia',
 'Ludie',
 'Luna',
 'Metta',
 'Patsy',
 'Phebe',
 'Sophronia',
 'Adda',
 'Avis',
 'Betsy',
 'Bonnie',
 'Cecil',
 'Cordie',
 'Emmaline',
 'Ethelyn',
 'Hortense',
 'June',
 'Louie',
 'Lovie',
 'Marcella',
 'Melinda',
 'Mona',
 'Odessa',
 'Veronica',
 'Aimee',
 'Annabel',
 'Ava',
 'Bella',
 'Carolina',
 'Cathrine',
 'Christena',
 'Clyde',
 'Dena',
 'Dolores',
 'Eleanore',
 'Elmira',
 'Fay',
 'Frank',
 'Jenny',
 'Kizzie',
 'Lonnie',
 'Loula',
 'Magdalene',
 'Mettie',
 'Mintie',
 'Peggy',
 'Reba',
 'Serena',
 'Vida',
 'Zada',
 'Abigail',
 'Celestine',
 'Celina',
 'Claudie',
 'Clemmie',
 'Connie',
 'Daisie',
 'Deborah',
 'Dessa',
 'Easter',
 'Eddie',
 'Emelia',
 'Emmie',
 'Imogene',
 'India',
 'Jeanne',
 'Joan',
 'Lenore',
 'Liddie',
 'Lotta',
 'Mame',
 'Nevada',
 'Rachael',
 'Sina',
 'Willa',
 'Aline',
 'Beryl',
 'Charles',
 'Daisey',
 'Dorcas',
 'Edmonia',
 'Effa',
 'Eldora',
 'Eloise',
 'Emmer',
 'Era',
 'Gena',
 'Henry',
 'Iris',
 'Izora',
 'Lennie',
 'Lissie',
 'Mallie',
 'Malvina',
 'Mathilde',
 'Mazie',
 'Queenie',
 'Robert',
 'Rosina',
 'Salome',
 'Theodora',
 'Therese',
 'Vena',
 'Wanda',
 'Wilda',
 'Altha',
 'Anastasia',
 'Besse',
 'Bird',
 'Birtie',
 'Clarissa',
 'Claude',
 'Delilah',
 'Diana',
 'Emelie',
 'Erna',
 'Fern',
 'Florida',
 'Frona',
 'Hilma',
 'Joseph',
 'Juliet',
 'Leonie',
 'Lugenia',
 'Mammie',
 'Manda',
 'Manerva',
 'Manie',
 'Nella',
 'Paulina',
 'Philomena',
 'Rae',
 'Selina',
 'Sena',
 'Theodosia',
 'Tommie',
 'Una',
 'Vernie',
 'Adela',
 'Althea',
 'Amalia',
 'Amber',
 'Angelina',
 'Annabelle',
 'Anner',
 'Arie',
 'Clarice',
 'Corda',
 'Corrie',
 'Dell',
 'Dellar',
 'Donie',
 'Doris',
 'Elda',
 'Elinor',
 'Emeline',
 'Emilia',
 'Esta',
 'Estell',
 'Etha',
 'Fred',
 'Hope',
 'Indiana',
 'Ione',
 'Jettie',
 'Johnnie',
 'Josiephine',
 'Kitty',
 'Lavina',
 'Leda',
 'Letta',
 'Mahala',
 'Marcia',
 'Margarette',
 'Maudie',
 'Maye',
 'Norah',
 'Oda',
 'Patty',
 'Paula',
 'Permelia',
 'Rosalia',
 'Roxanna',
 'Sula',
 'Vada',
 'Winnifred',
 'Adline',
 'Almira',
 'Alvena',
 'Arizona',
 'Becky',
 'Bennie',
 'Bernadette',
 'Camille',
 'Cordia',
 'Corine',
 'Dicie',
 'Dove',
 'Drusilla',
 'Elena',
 'Elenora',
 'Elmina',
 'Ethyl',
 'Evalyn',
 'Evelina',
 'Faye',
 'Huldah',
 'Idell',
 'Inga',
 'Irena',
 'Jewell',
 'Kattie',
 'Lavenia',
 'Leslie',
 'Lovina',
 'Lulie',
 'Magnolia',
 'Margeret',
 'Margery',
 'Media',
 'Millicent',
 'Nena',
 'Ocie',
 'Orilla',
 'Osie',
 'Pansy',
 'Ray',
 'Rosia',
 'Rowena',
 'Shirley',
 'Tabitha',
 'Thomas',
 'Verdie',
 'Walter',
 'Zetta',
 'Zoa',
 'Zona',
 'Albertina',
 'Albina',
 'Alyce',
 'Amie',
 'Angela',
 'Annis',
 'Carol',
 'Carra',
 'Clarence',
 'Clarinda',
 'Delphia',
 'Dillie',
 'Doshie',
 'Drucilla',
 'Etna',
 'Eugenie',
 'Eulalia',
 'Eve',
 'Felicia',
 'Florance',
 'Fronie',
 'Geraldine',
 'Gina',
 'Glenna',
 'Grayce',
 'Hedwig',
 'Jessica',
 'Jossie',
 'Katheryn',
 'Katy',
 'Lea',
 'Leanna',
 'Leitha',
 'Leone',
 'Lidie',
 'Loma',
 'Lular',
 'Magdalen',
 'Maymie',
 'Minervia',
 'Muriel',
 'Neppie',
 'Olie',
 'Onie',
 'Osa',
 'Otelia',
 'Paralee',
 'Patience',
 'Rella',
 'Rillie',
 'Rosanna',
 'Theo',
 'Tilda',
 'Tishie',
 'Tressa',
 'Viva',
 'Yetta',
 'Zena',
 'Zola',
 'Abby',
 'Aileen',
 'Alba',
 'Alda',
 'Alla',
 'Alverta',
 'Ara',
 'Ardelia',
 'Ardella',
 'Arrie',
 'Arvilla',
 'Augustine',
 'Aurora',
 'Bama',
 'Bena',
 'Byrd',
 'Calla',
 'Camilla',
 'Carey',
 'Carlotta',
 'Celestia',
 'Cherry',
 'Cinda',
 'Classie',
 'Claudine',
 'Clemie',
 'Clifford',
 'Clyda',
 'Creola',
 'Debbie',
 'Dee',
 'Dinah',
 'Doshia',
 'Ednah',
 'Edyth',
 'Eleanora',
 'Electa',
 'Eola',
 'Erie',
 'Eudora',
 'Euphemia',
 'Evalena',
 'Evaline',
 'Faith',
 'Fidelia',
 'Freddie',
 'Golda',
 'Harry',
 'Helma',
 'Hermine',
 'Hessie',
 'Ivah',
 'Janette',
 'Jennette',
 'Joella',
 'Kathryne',
 'Lacy',
 'Lanie',
 'Lauretta',
 'Leana',
 'Leatha',
 'Leo',
 'Liller',
 'Lillis',
 'Louetta',
 'Madie',
 'Mai',
 'Martina',
 'Maryann',
 'Melva',
 'Mena',
 'Mercedes',
 'Merle',
 'Mima',
 'Minda',
 'Monica',
 'Nealie',
 'Netta',
 'Nolia',
 'Nonie',
 'Odelia',
 'Ottilie',
 'Phyllis',
 'Robbie',
 'Sabina',
 'Sada',
 'Sammie',
 'Suzanne',
 'Sybilla',
 'Thea',
 'Tressie',
 'Vallie',
 'Venie',
 'Viney',
 'Wilhelmine',
 'Winona',
 'Zelda',
 'Zilpha',
 'Adelle',
 'Adina',
 'Adrienne',
 'Albertine',
 'Alys',
 'Ana',
 'Araminta',
 'Arthur',
 'Birtha',
 'Bulah',
 'Caddie',
 'Celie',
 'Charlotta',
 'Clair',
 'Concepcion',
 'Cordella',
 'Corrine',
 'Delila',
 'Delphine',
 'Dosha',
 'Edgar',
 'Elaine',
 'Elisa',
 'Ellar',
 'Elmire',
 'Elvina',
 'Ena',
 'Estie',
 'Etter',
 'Fronnie',
 'Genie',
 'Georgina',
 'Glenn',
 'Gracia',
 'Guadalupe',
 'Gwendolyn',
 'Hassie',
 'Honora',
 'Icy',
 'Isa',
 'Isadora',
 'Jesse',
 'Jewel',
 'Joe',
 'Johannah',
 'Juana',
 'Judith',
 'Judy',
 'Junie',
 'Lavonia',
 'Lella',
 'Lemma',
 'Letty',
 'Linna',
 'Littie',
 'Lollie',
 'Lorene',
 'Louis',
 'Love',
 'Lovisa',
 'Lucina',
 'Lynn',
 'Madora',
 'Mahalia',
 'Manervia',
 'Manuela',
 'Margarett',
 'Margaretta',
 'Margarita',
 'Marilla',
 'Mignon',
 'Mozella',
 'Natalie',
 'Nelia',
 'Nolie',
 'Omie',
 'Opal',
 'Ossie',
 'Ottie',
 'Ottilia',
 'Parthenia',
 'Penelope',
 'Pinkey',
 'Pollie',
 'Rennie',
 'Reta',
 'Roena',
 'Rosalee',
 'Roseanna',
 'Ruthie',
 'Sabra',
 'Sannie',
 'Selena',
 'Sibyl',
 'Tella',
 'Tempie',
 'Tennessee',
 'Teressa',
 'Texas',
 'Theda',
 'Thelma',
 'Thursa',
 'Ula',
 'Vannie',
 'Verona',
 'Vertie',
 'Wilma',
 'Adell',
 'Celeste',
 'Audrey',
 'Lonie',
 'Zadie',
 'Aura',
 'Elta',
 'Eveline',
 'Lelah',
 'Nanie',
 'Petra',
 'Elvie',
 'Glennie',
 'Juliette',
 'Mannie',
 'Mercy',
 'Miranda',
 'Nana',
 'Zilpah',
 'Almedia',
 'Berdie',
 'Byrdie',
 'Claribel',
 'Coral',
 'Edwina',
 'Exie',
 'Justine',
 'Malissie',
 'Myrtice',
 'Narcissus',
 'Rosamond',
 'Theresia',
 'Valeria',
 'Vessie',
 'Victorine',
 'Alfreda',
 'Alicia',
 'Arabella',
 'Arminda',
 'Audie',
 'Cammie',
 'Carmen',
 'Dottie',
 'Flo',
 'Fredericka',
 'Gloria',
 'Gusta',
 'Icie',
 'Lillia',
 'Lota',
 'Nathalie',
 'Nita',
 'Ota',
 'Ramona',
 'Texie',
 'Will',
 'Zillah',
 'Aida',
 ...]

In [82]:
df_boy = pd.read_csv("nama_boy.csv")
list_boy = list(df_boy["Name"])
list_boy

['John',
 'William',
 'James',
 'Charles',
 'George',
 'Frank',
 'Joseph',
 'Thomas',
 'Henry',
 'Robert',
 'Edward',
 'Harry',
 'Walter',
 'Arthur',
 'Fred',
 'Albert',
 'Samuel',
 'David',
 'Louis',
 'Joe',
 'Charlie',
 'Clarence',
 'Richard',
 'Andrew',
 'Daniel',
 'Ernest',
 'Will',
 'Jesse',
 'Oscar',
 'Lewis',
 'Peter',
 'Benjamin',
 'Frederick',
 'Willie',
 'Alfred',
 'Sam',
 'Roy',
 'Herbert',
 'Jacob',
 'Tom',
 'Elmer',
 'Carl',
 'Lee',
 'Howard',
 'Martin',
 'Michael',
 'Bert',
 'Herman',
 'Jim',
 'Francis',
 'Harvey',
 'Earl',
 'Eugene',
 'Ralph',
 'Ed',
 'Claude',
 'Edwin',
 'Ben',
 'Charley',
 'Paul',
 'Edgar',
 'Isaac',
 'Otto',
 'Luther',
 'Lawrence',
 'Ira',
 'Patrick',
 'Guy',
 'Oliver',
 'Theodore',
 'Hugh',
 'Clyde',
 'Alexander',
 'August',
 'Floyd',
 'Homer',
 'Jack',
 'Leonard',
 'Horace',
 'Marion',
 'Philip',
 'Allen',
 'Archie',
 'Stephen',
 'Chester',
 'Willis',
 'Raymond',
 'Rufus',
 'Warren',
 'Jessie',
 'Milton',
 'Alex',
 'Leo',
 'Julius',
 'Ray',
 'Sidney',
 'Bernard',
 'Dan',
 'Jerry',
 'Calvin',
 'Perry',
 'Dave',
 'Anthony',
 'Eddie',
 'Amos',
 'Dennis',
 'Clifford',
 'Leroy',
 'Wesley',
 'Alonzo',
 'Garfield',
 'Franklin',
 'Emil',
 'Leon',
 'Nathan',
 'Harold',
 'Matthew',
 'Levi',
 'Moses',
 'Everett',
 'Lester',
 'Winfield',
 'Adam',
 'Lloyd',
 'Mack',
 'Fredrick',
 'Jay',
 'Jess',
 'Melvin',
 'Noah',
 'Aaron',
 'Alvin',
 'Norman',
 'Gilbert',
 'Elijah',
 'Victor',
 'Gus',
 'Nelson',
 'Jasper',
 'Silas',
 'Jake',
 'Christopher',
 'Mike',
 'Percy',
 'Adolph',
 'Maurice',
 'Cornelius',
 'Felix',
 'Reuben',
 'Wallace',
 'Claud',
 'Roscoe',
 'Sylvester',
 'Earnest',
 'Hiram',
 'Otis',
 'Simon',
 'Willard',
 'Irvin',
 'Mark',
 'Jose',
 'Wilbur',
 'Abraham',
 'Virgil',
 'Clinton',
 'Elbert',
 'Leslie',
 'Marshall',
 'Owen',
 'Wiley',
 'Anton',
 'Morris',
 'Manuel',
 'Phillip',
 'Augustus',
 'Emmett',
 'Eli',
 'Nicholas',
 'Wilson',
 'Alva',
 'Harley',
 'Newton',
 'Timothy',
 'Marvin',
 'Ross',
 'Curtis',
 'Edmund',
 'Jeff',
 'Elias',
 'Harrison',
 'Stanley',
 'Columbus',
 'Lon',
 'Ora',
 'Ollie',
 'Pearl',
 'Russell',
 'Solomon',
 'Arch',
 'Asa',
 'Clayton',
 'Enoch',
 'Irving',
 'Mathew',
 'Nathaniel',
 'Scott',
 'Hubert',
 'Lemuel',
 'Andy',
 'Ellis',
 'Emanuel',
 'Joshua',
 'Millard',
 'Vernon',
 'Wade',
 'Cyrus',
 'Miles',
 'Rudolph',
 'Sherman',
 'Austin',
 'Bill',
 'Chas',
 'Lonnie',
 'Monroe',
 'Byron',
 'Edd',
 'Emery',
 'Grant',
 'Jerome',
 'Max',
 'Mose',
 'Steve',
 'Gordon',
 'Abe',
 'Pete',
 'Chris',
 'Clark',
 'Gustave',
 'Orville',
 'Lorenzo',
 'Bruce',
 'Marcus',
 'Preston',
 'Bob',
 'Dock',
 'Donald',
 'Jackson',
 'Cecil',
 'Barney',
 'Delbert',
 'Edmond',
 'Anderson',
 'Christian',
 'Glenn',
 'Jefferson',
 'Luke',
 'Neal',
 'Burt',
 'Ike',
 'Myron',
 'Tony',
 'Conrad',
 'Joel',
 'Matt',
 'Riley',
 'Vincent',
 'Emory',
 'Isaiah',
 'Nick',
 'Ezra',
 'Green',
 'Juan',
 'Clifton',
 'Lucius',
 'Porter',
 'Arnold',
 'Bud',
 'Jeremiah',
 'Taylor',
 'Forrest',
 'Roland',
 'Spencer',
 'Burton',
 'Don',
 'Emmet',
 'Gustav',
 'Louie',
 'Morgan',
 'Ned',
 'Van',
 'Ambrose',
 'Chauncey',
 'Elisha',
 'Ferdinand',
 'General',
 'Julian',
 'Kenneth',
 'Mitchell',
 'Allie',
 'Josh',
 'Judson',
 'Lyman',
 'Napoleon',
 'Pedro',
 'Berry',
 'Dewitt',
 'Ervin',
 'Forest',
 'Lynn',
 'Pink',
 'Ruben',
 'Sanford',
 'Ward',
 'Douglas',
 'Ole',
 'Omer',
 'Ulysses',
 'Walker',
 'Wilbert',
 'Adelbert',
 'Benjiman',
 'Ivan',
 'Jonas',
 'Major',
 'Abner',
 'Archibald',
 'Caleb',
 'Clint',
 'Dudley',
 'Granville',
 'King',
 'Mary',
 'Merton',
 'Antonio',
 'Bennie',
 'Carroll',
 'Freeman',
 'Josiah',
 'Milo',
 'Royal',
 'Dick',
 'Earle',
 'Elza',
 'Emerson',
 'Fletcher',
 'Judge',
 'Laurence',
 'Neil',
 'Roger',
 'Seth',
 'Glen',
 'Hugo',
 'Jimmie',
 'Johnnie',
 'Washington',
 'Elwood',
 'Gust',
 'Harmon',
 'Jordan',
 'Simeon',
 'Wayne',
 'Wilber',
 'Clem',
 'Evan',
 'Frederic',
 'Irwin',
 'Junius',
 'Lafayette',
 'Loren',
 'Madison',
 'Mason',
 'Orval',
 'Abram',
 'Aubrey',
 'Elliott',
 'Hans',
 'Karl',
 'Minor',
 'Wash',
 'Wilfred',
 'Allan',
 'Alphonse',
 'Dallas',
 'Dee',
 'Isiah',
 'Jason',
 'Johnny',
 'Lawson',
 'Lew',
 'Micheal',
 'Orin',
 'Addison',
 'Cal',
 'Erastus',
 'Francisco',
 'Hardy',
 'Lucien',
 'Randolph',
 'Stewart',
 'Vern',
 'Wilmer',
 'Zack',
 'Adrian',
 'Alvah',
 'Bertram',
 'Clay',
 'Ephraim',
 'Fritz',
 'Giles',
 'Grover',
 'Harris',
 'Isom',
 'Jesus',
 'Johnie',
 'Jonathan',
 'Lucian',
 'Malcolm',
 'Merritt',
 'Otho',
 'Perley',
 'Rolla',
 'Sandy',
 'Tomas',
 'Wilford',
 'Adolphus',
 'Angus',
 'Arther',
 'Carlos',
 'Cary',
 'Cassius',
 'Davis',
 'Hamilton',
 'Harve',
 'Israel',
 'Leander',
 'Melville',
 'Merle',
 'Murray',
 'Pleasant',
 'Sterling',
 'Steven',
 'Axel',
 'Boyd',
 'Bryant',
 'Clement',
 'Erwin',
 'Ezekiel',
 'Foster',
 'Frances',
 'Geo',
 'Houston',
 'Issac',
 'Jules',
 'Larkin',
 'Mat',
 'Morton',
 'Orlando',
 'Pierce',
 'Prince',
 'Rollie',
 'Rollin',
 'Sim',
 'Stuart',
 'Wilburn',
 'Bennett',
 'Casper',
 'Christ',
 'Dell',
 'Egbert',
 'Elmo',
 'Fay',
 'Gabriel',
 'Hector',
 'Horatio',
 'Lige',
 'Saul',
 'Smith',
 'Squire',
 'Tobe',
 'Tommie',
 'Wyatt',
 'Alford',
 'Alma',
 'Alton',
 'Andres',
 'Burl',
 'Cicero',
 'Dean',
 'Dorsey',
 'Enos',
 'Howell',
 'Lou',
 'Loyd',
 'Mahlon',
 'Nat',
 'Omar',
 'Oran',
 'Parker',
 'Raleigh',
 'Reginald',
 'Rubin',
 'Seymour',
 'Wm',
 'Young',
 'Benjamine',
 'Carey',
 'Carlton',
 'Eldridge',
 'Elzie',
 'Garrett',
 'Isham',
 'Johnson',
 'Larry',
 'Logan',
 'Merrill',
 'Mont',
 'Oren',
 'Pierre',
 'Rex',
 'Rodney',
 'Ted',
 'Webster',
 'West',
 'Wheeler',
 'Willam',
 'Al',
 'Aloysius',
 'Alvie',
 'Anna',
 'Art',
 'Augustine',
 'Bailey',
 'Benjaman',
 'Beverly',
 'Bishop',
 'Clair',
 'Cloyd',
 'Coleman',
 'Dana',
 'Duncan',
 'Dwight',
 'Emile',
 'Evert',
 'Henderson',
 'Hunter',
 'Jean',
 'Lem',
 'Luis',
 'Mathias',
 'Maynard',
 'Miguel',
 'Mortimer',
 'Nels',
 'Norris',
 'Pat',
 'Phil',
 'Rush',
 'Santiago',
 'Sol',
 'Sydney',
 'Thaddeus',
 'Thornton',
 'Tim',
 'Travis',
 'Truman',
 'Watson',
 'Webb',
 'Wellington',
 'Winfred',
 'Wylie',
 'Alec',
 'Basil',
 'Baxter',
 'Bertrand',
 'Buford',
 'Burr',
 'Cleveland',
 'Colonel',
 'Dempsey',
 'Early',
 'Ellsworth',
 'Fate',
 'Finley',
 'Gabe',
 'Garland',
 'Gerald',
 'Herschel',
 'Hezekiah',
 'Justus',
 'Lindsey',
 'Marcellus',
 'Olaf',
 'Olin',
 'Pablo',
 'Rolland',
 'Turner',
 'Verne',
 'Volney',
 'Williams',
 'Almon',
 'Alois',
 'Alonza',
 'Anson',
 'Authur',
 'Benton',
 'Billie',
 'Cornelious',
 'Darius',
 'Denis',
 'Dillard',
 'Doctor',
 'Elvin',
 'Emma',
 'Eric',
 'Evans',
 'Gideon',
 'Haywood',
 'Hilliard',
 'Hosea',
 'Lincoln',
 'Lonzo',
 'Lucious',
 'Lum',
 'Malachi',
 'Newt',
 'Noel',
 'Orie',
 'Palmer',
 'Pinkney',
 'Shirley',
 'Sumner',
 'Terry',
 'Urban',
 'Uriah',
 'Valentine',
 'Waldo',
 'Warner',
 'Wong',
 'Zeb',
 'Abel',
 'Alden',
 'Archer',
 'Avery',
 'Carson',
 'Cullen',
 'Doc',
 'Eben',
 'Elige',
 'Elizabeth',
 'Elmore',
 'Ernst',
 'Finis',
 'Freddie',
 'Godfrey',
 'Guss',
 'Hamp',
 'Hermann',
 'Isadore',
 'Isreal',
 'Jones',
 'June',
 'Lacy',
 'Lafe',
 'Leland',
 'Llewellyn',
 'Ludwig',
 'Manford',
 'Maxwell',
 'Minnie',
 'Obie',
 'Octave',
 'Orrin',
 'Ossie',
 'Oswald',
 'Park',
 'Parley',
 'Ramon',
 'Rice',
 'Stonewall',
 'Theo',
 'Tillman',
 'Addie',
 'Aron',
 'Ashley',
 'Bernhard',
 'Bertie',
 'Berton',
 'Buster',
 'Butler',
 'Carleton',
 'Carrie',
 'Clara',
 'Clarance',
 'Clare',
 'Crawford',
 'Danial',
 'Dayton',
 'Dolphus',
 'Elder',
 'Ephriam',
 'Fayette',
 'Felipe',
 'Fernando',
 'Flem',
 'Florence',
 'Ford',
 'Harlan',
 'Hayes',
 'Henery',
 'Hoy',
 'Huston',
 'Ida',
 'Ivory',
 'Jonah',
 'Justin',
 'Lenard',
 'Leopold',
 'Lionel',
 'Manley',
 'Marquis',
 'Marshal',
 'Mart',
 'Odie',
 'Olen',
 'Oral',
 'Orley',
 'Otha',
 'Press',
 'Price',
 'Quincy',
 'Randall',
 'Rich',
 'Richmond',
 'Romeo',
 'Russel',
 'Rutherford',
 'Shade',
 'Shelby',
 'Solon',
 'Thurman',
 'Tilden',
 'Troy',
 'Woodson',
 'Worth',
 'Aden',
 'Alcide',
 'Alf',
 'Algie',
 'Arlie',
 'Bart',
 'Bedford',
 'Benito',
 'Billy',
 'Bird',
 'Birt',
 'Bruno',
 'Burley',
 'Chancy',
 'Claus',
 'Cliff',
 'Clovis',
 'Connie',
 'Creed',
 'Delos',
 'Duke',
 'Eber',
 'Eligah',
 'Elliot',
 'Elton',
 'Emmitt',
 'Gene',
 'Golden',
 'Hal',
 'Hardin',
 'Harman',
 'Hervey',
 'Hollis',
 'Ivey',
 'Jennie',
 'Len',
 'Lindsay',
 'Lonie',
 'Lyle',
 'Mac',
 'Mal',
 'Math',
 'Miller',
 'Orson',
 'Osborne',
 'Percival',
 'Pleas',
 'Ples',
 'Rafael',
 'Raoul',
 'Roderick',
 'Rose',
 'Shelton',
 'Sid',
 'Theron',
 'Tobias',
 'Toney',
 'Tyler',
 'Vance',
 'Vivian',
 'Walton',
 'Watt',
 'Weaver',
 'Wilton',
 'Adolf',
 'Albin',
 'Albion',
 'Allison',
 'Alpha',
 'Alpheus',
 'Anastacio',
 'Andre',
 'Annie',
 'Arlington',
 'Armand',
 'Asberry',
 'Asbury',
 'Asher',
 'Augustin',
 'Auther',
 'Author',
 'Ballard',
 'Blas',
 'Caesar',
 'Candido',
 'Cato',
 'Clarke',
 'Clemente',
 'Colin',
 'Commodore',
 'Cora',
 'Coy',
 'Cruz',
 'Curt',
 'Damon',
 'Davie',
 'Delmar',
 'Dexter',
 'Dora',
 'Doss',
 'Drew',
 'Edson',
 'Elam',
 'Elihu',
 'Eliza',
 'Elsie',
 'Erie',
 'Ernie',
 'Ethel',
 'Ferd',
 'Friend',
 'Garry',
 'Gary',
 'Grace',
 'Gustaf',
 'Hallie',
 'Hampton',
 'Harrie',
 'Hattie',
 'Hence',
 'Hillard',
 'Hollie',
 'Holmes',
 'Hope',
 'Hyman',
 'Ishmael',
 'Jarrett',
 'Jessee',
 'Joeseph',
 'Junious',
 'Kirk',
 'Levy',
 'Mervin',
 'Michel',
 'Milford',
 'Mitchel',
 'Nellie',
 'Noble',
 'Obed',
 'Oda',
 'Orren',
 'Ottis',
 'Rafe',
 'Redden',
 'Reese',
 'Rube',
 'Ruby',
 'Rupert',
 'Salomon',
 'Sammie',
 'Sanders',
 'Soloman',
 'Stacy',
 'Stanford',
 'Stanton',
 'Thad',
 'Titus',
 'Tracy',
 'Vernie',
 'Wendell',
 'Wilhelm',
 'Willian',
 'Yee',
 'Zeke',
 'Ab',
 'Abbott',
 'Agustus',
 'Albertus',
 'Almer',
 'Alphonso',
 'Alvia',
 'Artie',
 'Arvid',
 'Ashby',
 'Augusta',
 'Aurthur',
 'Babe',
 'Baldwin',
 'Barnett',
 'Bartholomew',
 'Barton',
 'Bernie',
 'Blaine',
 'Boston',
 'Brad',
 'Bradford',
 'Bradley',
 'Brooks',
 'Buck',
 'Budd',
 'Ceylon',
 'Chalmers',
 'Chesley',
 'Chin',
 'Cleo',
 'Crockett',
 'Cyril',
 'Daisy',
 'Denver',
 'Dow',
 'Duff',
 'Edie',
 'Edith',
 'Elick',
 'Elie',
 'Eliga',
 'Eliseo',
 'Elroy',
 'Ely',
 'Ennis',
 'Enrique',
 'Erasmus',
 'Esau',
 'Everette',
 'Firman',
 'Fleming',
 'Flora',
 'Gardner',
 'Gee',
 'Gorge',
 'Gottlieb',
 'Gregorio',
 'Gregory',
 'Gustavus',
 'Halsey',
 'Handy',
 'Hardie',
 'Harl',
 'Hayden',
 'Hays',
 'Hermon',
 'Hershel',
 'Holly',
 'Hosteen',
 'Hoyt',
 'Hudson',
 'Huey',
 'Humphrey',
 'Hunt',
 'Hyrum',
 'Irven',
 'Isam',
 'Ivy',
 'Jabez',
 'Jewel',
 'Jodie',
 'Judd',
 'Julious',
 'Justice',
 'Katherine',
 'Kelly',
 'Kit',
 'Knute',
 'Lavern',
 'Lawyer',
 'Layton',
 ...]

In [83]:
# namest = "Gerald JAMES JOHN ROBERT MICHAEL WILLIAM DAVID RICHARD CHARLES JOSEPH CHRISTOPHER DANIEL PAUL MARK DONALD GEORGE KENNETH STEVEN EDWARD BRIAN RONALD ANTHONY KEVIN JASON MATTHEW GARY TIMOTHY JOSE LARRY JEFFREY FRANK SCOTT ERIC STEPHEN ANDREW RAYMOND GREGORY JOSHUA JERRY DENNIS WALTER PATRICK PETER HAROLD DOUGLAS HENRY CARL ARTHUR RYAN ROGER JOE JUAN JACK ALBERT JONATHAN JUSTIN TERRY GERALD KEITH SAMUEL WILLIE RALPH LAWRENCE NICHOLAS ROY BENJAMIN BRUCE BRANDON ADAM HARRY FRED WAYNE BILLY STEVE LOUIS JEREMY AARON RANDY HOWARD EUGENE CARLOS RUSSELL BOBBY VICTOR MARTIN ERNEST PHILLIP TODD JESSE CRAIG ALAN SHAWN CLARENCE SEAN PHILIP CHRIS JOHNNY EARL JIMMY ANTONIO DANNY BRYAN TONY LUIS MIKE STANLEY LEONARD NATHAN DALE MANUEL RODNEY CURTIS NORMAN ALLEN MARVIN VINCENT GLENN JEFFERY TRAVIS JEFF CHAD JACOB LEE MELVIN ALFRED KYLE FRANCIS BRADLEY JESUS HERBERT FREDERICK RAY JOEL EDWIN DON EDDIE RICKY TROY RANDALL BARRY ALEXANDER BERNARD MARIO LEROY FRANCISCO MARCUS MICHEAL THEODORE CLIFFORD MIGUEL OSCAR JAY JIM TOM CALVIN ALEX JON RONNIE BILL LLOYD TOMMY LEON DEREK WARREN DARRELL JEROME FLOYD LEO ALVIN TIM WESLEY GORDON DEAN GREG JORGE DUSTIN PEDRO DERRICK DAN LEWIS ZACHARY COREY HERMAN MAURICE VERNON ROBERTO CLYDE GLEN HECTOR SHANE RICARDO SAM RICK LESTER BRENT RAMON CHARLIE TYLER GILBERT GENE MARC REGINALD RUBEN BRETT ANGEL NATHANIEL RAFAEL LESLIE EDGAR MILTON RAUL BEN CHESTER CECIL DUANE FRANKLIN ANDRE ELMER BRAD GABRIEL RON MITCHELL ROLAND ARNOLD HARVEY JARED ADRIAN KARL CORY CLAUDE ERIK DARRYL JAMIE NEIL JESSIE CHRISTIAN JAVIER FERNANDO CLINTON TED MATHEW TYRONE DARREN LONNIE LANCE CODY JULIO KELLY KURT ALLAN NELSON GUY CLAYTON HUGH MAX DWAYNE DWIGHT ARMANDO FELIX JIMMIE EVERETT JORDAN IAN WALLACE KEN BOB JAIME CASEY ALFREDO ALBERTO DAVE IVAN JOHNNIE SIDNEY BYRON JULIAN ISAAC MORRIS CLIFTON WILLARD DARYL ROSS VIRGIL ANDY MARSHALL SALVADOR PERRY KIRK SERGIO MARION TRACY SETH KENT TERRANCE RENE EDUARDO TERRENCE ENRIQUE FREDDIE WADE AUSTIN STUART FREDRICK ARTURO ALEJANDRO JACKIE JOEY NICK LUTHER WENDELL JEREMIAH EVAN JULIUS DANA DONNIE OTIS SHANNON TREVOR OLIVER LUKE HOMER GERARD DOUG KENNY HUBERT ANGELO SHAUN LYLE MATT LYNN ALFONSO ORLANDO REX CARLTON ERNESTO CAMERON NEAL PABLO LORENZO OMAR WILBUR BLAKE GRANT HORACE RODERICK KERRY ABRAHAM WILLIS RICKEY JEAN IRA ANDRES CESAR JOHNATHAN MALCOLM RUDOLPH DAMON KELVIN RUDY PRESTON ALTON ARCHIE MARCO WM PETE RANDOLPH GARRY GEOFFREY JONATHON FELIPE BENNIE GERARDO ED DOMINIC ROBIN LOREN DELBERT COLIN GUILLERMO EARNEST LUCAS BENNY NOEL SPENCER RODOLFO MYRON EDMUND GARRETT SALVATORE CEDRIC LOWELL GREGG SHERMAN WILSON DEVIN SYLVESTER KIM ROOSEVELT ISRAEL JERMAINE FORREST WILBERT LELAND SIMON GUADALUPE CLARK IRVING CARROLL BRYANT OWEN RUFUS WOODROW SAMMY KRISTOPHER MACK LEVI MARCOS GUSTAVO JAKE LIONEL MARTY TAYLOR ELLIS DALLAS GILBERTO CLINT NICOLAS LAURENCE ISMAEL ORVILLE DREW JODY ERVIN DEWEY AL WILFRED JOSH HUGO IGNACIO CALEB TOMAS SHELDON ERICK FRANKIE STEWART DOYLE DARREL ROGELIO TERENCE SANTIAGO ALONZO ELIAS BERT ELBERT RAMIRO CONRAD PAT NOAH GRADY PHIL CORNELIUS LAMAR ROLANDO CLAY PERCY DEXTER BRADFORD MERLE DARIN AMOS TERRELL MOSES IRVIN SAUL ROMAN DARNELL RANDAL TOMMIE TIMMY DARRIN WINSTON BRENDAN TOBY VAN ABEL DOMINICK BOYD COURTNEY JAN EMILIO ELIJAH CARY DOMINGO SANTOS AUBREY EMMETT MARLON EMANUEL JERALD EDMOND EMIL DEWAYNE WILL OTTO TEDDY REYNALDO BRET MORGAN JESS TRENT HUMBERTO EMMANUEL STEPHAN LOUIE VICENTE LAMONT STACY GARLAND MILES MICAH EFRAIN BILLIE LOGAN HEATH RODGER HARLEY DEMETRIUS ETHAN ELDON ROCKY PIERRE JUNIOR FREDDY ELI BRYCE ANTOINE ROBBIE KENDALL ROYCE STERLING MICKEY CHASE GROVER ELTON CLEVELAND DYLAN CHUCK DAMIAN REUBEN STAN AUGUST LEONARDO JASPER RUSSEL ERWIN BENITO HANS MONTE BLAINE ERNIE CURT QUENTIN AGUSTIN MURRAY JAMAL DEVON ADOLFO HARRISON TYSON BURTON BRADY ELLIOTT WILFREDO BART JARROD VANCE DENIS DAMIEN JOAQUIN HARLAN DESMOND ELLIOT DARWIN ASHLEY GREGORIO BUDDY XAVIER KERMIT ROSCOE ESTEBAN ANTON SOLOMON SCOTTY NORBERT ELVIN WILLIAMS NOLAN CAREY ROD QUINTON HAL BRAIN ROB ELWOOD KENDRICK DARIUS MOISES SON MARLIN FIDEL THADDEUS CLIFF MARCEL ALI JACKSON RAPHAEL BRYON ARMAND ALVARO JEFFRY DANE JOESPH THURMAN NED SAMMIE RUSTY MICHEL MONTY RORY FABIAN REGGIE MASON GRAHAM KRIS ISAIAH VAUGHN GUS AVERY LOYD DIEGO ALEXIS ADOLPH NORRIS MILLARD ROCCO GONZALO DERICK RODRIGO GERRY STACEY CARMEN WILEY RIGOBERTO ALPHONSO TY SHELBY RICKIE NOE VERN BOBBIE REED JEFFERSON ELVIS BERNARDO MAURICIO HIRAM DONOVAN BASIL RILEY OLLIE NICKOLAS MAYNARD SCOT VINCE QUINCY EDDY SEBASTIAN FEDERICO ULYSSES HERIBERTO DONNELL COLE DENNY DAVIS GAVIN EMERY WARD ROMEO JAYSON DION DANTE CLEMENT COY ODELL MAXWELL JARVIS BRUNO ISSAC MARY DUDLEY BROCK SANFORD COLBY CARMELO BARNEY NESTOR HOLLIS STEFAN DONNY ART LINWOOD BEAU WELDON GALEN ISIDRO TRUMAN DELMAR JOHNATHON SILAS FREDERIC DICK KIRBY IRWIN CRUZ MERLIN MERRILL CHARLEY MARCELINO LANE HARRIS CLEO CARLO TRENTON KURTIS HUNTER AURELIO WINFRED VITO COLLIN DENVER CARTER LEONEL EMORY PASQUALE MOHAMMAD MARIANO DANIAL BLAIR LANDON DIRK BRANDEN ADAN NUMBERS CLAIR BUFORD GERMAN BERNIE WILMER JOAN EMERSON ZACHERY FLETCHER JACQUES ERROL DALTON MONROE JOSUE DOMINIQUE EDWARDO BOOKER WILFORD SONNY SHELTON CARSON THERON RAYMUNDO DAREN TRISTAN HOUSTON ROBBY LINCOLN JAME GENARO GALE BENNETT OCTAVIO CORNELL LAVERNE HUNG ARRON ANTONY HERSCHEL ALVA GIOVANNI GARTH CYRUS CYRIL RONNY STEVIE LON FREEMAN ERIN DUNCAN KENNITH CARMINE AUGUSTINE YOUNG ERICH CHADWICK WILBURN RUSS REID MYLES ANDERSON MORTON JONAS FOREST MITCHEL MERVIN ZANE RICH JAMEL LAZARO ALPHONSE RANDELL MAJOR JOHNIE JARRETT BROOKS ARIEL ABDUL DUSTY LUCIANO LINDSEY TRACEY SEYMOUR SCOTTIE EUGENIO MOHAMMED SANDY VALENTIN CHANCE ARNULFO LUCIEN FERDINAND THAD EZRA SYDNEY ALDO RUBIN ROYAL MITCH EARLE ABE WYATT MARQUIS LANNY KAREEM JAMAR BORIS ISIAH EMILE ELMO ARON LEOPOLDO EVERETTE JOSEF GAIL ELOY DORIAN RODRICK REINALDO LUCIO JERROD WESTON HERSHEL BARTON PARKER LEMUEL LAVERN BURT JULES GIL ELISEO AHMAD NIGEL EFREN ANTWAN ALDEN MARGARITO COLEMAN REFUGIO DINO OSVALDO LES DEANDRE NORMAND KIETH IVORY ANDREA TREY NORBERTO NAPOLEON JEROLD FRITZ ROSENDO MILFORD SANG DEON CHRISTOPER ALFONZO LYMAN JOSIAH BRANT WILTON RICO JAMAAL DEWITT CAROL BRENTON YONG OLIN FOSTER FAUSTINO CLAUDIO JUDSON GINO EDGARDO BERRY ALEC TANNER JARRED DONN TRINIDAD TAD SHIRLEY PRINCE PORFIRIO ODIS MARIA LENARD CHAUNCEY CHANG TOD MEL MARCELO KORY AUGUSTUS KEVEN HILARIO BUD SAL ROSARIO ORVAL MAURO DANNIE ZACHARIAH OLEN ANIBAL MILO JED FRANCES THANH DILLON AMADO NEWTON CONNIE LENNY TORY RICHIE LUPE HORACIO BRICE MOHAMED DELMER DARIO REYES DEE MAC JONAH JERROLD ROBT HANK SUNG RUPERT ROLLAND KENTON DAMION CHI ANTONE WALDO FREDRIC BRADLY QUINN KIP BURL WALKER TYREE JEFFEREY AHMED"
# names_list = namest.split()
# names = [name.title() for name in names_list]

In [84]:
karakter_list = []
keluarga_list = []
karakter_info = [[],[],[],[],[],[],[],[],[],[],[],[],[]]
n = 1000
for i in range(n):
    if i < int(n/2):
        umur = random.randint(15, 40)
    else:
        umur = random.randint(1, 99)
    
    kelamin = random.randint(0, 10)
    if kelamin < 5:
        sex = "Laki-laki"
        nama = random.choices(list_boy)[0]
        list_boy.remove(nama)
    else:
        sex = "Perempuan"
        nama = random.choices(list_girl)[0]
        list_girl.remove(nama)
    
    karakter_list.append(karakter(nama, umur, sex))
    karakter_info[0].append(karakter_list[i].name)
    karakter_info[1].append(karakter_list[i].age)
    karakter_info[2].append(karakter_list[i].power.atk)
    karakter_info[3].append(karakter_list[i].power.defend)
    karakter_info[4].append(karakter_list[i].power.health)
    karakter_info[5].append(karakter_list[i].power.spd)
    karakter_info[6].append(karakter_list[i].power.stamina)
    karakter_info[7].append(0)
    karakter_info[8].append(0)
    karakter_info[9].append(karakter_list[i].sex)
    karakter_info[10].append(karakter_list[i].sex_role)
    karakter_info[11].append(karakter_list[i].role)
    karakter_info[12].append(karakter_list[i].pasangan)

df = pd.DataFrame(karakter_info)
df = df.transpose()
df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose", "Kelamin", "Kategori", "Role", "Pasangan"], axis=1)
df

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
0,Carinne,16,11,6,763,7,112,0,0,Perempuan,Dewasa Muda,Penduduk,None
1,Loice,34,13,0,349,7,84,0,0,Laki-laki,Dewasa Tua,Penduduk,None
2,Draelyn,28,8,17,577,1,116,0,0,Laki-laki,Dewasa Muda,Penduduk,None
3,Elda,18,9,8,943,1,96,0,0,Laki-laki,Dewasa Muda,Penduduk,None
4,Shakiem,24,12,15,429,6,95,0,0,Laki-laki,Dewasa Muda,Penduduk,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Joshton,21,17,9,307,5,90,0,0,Laki-laki,Dewasa Muda,Penduduk,None
996,Jazalynn,9,20,15,823,0,22,0,0,Perempuan,Remaja,Penduduk,None
997,Gabriele,31,2,11,894,3,103,0,0,Laki-laki,Dewasa Tua,Penduduk,None
998,Davel,82,18,9,389,7,4,0,0,Laki-laki,Lansia,Penduduk,None
999,Willeta,54,6,16,375,0,18,0,0,Perempuan,Dewasa Tua,Penduduk,None

# **Set Roles**

In [85]:
df_temp = df.copy().drop(["Name", "win", "Lose", "Kelamin", "Kategori", "Role", "Pasangan"], axis = 1)
d = preprocessing.normalize(df_temp, axis=0)
df_normal = pd.DataFrame(d, columns=["Age","Atk","Def","HP","Spd","Stamina"])

# new_model = joblib.load('svm_first_model.sav')

# hasil = new_model.predict(df_normal)

# df["Role"] = hasil
# df["Role"] = df["Role"].replace({0:"Penduduk", 1:"Fighter"})
df["Role"] = "Fighter"
df

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
0,Carinne,16,11,6,763,7,112,0,0,Perempuan,Dewasa Muda,Fighter,None
1,Loice,34,13,0,349,7,84,0,0,Laki-laki,Dewasa Tua,Fighter,None
2,Draelyn,28,8,17,577,1,116,0,0,Laki-laki,Dewasa Muda,Fighter,None
3,Elda,18,9,8,943,1,96,0,0,Laki-laki,Dewasa Muda,Fighter,None
4,Shakiem,24,12,15,429,6,95,0,0,Laki-laki,Dewasa Muda,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Joshton,21,17,9,307,5,90,0,0,Laki-laki,Dewasa Muda,Fighter,None
996,Jazalynn,9,20,15,823,0,22,0,0,Perempuan,Remaja,Fighter,None
997,Gabriele,31,2,11,894,3,103,0,0,Laki-laki,Dewasa Tua,Fighter,None
998,Davel,82,18,9,389,7,4,0,0,Laki-laki,Lansia,Fighter,None
999,Willeta,54,6,16,375,0,18,0,0,Perempuan,Dewasa Tua,Fighter,None

In [86]:
df_temp = df.loc[df["Role"] == "Fighter"]
for idx in df_temp.index:
  karakter_list[idx].role = "Fighter"

# **Set King / Queen**

In [87]:
# 1000 orang
# 200x Duel

def GetBestPerson(df_duel_temp):

  df_duel = df_duel_temp.loc[df_duel_temp["Age"] >= 10]
  df_duel.reset_index()
  lis_temp = list(df_duel["Name"])
  karakter_list_duel = [char for char in karakter_list if char.name in lis_temp]
  # for char in karakter_list:
  #   if char.name in lis_temp:
  #     karakter_list_duel.append(char)

  for j in range(200):
    random.shuffle(karakter_list_duel)
    for i in range(0,len(karakter_list_duel),2):
      if(i+1 != len(karakter_list_duel)):
        win_name = duel(karakter_list_duel[i],karakter_list_duel[i+1])
        if karakter_list_duel[i].name == win_name:
          lose_name = karakter_list_duel[i+1].name
        else:
          lose_name = karakter_list_duel[i].name

        idx = df_duel[df_duel['Name']==win_name].index.values
        df_duel.at[idx[0],'win'] += 1

        idx = df_duel[df_duel['Name']==lose_name].index.values
        df_duel.at[idx[0],'Lose'] += 1
  
  return df_duel

In [88]:
df_hasil = GetBestPerson(df.copy())

In [89]:
df_hasil.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
698,Camyah,33,1,2,209,9,144,0,200,Perempuan,Dewasa Tua,Fighter,None
504,Giuseppi,20,1,0,249,7,135,0,200,Laki-laki,Dewasa Muda,Fighter,None
969,Mellisha,78,1,15,241,1,5,0,200,Perempuan,Lansia,Fighter,None
329,Mekisha,35,1,13,222,3,118,0,200,Perempuan,Dewasa Tua,Fighter,None
320,Aalayjah,34,1,10,389,2,92,1,199,Perempuan,Dewasa Tua,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,Davante,96,19,16,965,3,3,199,1,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,199,1,Laki-laki,Dewasa Tua,Fighter,None
187,Dalys,21,20,18,897,10,128,199,1,Perempuan,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,200,0,Laki-laki,Dewasa Muda,Fighter,None
120,Tyonna,26,19,16,973,2,81,200,0,Perempuan,Dewasa Muda,Fighter,None

In [90]:
df_king_1 = df_hasil.loc[df_hasil["win"] >= 100]
df_king_1.reset_index()
df_king_1

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
0,Carinne,16,11,6,763,7,112,138,62,Perempuan,Dewasa Muda,Fighter,None
3,Elda,18,9,8,943,1,96,151,49,Laki-laki,Dewasa Muda,Fighter,None
5,Juwairiyah,37,14,7,511,7,122,127,73,Perempuan,Dewasa Tua,Fighter,None
8,Lucilla,25,11,0,869,7,95,148,52,Perempuan,Dewasa Muda,Fighter,None
9,Shaqualia,34,15,1,865,2,118,169,31,Perempuan,Dewasa Tua,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,Zanyiah,42,19,12,461,9,129,158,42,Perempuan,Dewasa Tua,Fighter,None
993,Adebowale,35,19,13,916,5,130,199,1,Laki-laki,Dewasa Tua,Fighter,None
994,Selasi,60,14,19,641,2,8,153,47,Laki-laki,Lansia,Fighter,None
995,Joshton,21,17,9,307,5,90,104,96,Laki-laki,Dewasa Muda,Fighter,None
998,Davel,82,18,9,389,7,4,127,73,Laki-laki,Lansia,Fighter,None

In [91]:
df_king_1["win"] = 0
df_king_1["Lose"] = 0
df_king_1_duel = GetBestPerson(df_king_1.copy())

<ipython-input-91-78470f6dc6ec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_1["win"] = 0
<ipython-input-91-78470f6dc6ec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_1["Lose"] = 0

In [92]:
df_king_1_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
324,Jackalynn,25,18,9,275,6,90,3,197,Perempuan,Dewasa Muda,Fighter,None
406,Latrica,18,9,4,544,9,97,3,196,Perempuan,Dewasa Muda,Fighter,None
398,Giovanie,26,6,20,712,10,127,3,197,Laki-laki,Dewasa Muda,Fighter,None
136,Trence,39,7,11,750,4,86,4,196,Laki-laki,Dewasa Tua,Fighter,None
419,slamet nidun,27,6,16,755,9,98,5,195,Laki-laki,Dewasa Muda,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,Leshauna,60,18,13,962,5,20,197,3,Perempuan,Lansia,Fighter,None
841,Armone,38,19,20,911,3,92,197,3,Laki-laki,Dewasa Tua,Fighter,None
663,Taevin,46,20,10,1000,2,33,197,3,Laki-laki,Dewasa Tua,Fighter,None
602,Sabirin,69,20,9,951,8,7,197,3,Perempuan,Lansia,Fighter,None
486,Arlandus,27,19,16,938,3,91,198,2,Laki-laki,Dewasa Muda,Fighter,None

In [93]:
df_king_2 = df_king_1_duel.loc[df_king_1_duel["win"] >= 100]
df_king_2.reset_index()
df_king_2

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
9,Shaqualia,34,15,1,865,2,118,154,45,Perempuan,Dewasa Tua,Fighter,None
12,jurianto,36,11,4,996,0,108,126,73,Laki-laki,Dewasa Tua,Fighter,None
17,Kaylon,38,14,2,869,2,105,144,56,Perempuan,Dewasa Tua,Fighter,None
19,Heloise,19,15,12,836,10,109,156,44,Perempuan,Dewasa Muda,Fighter,None
20,Janyse,16,20,0,765,0,120,176,24,Perempuan,Dewasa Muda,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,Kerrilee,34,14,13,758,8,113,131,69,Perempuan,Dewasa Tua,Fighter,None
985,singgih adi putra,70,16,9,924,5,5,179,21,Laki-laki,Lansia,Fighter,None
990,Amilcar,88,20,17,592,5,5,157,43,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,191,8,Laki-laki,Dewasa Tua,Fighter,None
994,Selasi,60,14,19,641,2,8,106,91,Laki-laki,Lansia,Fighter,None

In [94]:
df_king_2["win"] = 0
df_king_2["Lose"] = 0
df_king_2_duel = GetBestPerson(df_king_2.copy())

<ipython-input-94-aeca91faa0bc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_2["win"] = 0
<ipython-input-94-aeca91faa0bc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_2["Lose"] = 0

In [95]:
df_king_2_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
45,Gaven,17,9,20,870,10,111,9,189,Laki-laki,Dewasa Muda,Fighter,None
903,Lorensa,39,12,10,753,4,79,13,186,Perempuan,Dewasa Tua,Fighter,None
972,Christiane,95,16,8,588,1,5,15,185,Laki-laki,Lansia,Fighter,None
653,Ashish,54,13,10,683,8,28,17,183,Laki-laki,Dewasa Tua,Fighter,None
200,Odalis,22,14,6,668,9,82,18,181,Perempuan,Dewasa Muda,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,Davante,96,19,16,965,3,3,193,7,Laki-laki,Lansia,Fighter,None
473,Michelle,27,19,7,999,1,105,194,6,Laki-laki,Dewasa Muda,Fighter,None
120,Tyonna,26,19,16,973,2,81,195,4,Perempuan,Dewasa Muda,Fighter,None
663,Taevin,46,20,10,1000,2,33,196,4,Laki-laki,Dewasa Tua,Fighter,None
602,Sabirin,69,20,9,951,8,7,196,4,Perempuan,Lansia,Fighter,None

In [96]:
df_king_3 = df_king_2_duel.loc[df_king_2_duel["win"] >= 100]
df_king_3.reset_index()
df_king_3

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
9,Shaqualia,34,15,1,865,2,118,104,96,Perempuan,Dewasa Tua,Fighter,None
19,Heloise,19,15,12,836,10,109,116,82,Perempuan,Dewasa Muda,Fighter,None
20,Janyse,16,20,0,765,0,120,135,63,Perempuan,Dewasa Muda,Fighter,None
53,Verdis,36,19,8,779,1,112,147,52,Laki-laki,Dewasa Tua,Fighter,None
54,Jordani,35,14,17,858,9,142,118,82,Laki-laki,Dewasa Tua,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,Kaliph,16,18,6,771,2,118,127,72,Laki-laki,Dewasa Muda,Fighter,None
967,Lezlee,59,19,3,804,7,13,142,56,Perempuan,Dewasa Tua,Fighter,None
985,singgih adi putra,70,16,9,924,5,5,156,44,Laki-laki,Lansia,Fighter,None
990,Amilcar,88,20,17,592,5,5,116,84,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,187,13,Laki-laki,Dewasa Tua,Fighter,None

In [97]:
df_king_3["win"] = 0
df_king_3["Lose"] = 0
df_king_3_duel = GetBestPerson(df_king_3.copy())

<ipython-input-97-015c73aa1de4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_3["win"] = 0
<ipython-input-97-015c73aa1de4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_3["Lose"] = 0

In [98]:
df_king_3_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
438,Adamina,21,14,1,916,5,83,16,184,Perempuan,Dewasa Muda,Fighter,None
618,Jonet,77,12,15,932,0,4,18,182,Perempuan,Lansia,Fighter,None
328,Ashtun,28,13,3,983,9,92,21,179,Laki-laki,Dewasa Muda,Fighter,None
489,Clement,20,12,15,959,1,94,24,176,Laki-laki,Dewasa Muda,Fighter,None
123,Demarques,32,16,9,761,10,85,26,174,Laki-laki,Dewasa Tua,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,Arlandus,27,19,16,938,3,91,188,12,Laki-laki,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,190,10,Laki-laki,Lansia,Fighter,None
187,Dalys,21,20,18,897,10,128,191,9,Perempuan,Dewasa Muda,Fighter,None
120,Tyonna,26,19,16,973,2,81,191,9,Perempuan,Dewasa Muda,Fighter,None
663,Taevin,46,20,10,1000,2,33,192,8,Laki-laki,Dewasa Tua,Fighter,None

In [99]:
df_king_4 = df_king_3_duel.loc[df_king_3_duel["win"] >= 100]
df_king_4.reset_index()
df_king_4

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
53,Verdis,36,19,8,779,1,112,107,93,Laki-laki,Dewasa Tua,Fighter,None
56,Malinah,21,18,12,822,10,137,120,80,Perempuan,Dewasa Muda,Fighter,None
75,Arec,15,18,8,909,2,114,147,53,Laki-laki,Dewasa Muda,Fighter,None
83,Cherrise,22,20,1,790,7,148,105,95,Perempuan,Dewasa Muda,Fighter,None
118,Dareld,35,19,16,867,6,75,169,31,Laki-laki,Dewasa Tua,Fighter,None
120,Tyonna,26,19,16,973,2,81,191,9,Perempuan,Dewasa Muda,Fighter,None
134,Shree,25,16,18,922,7,113,142,58,Laki-laki,Dewasa Muda,Fighter,None
187,Dalys,21,20,18,897,10,128,191,9,Perempuan,Dewasa Muda,Fighter,None
207,Racheal,31,19,14,730,7,105,108,92,Perempuan,Dewasa Tua,Fighter,None
231,Shenitra,30,19,5,934,0,93,155,45,Perempuan,Dewasa Tua,Fighter,None
269,Mahiya,32,20,16,792,10,134,148,52,Perempuan,Dewasa Tua,Fighter,None
284,Charle,19,17,17,936,4,149,152,48,Laki-laki,Dewasa Muda,Fighter,None
303,Shaunel,27,18,17,824,3,113,137,63,Perempuan,Dewasa Muda,Fighter,None
314,Leshelle,40,20,11,746,5,132,142,58,Perempuan,Dewasa Tua,Fighter,None
354,Heng,25,20,14,768,10,92,143,57,Laki-laki,Dewasa Muda,Fighter,None
379,Jamariae,39,19,2,998,2,111,171,29,Laki-laki,Dewasa Tua,Fighter,None
417,Abigaile,38,16,20,990,10,134,174,26,Perempuan,Dewasa Tua,Fighter,None
424,Atianna,28,20,6,843,2,123,150,50,Perempuan,Dewasa Muda,Fighter,None
464,Pearlann,22,15,17,933,10,131,123,77,Perempuan,Dewasa Muda,Fighter,None
473,Michelle,27,19,7,999,1,105,178,22,Laki-laki,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,188,12,Laki-laki,Dewasa Muda,Fighter,None
519,Caileen,68,19,14,831,4,7,146,54,Perempuan,Lansia,Fighter,None
541,Hollyn,48,20,11,802,0,34,148,52,Perempuan,Dewasa Tua,Fighter,None
551,Lucienna,83,20,0,880,10,5,142,58,Perempuan,Lansia,Fighter,None
553,Davante,96,19,16,965,3,3,190,10,Laki-laki,Lansia,Fighter,None
560,Othar,87,17,12,832,10,3,113,87,Laki-laki,Lansia,Fighter,None
577,Nakeira,91,19,6,908,7,2,154,46,Perempuan,Lansia,Fighter,None
599,Mervil,53,17,10,879,1,29,121,79,Laki-laki,Dewasa Tua,Fighter,None
602,Sabirin,69,20,9,951,8,7,185,15,Perempuan,Lansia,Fighter,None
611,Jakameron,51,17,0,950,2,13,102,98,Laki-laki,Dewasa Tua,Fighter,None
631,Leshauna,60,18,13,962,5,20,177,23,Perempuan,Lansia,Fighter,None
657,Kaliana,88,15,10,963,0,6,106,94,Perempuan,Lansia,Fighter,None
663,Taevin,46,20,10,1000,2,33,192,8,Laki-laki,Dewasa Tua,Fighter,None
697,Hildia,94,18,20,845,3,6,156,44,Perempuan,Lansia,Fighter,None
729,Marlania,19,17,11,900,4,86,131,69,Perempuan,Dewasa Muda,Fighter,None
742,Star,17,17,0,991,6,131,119,81,Laki-laki,Dewasa Muda,Fighter,None
745,Katie,72,19,19,748,4,11,119,81,Perempuan,Lansia,Fighter,None
750,Mackenzie,53,20,7,806,10,23,124,76,Laki-laki,Dewasa Tua,Fighter,None
787,Daviya,33,18,9,938,6,145,154,46,Perempuan,Dewasa Tua,Fighter,None
810,Senetta,30,20,8,791,10,88,120,80,Perempuan,Dewasa Tua,Fighter,None
831,Tenna,72,17,4,943,6,11,125,75,Perempuan,Lansia,Fighter,None
841,Armone,38,19,20,911,3,92,181,19,Laki-laki,Dewasa Tua,Fighter,None
851,Troi,19,16,20,926,3,101,136,64,Perempuan,Dewasa Muda,Fighter,None
866,Julissa,63,17,11,963,1,15,149,51,Laki-laki,Lansia,Fighter,None
871,Jameka,26,17,5,922,1,123,120,80,Perempuan,Dewasa Muda,Fighter,None
881,Rosenia,23,18,11,866,5,78,122,78,Perempuan,Dewasa Muda,Fighter,None
900,Helge,27,18,10,873,1,142,139,61,Laki-laki,Dewasa Muda,Fighter,None
904,Zandrea,44,15,18,922,9,63,103,97,Perempuan,Dewasa Tua,Fighter,None
915,Ariam,66,19,17,864,1,9,158,42,Laki-laki,Lansia,Fighter,None
917,Kindrick,94,18,11,986,3,4,178,22,Laki-laki,Lansia,Fighter,None
919,Aerial,89,17,7,964,9,7,144,56,Laki-laki,Lansia,Fighter,None
953,rohimin,34,17,9,970,8,75,149,51,Laki-laki,Dewasa Tua,Fighter,None
967,Lezlee,59,19,3,804,7,13,108,92,Perempuan,Dewasa Tua,Fighter,None
985,singgih adi putra,70,16,9,924,5,5,105,95,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,181,19,Laki-laki,Dewasa Tua,Fighter,None

In [100]:
idxs = df_king_4.index
print(len(idxs))
for i in idxs:
  karakter_list[i].role = "Prajurit"
  df['Role'][i] = "Prajurit"

55

In [101]:
df_king_4["win"] = 0
df_king_4["Lose"] = 0
df_king_4_duel = GetBestPerson(df_king_4.copy())

<ipython-input-101-caed9bcb471e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_4["win"] = 0
<ipython-input-101-caed9bcb471e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_4["Lose"] = 0

In [102]:
df_king_4_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
657,Kaliana,88,15,10,963,0,6,37,162,Perempuan,Lansia,Fighter,None
207,Racheal,31,19,14,730,7,105,37,157,Perempuan,Dewasa Tua,Fighter,None
560,Othar,87,17,12,832,10,3,38,162,Laki-laki,Lansia,Fighter,None
53,Verdis,36,19,8,779,1,112,39,157,Laki-laki,Dewasa Tua,Fighter,None
83,Cherrise,22,20,1,790,7,148,41,155,Perempuan,Dewasa Muda,Fighter,None
611,Jakameron,51,17,0,950,2,13,42,150,Laki-laki,Dewasa Tua,Fighter,None
967,Lezlee,59,19,3,804,7,13,48,151,Perempuan,Dewasa Tua,Fighter,None
56,Malinah,21,18,12,822,10,137,51,147,Perempuan,Dewasa Muda,Fighter,None
464,Pearlann,22,15,17,933,10,131,56,142,Perempuan,Dewasa Muda,Fighter,None
871,Jameka,26,17,5,922,1,123,61,135,Perempuan,Dewasa Muda,Fighter,None
904,Zandrea,44,15,18,922,9,63,62,135,Perempuan,Dewasa Tua,Fighter,None
831,Tenna,72,17,4,943,6,11,62,133,Perempuan,Lansia,Fighter,None
985,singgih adi putra,70,16,9,924,5,5,64,133,Laki-laki,Lansia,Fighter,None
303,Shaunel,27,18,17,824,3,113,67,128,Perempuan,Dewasa Muda,Fighter,None
314,Leshelle,40,20,11,746,5,132,67,128,Perempuan,Dewasa Tua,Fighter,None
599,Mervil,53,17,10,879,1,29,71,128,Laki-laki,Dewasa Tua,Fighter,None
742,Star,17,17,0,991,6,131,73,122,Laki-laki,Dewasa Muda,Fighter,None
745,Katie,72,19,19,748,4,11,75,124,Perempuan,Lansia,Fighter,None
900,Helge,27,18,10,873,1,142,78,116,Laki-laki,Dewasa Muda,Fighter,None
881,Rosenia,23,18,11,866,5,78,79,120,Perempuan,Dewasa Muda,Fighter,None
729,Marlania,19,17,11,900,4,86,80,118,Perempuan,Dewasa Muda,Fighter,None
810,Senetta,30,20,8,791,10,88,83,113,Perempuan,Dewasa Tua,Fighter,None
75,Arec,15,18,8,909,2,114,84,110,Laki-laki,Dewasa Muda,Fighter,None
919,Aerial,89,17,7,964,9,7,85,110,Laki-laki,Lansia,Fighter,None
851,Troi,19,16,20,926,3,101,88,108,Perempuan,Dewasa Muda,Fighter,None
750,Mackenzie,53,20,7,806,10,23,89,108,Laki-laki,Dewasa Tua,Fighter,None
424,Atianna,28,20,6,843,2,123,90,104,Perempuan,Dewasa Muda,Fighter,None
519,Caileen,68,19,14,831,4,7,96,102,Perempuan,Lansia,Fighter,None
953,rohimin,34,17,9,970,8,75,96,101,Laki-laki,Dewasa Tua,Fighter,None
354,Heng,25,20,14,768,10,92,97,101,Laki-laki,Dewasa Muda,Fighter,None
134,Shree,25,16,18,922,7,113,98,99,Laki-laki,Dewasa Muda,Fighter,None
541,Hollyn,48,20,11,802,0,34,100,98,Perempuan,Dewasa Tua,Fighter,None
551,Lucienna,83,20,0,880,10,5,101,95,Perempuan,Lansia,Fighter,None
866,Julissa,63,17,11,963,1,15,104,94,Laki-laki,Lansia,Fighter,None
697,Hildia,94,18,20,845,3,6,106,93,Perempuan,Lansia,Fighter,None
577,Nakeira,91,19,6,908,7,2,110,84,Perempuan,Lansia,Fighter,None
787,Daviya,33,18,9,938,6,145,111,87,Perempuan,Dewasa Tua,Fighter,None
284,Charle,19,17,17,936,4,149,113,79,Laki-laki,Dewasa Muda,Fighter,None
231,Shenitra,30,19,5,934,0,93,119,80,Perempuan,Dewasa Tua,Fighter,None
269,Mahiya,32,20,16,792,10,134,124,74,Perempuan,Dewasa Tua,Fighter,None
379,Jamariae,39,19,2,998,2,111,129,65,Laki-laki,Dewasa Tua,Fighter,None
915,Ariam,66,19,17,864,1,9,134,62,Laki-laki,Lansia,Fighter,None
417,Abigaile,38,16,20,990,10,134,134,61,Perempuan,Dewasa Tua,Fighter,None
118,Dareld,35,19,16,867,6,75,139,57,Laki-laki,Dewasa Tua,Fighter,None
631,Leshauna,60,18,13,962,5,20,140,58,Perempuan,Lansia,Fighter,None
917,Kindrick,94,18,11,986,3,4,141,53,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,151,48,Laki-laki,Dewasa Tua,Fighter,None
473,Michelle,27,19,7,999,1,105,155,41,Laki-laki,Dewasa Muda,Fighter,None
602,Sabirin,69,20,9,951,8,7,156,39,Perempuan,Lansia,Fighter,None
486,Arlandus,27,19,16,938,3,91,158,36,Laki-laki,Dewasa Muda,Fighter,None
841,Armone,38,19,20,911,3,92,163,35,Laki-laki,Dewasa Tua,Fighter,None
187,Dalys,21,20,18,897,10,128,167,30,Perempuan,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,167,26,Laki-laki,Lansia,Fighter,None
120,Tyonna,26,19,16,973,2,81,170,26,Perempuan,Dewasa Muda,Fighter,None
663,Taevin,46,20,10,1000,2,33,174,20,Laki-laki,Dewasa Tua,Fighter,None

In [103]:
df_king_5 = df_king_4_duel.loc[df_king_4_duel["win"] >= 100]
df_king_5.reset_index()
df_king_5

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
118,Dareld,35,19,16,867,6,75,139,57,Laki-laki,Dewasa Tua,Fighter,None
120,Tyonna,26,19,16,973,2,81,170,26,Perempuan,Dewasa Muda,Fighter,None
187,Dalys,21,20,18,897,10,128,167,30,Perempuan,Dewasa Muda,Fighter,None
231,Shenitra,30,19,5,934,0,93,119,80,Perempuan,Dewasa Tua,Fighter,None
269,Mahiya,32,20,16,792,10,134,124,74,Perempuan,Dewasa Tua,Fighter,None
284,Charle,19,17,17,936,4,149,113,79,Laki-laki,Dewasa Muda,Fighter,None
379,Jamariae,39,19,2,998,2,111,129,65,Laki-laki,Dewasa Tua,Fighter,None
417,Abigaile,38,16,20,990,10,134,134,61,Perempuan,Dewasa Tua,Fighter,None
473,Michelle,27,19,7,999,1,105,155,41,Laki-laki,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,158,36,Laki-laki,Dewasa Muda,Fighter,None
541,Hollyn,48,20,11,802,0,34,100,98,Perempuan,Dewasa Tua,Fighter,None
551,Lucienna,83,20,0,880,10,5,101,95,Perempuan,Lansia,Fighter,None
553,Davante,96,19,16,965,3,3,167,26,Laki-laki,Lansia,Fighter,None
577,Nakeira,91,19,6,908,7,2,110,84,Perempuan,Lansia,Fighter,None
602,Sabirin,69,20,9,951,8,7,156,39,Perempuan,Lansia,Fighter,None
631,Leshauna,60,18,13,962,5,20,140,58,Perempuan,Lansia,Fighter,None
663,Taevin,46,20,10,1000,2,33,174,20,Laki-laki,Dewasa Tua,Fighter,None
697,Hildia,94,18,20,845,3,6,106,93,Perempuan,Lansia,Fighter,None
787,Daviya,33,18,9,938,6,145,111,87,Perempuan,Dewasa Tua,Fighter,None
841,Armone,38,19,20,911,3,92,163,35,Laki-laki,Dewasa Tua,Fighter,None
866,Julissa,63,17,11,963,1,15,104,94,Laki-laki,Lansia,Fighter,None
915,Ariam,66,19,17,864,1,9,134,62,Laki-laki,Lansia,Fighter,None
917,Kindrick,94,18,11,986,3,4,141,53,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,151,48,Laki-laki,Dewasa Tua,Fighter,None

In [104]:
df_king_5["win"] = 0
df_king_5["Lose"] = 0
df_king_5_duel = GetBestPerson(df_king_5.copy())

<ipython-input-104-ff85a5617b6e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_5["win"] = 0
<ipython-input-104-ff85a5617b6e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_5["Lose"] = 0

In [105]:
df_king_5_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
551,Lucienna,83,20,0,880,10,5,45,155,Perempuan,Lansia,Fighter,None
541,Hollyn,48,20,11,802,0,34,49,151,Perempuan,Dewasa Tua,Fighter,None
284,Charle,19,17,17,936,4,149,52,148,Laki-laki,Dewasa Muda,Fighter,None
787,Daviya,33,18,9,938,6,145,60,140,Perempuan,Dewasa Tua,Fighter,None
577,Nakeira,91,19,6,908,7,2,60,140,Perempuan,Lansia,Fighter,None
231,Shenitra,30,19,5,934,0,93,68,132,Perempuan,Dewasa Tua,Fighter,None
697,Hildia,94,18,20,845,3,6,69,131,Perempuan,Lansia,Fighter,None
866,Julissa,63,17,11,963,1,15,73,127,Laki-laki,Lansia,Fighter,None
269,Mahiya,32,20,16,792,10,134,76,124,Perempuan,Dewasa Tua,Fighter,None
118,Dareld,35,19,16,867,6,75,84,116,Laki-laki,Dewasa Tua,Fighter,None
417,Abigaile,38,16,20,990,10,134,85,115,Perempuan,Dewasa Tua,Fighter,None
915,Ariam,66,19,17,864,1,9,88,112,Laki-laki,Lansia,Fighter,None
379,Jamariae,39,19,2,998,2,111,97,103,Laki-laki,Dewasa Tua,Fighter,None
631,Leshauna,60,18,13,962,5,20,104,96,Perempuan,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,104,96,Laki-laki,Dewasa Tua,Fighter,None
917,Kindrick,94,18,11,986,3,4,116,84,Laki-laki,Lansia,Fighter,None
473,Michelle,27,19,7,999,1,105,126,74,Laki-laki,Dewasa Muda,Fighter,None
841,Armone,38,19,20,911,3,92,139,61,Laki-laki,Dewasa Tua,Fighter,None
602,Sabirin,69,20,9,951,8,7,141,59,Perempuan,Lansia,Fighter,None
187,Dalys,21,20,18,897,10,128,146,54,Perempuan,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,147,53,Laki-laki,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,149,51,Laki-laki,Lansia,Fighter,None
120,Tyonna,26,19,16,973,2,81,157,43,Perempuan,Dewasa Muda,Fighter,None
663,Taevin,46,20,10,1000,2,33,165,35,Laki-laki,Dewasa Tua,Fighter,None

In [106]:
df_king_6 = df_king_5_duel.loc[df_king_5_duel["win"] >= 100]
df_king_6.reset_index()
df_king_6

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
120,Tyonna,26,19,16,973,2,81,157,43,Perempuan,Dewasa Muda,Fighter,None
187,Dalys,21,20,18,897,10,128,146,54,Perempuan,Dewasa Muda,Fighter,None
473,Michelle,27,19,7,999,1,105,126,74,Laki-laki,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,147,53,Laki-laki,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,149,51,Laki-laki,Lansia,Fighter,None
602,Sabirin,69,20,9,951,8,7,141,59,Perempuan,Lansia,Fighter,None
631,Leshauna,60,18,13,962,5,20,104,96,Perempuan,Lansia,Fighter,None
663,Taevin,46,20,10,1000,2,33,165,35,Laki-laki,Dewasa Tua,Fighter,None
841,Armone,38,19,20,911,3,92,139,61,Laki-laki,Dewasa Tua,Fighter,None
917,Kindrick,94,18,11,986,3,4,116,84,Laki-laki,Lansia,Fighter,None
993,Adebowale,35,19,13,916,5,130,104,96,Laki-laki,Dewasa Tua,Fighter,None

In [107]:
df_king_6["win"] = 0
df_king_6["Lose"] = 0
df_king_6_duel = GetBestPerson(df_king_6.copy())

<ipython-input-107-7138a0f738d3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_6["win"] = 0
<ipython-input-107-7138a0f738d3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_6["Lose"] = 0

In [108]:
df_king_6_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
993,Adebowale,35,19,13,916,5,130,56,123,Laki-laki,Dewasa Tua,Fighter,None
631,Leshauna,60,18,13,962,5,20,57,122,Perempuan,Lansia,Fighter,None
917,Kindrick,94,18,11,986,3,4,59,119,Laki-laki,Lansia,Fighter,None
473,Michelle,27,19,7,999,1,105,81,100,Laki-laki,Dewasa Muda,Fighter,None
486,Arlandus,27,19,16,938,3,91,92,92,Laki-laki,Dewasa Muda,Fighter,None
602,Sabirin,69,20,9,951,8,7,99,85,Perempuan,Lansia,Fighter,None
841,Armone,38,19,20,911,3,92,100,81,Laki-laki,Dewasa Tua,Fighter,None
120,Tyonna,26,19,16,973,2,81,109,75,Perempuan,Dewasa Muda,Fighter,None
187,Dalys,21,20,18,897,10,128,114,70,Perempuan,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,115,71,Laki-laki,Lansia,Fighter,None
663,Taevin,46,20,10,1000,2,33,118,62,Laki-laki,Dewasa Tua,Fighter,None

In [109]:
df_king_7 = df_king_6_duel.loc[df_king_6_duel["win"] >= 100]
df_king_7.reset_index()
df_king_7

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
120,Tyonna,26,19,16,973,2,81,109,75,Perempuan,Dewasa Muda,Fighter,None
187,Dalys,21,20,18,897,10,128,114,70,Perempuan,Dewasa Muda,Fighter,None
553,Davante,96,19,16,965,3,3,115,71,Laki-laki,Lansia,Fighter,None
663,Taevin,46,20,10,1000,2,33,118,62,Laki-laki,Dewasa Tua,Fighter,None
841,Armone,38,19,20,911,3,92,100,81,Laki-laki,Dewasa Tua,Fighter,None

In [110]:
idxs = df_king_7.index
print(len(idxs))
for i in idxs:
  karakter_list[i].role = "Panglima"
  df['Role'][i] = "Panglima"

5

In [111]:
df_king_7["win"] = 0
df_king_7["Lose"] = 0
df_king_7_duel = GetBestPerson(df_king_7.copy())

<ipython-input-111-c329a365292a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_7["win"] = 0
<ipython-input-111-c329a365292a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_7["Lose"] = 0

In [112]:
df_king_7_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
187,Dalys,21,20,18,897,10,128,66,86,Perempuan,Dewasa Muda,Fighter,None
841,Armone,38,19,20,911,3,92,73,92,Laki-laki,Dewasa Tua,Fighter,None
553,Davante,96,19,16,965,3,3,75,88,Laki-laki,Lansia,Fighter,None
120,Tyonna,26,19,16,973,2,81,78,83,Perempuan,Dewasa Muda,Fighter,None
663,Taevin,46,20,10,1000,2,33,108,51,Laki-laki,Dewasa Tua,Fighter,None

In [113]:
if df_king_7_duel.loc[df_king_7_duel["win"] >= 100].shape[0] > 0:
  df_king_8 = df_king_7_duel.loc[df_king_7_duel["win"] >= 100]
else:
  df_king_8 = df_king_7_duel.copy()
  
df_king_8.reset_index()
df_king_8

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
663,Taevin,46,20,10,1000,2,33,108,51,Laki-laki,Dewasa Tua,Fighter,None

In [114]:
df_king_8["win"] = 0
df_king_8["Lose"] = 0
df_king_8_duel = GetBestPerson(df_king_8.copy())

<ipython-input-114-bb505b4364a2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_8["win"] = 0
<ipython-input-114-bb505b4364a2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_king_8["Lose"] = 0

In [115]:
df_king_8_duel.sort_values("win")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
663,Taevin,46,20,10,1000,2,33,0,0,Laki-laki,Dewasa Tua,Fighter,None

In [116]:
df_king_9 = df_king_8_duel.loc[df_king_8_duel["win"] == max(df_king_8_duel["win"])]
df_king_9.reset_index()
if df_king_9.shape[0] > 1:
  df_king_9 = pd.DataFrame(df_king_9.iloc[0])
  df_king_9 = df_king_9.transpose()
df_king_9

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
663,Taevin,46,20,10,1000,2,33,0,0,Laki-laki,Dewasa Tua,Fighter,None

In [117]:
idx = df_king_9.index
if karakter_list[idx[0]].sex == "Perempuan":
  karakter_list[idx[0]].role = "Queen"
  df['Role'][idx] = "Queen"
else :
  karakter_list[idx[0]].role = "King"
  df['Role'][idx] = "King"

# **Tes Harian**

In [118]:
df

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
0,Carinne,16,11,6,763,7,112,0,0,Perempuan,Dewasa Muda,Fighter,None
1,Loice,34,13,0,349,7,84,0,0,Laki-laki,Dewasa Tua,Fighter,None
2,Draelyn,28,8,17,577,1,116,0,0,Laki-laki,Dewasa Muda,Fighter,None
3,Elda,18,9,8,943,1,96,0,0,Laki-laki,Dewasa Muda,Fighter,None
4,Shakiem,24,12,15,429,6,95,0,0,Laki-laki,Dewasa Muda,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Joshton,21,17,9,307,5,90,0,0,Laki-laki,Dewasa Muda,Fighter,None
996,Jazalynn,9,20,15,823,0,22,0,0,Perempuan,Remaja,Fighter,None
997,Gabriele,31,2,11,894,3,103,0,0,Laki-laki,Dewasa Tua,Fighter,None
998,Davel,82,18,9,389,7,4,0,0,Laki-laki,Lansia,Fighter,None
999,Willeta,54,6,16,375,0,18,0,0,Perempuan,Dewasa Tua,Fighter,None

In [119]:
df.sort_values("Role")

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Kelamin,Kategori,Role,Pasangan
0,Carinne,16,11,6,763,7,112,0,0,Perempuan,Dewasa Muda,Fighter,None
646,Matthewryan,12,6,19,806,9,24,0,0,Laki-laki,Remaja,Fighter,None
647,Jamillette,86,4,19,355,9,7,0,0,Perempuan,Lansia,Fighter,None
648,Graceanna,8,12,4,273,5,27,0,0,Perempuan,Remaja,Fighter,None
649,Zyiana,3,12,12,355,0,7,0,0,Perempuan,Anak-anak,Fighter,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,Jameka,26,17,5,922,1,123,0,0,Perempuan,Dewasa Muda,Prajurit,None
118,Dareld,35,19,16,867,6,75,0,0,Laki-laki,Dewasa Tua,Prajurit,None
631,Leshauna,60,18,13,962,5,20,0,0,Perempuan,Lansia,Prajurit,None
424,Atianna,28,20,6,843,2,123,0,0,Perempuan,Dewasa Muda,Prajurit,None
379,Jamariae,39,19,2,998,2,111,0,0,Laki-laki,Dewasa Tua,Prajurit,None

In [120]:
karakter_list

[<__main__.karakter at 0x2c0712ba610>,
 <__main__.karakter at 0x2c071796b50>,
 <__main__.karakter at 0x2c071796cd0>,
 <__main__.karakter at 0x2c071796ca0>,
 <__main__.karakter at 0x2c0717968e0>,
 <__main__.karakter at 0x2c071796df0>,
 <__main__.karakter at 0x2c071796e80>,
 <__main__.karakter at 0x2c071796d60>,
 <__main__.karakter at 0x2c071767790>,
 <__main__.karakter at 0x2c071796c40>,
 <__main__.karakter at 0x2c071796d00>,
 <__main__.karakter at 0x2c071796f10>,
 <__main__.karakter at 0x2c071796ee0>,
 <__main__.karakter at 0x2c071796e20>,
 <__main__.karakter at 0x2c071796fa0>,
 <__main__.karakter at 0x2c071796ac0>,
 <__main__.karakter at 0x2c071796d30>,
 <__main__.karakter at 0x2c071796bb0>,
 <__main__.karakter at 0x2c0717af310>,
 <__main__.karakter at 0x2c0717af3d0>,
 <__main__.karakter at 0x2c0717af460>,
 <__main__.karakter at 0x2c0717af4c0>,
 <__main__.karakter at 0x2c0717679a0>,
 <__main__.karakter at 0x2c0717af4f0>,
 <__main__.karakter at 0x2c0717af070>,
 <__main__.karakter at 0x2c0717af580>,
 <__main__.karakter at 0x2c071767c40>,
 <__main__.karakter at 0x2c0717af520>,
 <__main__.karakter at 0x2c0717af400>,
 <__main__.karakter at 0x2c0717af670>,
 <__main__.karakter at 0x2c0717af640>,
 <__main__.karakter at 0x2c0717af1f0>,
 <__main__.karakter at 0x2c0717afac0>,
 <__main__.karakter at 0x2c0717afa00>,
 <__main__.karakter at 0x2c0717afb50>,
 <__main__.karakter at 0x2c0717af7f0>,
 <__main__.karakter at 0x2c0717af040>,
 <__main__.karakter at 0x2c0717af5e0>,
 <__main__.karakter at 0x2c0717afcd0>,
 <__main__.karakter at 0x2c0717afca0>,
 <__main__.karakter at 0x2c0717afc40>,
 <__main__.karakter at 0x2c0717afe20>,
 <__main__.karakter at 0x2c0717afdf0>,
 <__main__.karakter at 0x2c0717afbb0>,
 <__main__.karakter at 0x2c0717aff40>,
 <__main__.karakter at 0x2c0717afe80>,
 <__main__.karakter at 0x2c0717afbe0>,
 <__main__.karakter at 0x2c0717afeb0>,
 <__main__.karakter at 0x2c0717affd0>,
 <__main__.karakter at 0x2c071767bb0>,
 <__main__.karakter at 0x2c0717af550>,
 <__main__.karakter at 0x2c071767ca0>,
 <__main__.karakter at 0x2c06daaca60>,
 <__main__.karakter at 0x2c0717af250>,
 <__main__.karakter at 0x2c071767250>,
 <__main__.karakter at 0x2c071767df0>,
 <__main__.karakter at 0x2c0717af130>,
 <__main__.karakter at 0x2c07176ef10>,
 <__main__.karakter at 0x2c070e59e80>,
 <__main__.karakter at 0x2c071784610>,
 <__main__.karakter at 0x2c070e59ee0>,
 <__main__.karakter at 0x2c071784400>,
 <__main__.karakter at 0x2c070e59e50>,
 <__main__.karakter at 0x2c071750220>,
 <__main__.karakter at 0x2c0717508b0>,
 <__main__.karakter at 0x2c071750e20>,
 <__main__.karakter at 0x2c071750cd0>,
 <__main__.karakter at 0x2c0717506d0>,
 <__main__.karakter at 0x2c0717daca0>,
 <__main__.karakter at 0x2c0717daa90>,
 <__main__.karakter at 0x2c0717dadf0>,
 <__main__.karakter at 0x2c0717dab50>,
 <__main__.karakter at 0x2c0717dad30>,
 <__main__.karakter at 0x2c0717daf10>,
 <__main__.karakter at 0x2c0717dae50>,
 <__main__.karakter at 0x2c0717dafa0>,
 <__main__.karakter at 0x2c0717dad60>,
 <__main__.karakter at 0x2c0717dad90>,
 <__main__.karakter at 0x2c0717daf70>,
 <__main__.karakter at 0x2c0717dab20>,
 <__main__.karakter at 0x2c0717dac40>,
 <__main__.karakter at 0x2c0717dac70>,
 <__main__.karakter at 0x2c071791130>,
 <__main__.karakter at 0x2c071791a30>,
 <__main__.karakter at 0x2c071791a00>,
 <__main__.karakter at 0x2c0717911c0>,
 <__main__.karakter at 0x2c071791b50>,
 <__main__.karakter at 0x2c071791a90>,
 <__main__.karakter at 0x2c071791c10>,
 <__main__.karakter at 0x2c071791ac0>,
 <__main__.karakter at 0x2c071791250>,
 <__main__.karakter at 0x2c071791d30>,
 <__main__.karakter at 0x2c071791cd0>,
 <__main__.karakter at 0x2c071791df0>,
 <__main__.karakter at 0x2c071791e50>,
 <__main__.karakter at 0x2c071791190>,
 <__main__.karakter at 0x2c071791be0>,
 <__main__.karakter at 0x2c071791dc0>,
 <__main__.karakter at 0x2c071791fa0>,
 <__main__.karakter at 0x2c071791ee0>,
 <__main__.karakter at 0x2c071791f10>,
 <__main__.karakter at 0x2c071791f70>,
 <__main__.karakter at 0x2c0717910d0>,
 <__main__.karakter at 0x2c071791070>,
 <__main__.karakter at 0x2c071791040>,
 <__main__.karakter at 0x2c0717f01f0>,
 <__main__.karakter at 0x2c0717f0070>,
 <__main__.karakter at 0x2c0717f02b0>,
 <__main__.karakter at 0x2c0717f0130>,
 <__main__.karakter at 0x2c0717f0190>,
 <__main__.karakter at 0x2c0717f0250>,
 <__main__.karakter at 0x2c071113af0>,
 <__main__.karakter at 0x2c0712b7fd0>,
 <__main__.karakter at 0x2c071113ac0>,
 <__main__.karakter at 0x2c0717f00d0>,
 <__main__.karakter at 0x2c071113df0>,
 <__main__.karakter at 0x2c0717c5250>,
 <__main__.karakter at 0x2c0717c51f0>,
 <__main__.karakter at 0x2c0717c51c0>,
 <__main__.karakter at 0x2c0717c5430>,
 <__main__.karakter at 0x2c0717c54c0>,
 <__main__.karakter at 0x2c0717c53a0>,
 <__main__.karakter at 0x2c0717c5550>,
 <__main__.karakter at 0x2c0717c5460>,
 <__main__.karakter at 0x2c0717c5310>,
 <__main__.karakter at 0x2c0717c5e20>,
 <__main__.karakter at 0x2c0717c50a0>,
 <__main__.karakter at 0x2c0717c50d0>,
 <__main__.karakter at 0x2c0717c5130>,
 <__main__.karakter at 0x2c0717f24f0>,
 <__main__.karakter at 0x2c0717f25e0>,
 <__main__.karakter at 0x2c0717f29d0>,
 <__main__.karakter at 0x2c0717f2a60>,
 <__main__.karakter at 0x2c07170e5b0>,
 <__main__.karakter at 0x2c0717f2be0>,
 <__main__.karakter at 0x2c07170e400>,
 <__main__.karakter at 0x2c07170e5e0>,
 <__main__.karakter at 0x2c071782070>,
 <__main__.karakter at 0x2c071782e50>,
 <__main__.karakter at 0x2c071782b80>,
 <__main__.karakter at 0x2c071782a30>,
 <__main__.karakter at 0x2c071782a00>,
 <__main__.karakter at 0x2c071782370>,
 <__main__.karakter at 0x2c071782d90>,
 <__main__.karakter at 0x2c071782f70>,
 <__main__.karakter at 0x2c071782af0>,
 <__main__.karakter at 0x2c071782fd0>,
 <__main__.karakter at 0x2c071782940>,
 <__main__.karakter at 0x2c0717828e0>,
 <__main__.karakter at 0x2c071782bb0>,
 <__main__.karakter at 0x2c071782c70>,
 <__main__.karakter at 0x2c07181e370>,
 <__main__.karakter at 0x2c07181e280>,
 <__main__.karakter at 0x2c07181e2e0>,
 <__main__.karakter at 0x2c07181e3d0>,
 <__main__.karakter at 0x2c07181e430>,
 <__main__.karakter at 0x2c07181e190>,
 <__main__.karakter at 0x2c07181e100>,
 <__main__.karakter at 0x2c07181e490>,
 <__main__.karakter at 0x2c07181e610>,
 <__main__.karakter at 0x2c07181e670>,
 <__main__.karakter at 0x2c07181e580>,
 <__main__.karakter at 0x2c07181e820>,
 <__main__.karakter at 0x2c07181e2b0>,
 <__main__.karakter at 0x2c07181e850>,
 <__main__.karakter at 0x2c07181e8b0>,
 <__main__.karakter at 0x2c07181e310>,
 <__main__.karakter at 0x2c07181e910>,
 <__main__.karakter at 0x2c07181ebe0>,
 <__main__.karakter at 0x2c07181ed60>,
 <__main__.karakter at 0x2c07181e760>,
 <__main__.karakter at 0x2c07181edf0>,
 <__main__.karakter at 0x2c07181ee50>,
 <__main__.karakter at 0x2c07181e4f0>,
 <__main__.karakter at 0x2c07181ebb0>,
 <__main__.karakter at 0x2c07181ef10>,
 <__main__.karakter at 0x2c07181ef40>,
 <__main__.karakter at 0x2c07181efa0>,
 <__main__.karakter at 0x2c07181eb50>,
 <__main__.karakter at 0x2c07181e7f0>,
 <__main__.karakter at 0x2c07181e520>,
 <__main__.karakter at 0x2c07181e070>,
 <__main__.karakter at 0x2c07181e160>,
 <__main__.karakter at 0x2c07181e8e0>,
 <__main__.karakter at 0x2c07251e190>,
 <__main__.karakter at 0x2c07251e1f0>,
 <__main__.karakter at 0x2c07251e250>,
 <__main__.karakter at 0x2c07251e2b0>,
 <__main__.karakter at 0x2c07251e310>,
 <__main__.karakter at 0x2c07251e370>,
 <__main__.karakter at 0x2c07251e3d0>,
 <__main__.karakter at 0x2c07251e430>,
 <__main__.karakter at 0x2c07251e490>,
 <__main__.karakter at 0x2c07251e4f0>,
 <__main__.karakter at 0x2c07251e550>,
 <__main__.karakter at 0x2c07251e5b0>,
 <__main__.karakter at 0x2c07251e610>,
 <__main__.karakter at 0x2c07251e670>,
 <__main__.karakter at 0x2c07251e6d0>,
 <__main__.karakter at 0x2c07251e730>,
 <__main__.karakter at 0x2c07251e790>,
 <__main__.karakter at 0x2c07251e7f0>,
 <__main__.karakter at 0x2c07251e850>,
 <__main__.karakter at 0x2c07251e8b0>,
 <__main__.karakter at 0x2c07251e910>,
 <__main__.karakter at 0x2c07251e970>,
 <__main__.karakter at 0x2c07251e9d0>,
 <__main__.karakter at 0x2c07251ea30>,
 <__main__.karakter at 0x2c07251ea90>,
 <__main__.karakter at 0x2c07251eaf0>,
 <__main__.karakter at 0x2c07251eb50>,
 <__main__.karakter at 0x2c07251ebb0>,
 <__main__.karakter at 0x2c07251ec10>,
 <__main__.karakter at 0x2c07251ec70>,
 <__main__.karakter at 0x2c07251ecd0>,
 <__main__.karakter at 0x2c07251ed30>,
 <__main__.karakter at 0x2c07251ed90>,
 <__main__.karakter at 0x2c07251edf0>,
 <__main__.karakter at 0x2c07251ee50>,
 <__main__.karakter at 0x2c07251eeb0>,
 <__main__.karakter at 0x2c07251ef10>,
 <__main__.karakter at 0x2c07251ef70>,
 <__main__.karakter at 0x2c07251efd0>,
 <__main__.karakter at 0x2c07251e130>,
 <__main__.karakter at 0x2c07251e0d0>,
 <__main__.karakter at 0x2c07251e070>,
 <__main__.karakter at 0x2c072523190>,
 <__main__.karakter at 0x2c0725231f0>,
 <__main__.karakter at 0x2c072523250>,
 <__main__.karakter at 0x2c0725232b0>,
 <__main__.karakter at 0x2c072523310>,
 <__main__.karakter at 0x2c072523370>,
 <__main__.karakter at 0x2c0725233d0>,
 <__main__.karakter at 0x2c072523430>,
 <__main__.karakter at 0x2c072523490>,
 <__main__.karakter at 0x2c0725234f0>,
 <__main__.karakter at 0x2c072523550>,
 <__main__.karakter at 0x2c0725235b0>,
 <__main__.karakter at 0x2c072523610>,
 <__main__.karakter at 0x2c072523640>,
 <__main__.karakter at 0x2c072523700>,
 <__main__.karakter at 0x2c072523760>,
 <__main__.karakter at 0x2c0725237c0>,
 <__main__.karakter at 0x2c072523820>,
 <__main__.karakter at 0x2c072523880>,
 <__main__.karakter at 0x2c0725238e0>,
 <__main__.karakter at 0x2c072523940>,
 <__main__.karakter at 0x2c0725239a0>,
 <__main__.karakter at 0x2c072523a00>,
 <__main__.karakter at 0x2c072523a60>,
 <__main__.karakter at 0x2c072523ac0>,
 <__main__.karakter at 0x2c072523b20>,
 <__main__.karakter at 0x2c072523b80>,
 <__main__.karakter at 0x2c072523be0>,
 <__main__.karakter at 0x2c072523c40>,
 <__main__.karakter at 0x2c072523ca0>,
 <__main__.karakter at 0x2c072523d00>,
 <__main__.karakter at 0x2c072523d60>,
 <__main__.karakter at 0x2c072523dc0>,
 <__main__.karakter at 0x2c072523e20>,
 <__main__.karakter at 0x2c072523e80>,
 <__main__.karakter at 0x2c072523ee0>,
 <__main__.karakter at 0x2c072523f40>,
 <__main__.karakter at 0x2c072523fa0>,
 <__main__.karakter at 0x2c072523fd0>,
 <__main__.karakter at 0x2c072523100>,
 <__main__.karakter at 0x2c0725230d0>,
 <__main__.karakter at 0x2c072523040>,
 <__main__.karakter at 0x2c0725291c0>,
 <__main__.karakter at 0x2c072529220>,
 <__main__.karakter at 0x2c072529280>,
 <__main__.karakter at 0x2c0725292e0>,
 <__main__.karakter at 0x2c072529340>,
 <__main__.karakter at 0x2c0725293a0>,
 <__main__.karakter at 0x2c072529400>,
 <__main__.karakter at 0x2c072529460>,
 <__main__.karakter at 0x2c0725294c0>,
 <__main__.karakter at 0x2c072529520>,
 <__main__.karakter at 0x2c072529580>,
 <__main__.karakter at 0x2c0725295e0>,
 <__main__.karakter at 0x2c072529640>,
 <__main__.karakter at 0x2c0725296a0>,
 <__main__.karakter at 0x2c072529700>,
 <__main__.karakter at 0x2c072529760>,
 <__main__.karakter at 0x2c0725297c0>,
 <__main__.karakter at 0x2c072529820>,
 <__main__.karakter at 0x2c072529880>,
 <__main__.karakter at 0x2c0725298e0>,
 <__main__.karakter at 0x2c072529940>,
 <__main__.karakter at 0x2c0725299a0>,
 <__main__.karakter at 0x2c072529a00>,
 <__main__.karakter at 0x2c072529a60>,
 <__main__.karakter at 0x2c072529ac0>,
 <__main__.karakter at 0x2c072529b20>,
 <__main__.karakter at 0x2c072529b80>,
 <__main__.karakter at 0x2c072529be0>,
 <__main__.karakter at 0x2c072529c40>,
 <__main__.karakter at 0x2c072529ca0>,
 <__main__.karakter at 0x2c072529d00>,
 <__main__.karakter at 0x2c072529d60>,
 <__main__.karakter at 0x2c072529dc0>,
 <__main__.karakter at 0x2c072529e20>,
 <__main__.karakter at 0x2c072529e80>,
 <__main__.karakter at 0x2c072529ee0>,
 <__main__.karakter at 0x2c072529f40>,
 <__main__.karakter at 0x2c072529fa0>,
 <__main__.karakter at 0x2c072529fd0>,
 <__main__.karakter at 0x2c072529130>,
 <__main__.karakter at 0x2c0725290d0>,
 <__main__.karakter at 0x2c072529070>,
 <__main__.karakter at 0x2c07252f1c0>,
 <__main__.karakter at 0x2c07252f220>,
 <__main__.karakter at 0x2c07252f280>,
 <__main__.karakter at 0x2c07252f2e0>,
 <__main__.karakter at 0x2c07252f340>,
 <__main__.karakter at 0x2c07252f3a0>,
 <__main__.karakter at 0x2c07252f400>,
 <__main__.karakter at 0x2c07252f460>,
 <__main__.karakter at 0x2c07252f4c0>,
 <__main__.karakter at 0x2c07252f520>,
 <__main__.karakter at 0x2c07252f580>,
 <__main__.karakter at 0x2c07252f5e0>,
 <__main__.karakter at 0x2c07252f640>,
 <__main__.karakter at 0x2c07252f6a0>,
 <__main__.karakter at 0x2c07252f700>,
 <__main__.karakter at 0x2c07252f760>,
 <__main__.karakter at 0x2c07252f7c0>,
 <__main__.karakter at 0x2c07252f820>,
 <__main__.karakter at 0x2c07252f880>,
 <__main__.karakter at 0x2c07252f8e0>,
 <__main__.karakter at 0x2c07252f940>,
 <__main__.karakter at 0x2c07252f9a0>,
 <__main__.karakter at 0x2c07252fa00>,
 <__main__.karakter at 0x2c07252fa60>,
 <__main__.karakter at 0x2c07252fac0>,
 <__main__.karakter at 0x2c07252fb20>,
 <__main__.karakter at 0x2c07252fb80>,
 <__main__.karakter at 0x2c07252fbe0>,
 <__main__.karakter at 0x2c07252fc40>,
 <__main__.karakter at 0x2c07252fca0>,
 <__main__.karakter at 0x2c07252fd00>,
 <__main__.karakter at 0x2c07252fd60>,
 <__main__.karakter at 0x2c07252fdc0>,
 <__main__.karakter at 0x2c07252fe20>,
 <__main__.karakter at 0x2c07252fe80>,
 <__main__.karakter at 0x2c07252fee0>,
 <__main__.karakter at 0x2c07252ff40>,
 <__main__.karakter at 0x2c07252ffa0>,
 <__main__.karakter at 0x2c07252ffd0>,
 <__main__.karakter at 0x2c07252f130>,
 <__main__.karakter at 0x2c07252f0d0>,
 <__main__.karakter at 0x2c07252f070>,
 <__main__.karakter at 0x2c0725331c0>,
 <__main__.karakter at 0x2c072533220>,
 <__main__.karakter at 0x2c072533280>,
 <__main__.karakter at 0x2c0725332e0>,
 <__main__.karakter at 0x2c072533340>,
 <__main__.karakter at 0x2c0725333a0>,
 <__main__.karakter at 0x2c072533400>,
 <__main__.karakter at 0x2c072533460>,
 <__main__.karakter at 0x2c0725334c0>,
 <__main__.karakter at 0x2c072533520>,
 <__main__.karakter at 0x2c072533580>,
 <__main__.karakter at 0x2c0725335e0>,
 <__main__.karakter at 0x2c072533640>,
 <__main__.karakter at 0x2c0725336a0>,
 <__main__.karakter at 0x2c072533700>,
 <__main__.karakter at 0x2c072533760>,
 <__main__.karakter at 0x2c0725337c0>,
 <__main__.karakter at 0x2c072533820>,
 <__main__.karakter at 0x2c072533880>,
 <__main__.karakter at 0x2c0725338e0>,
 <__main__.karakter at 0x2c072533940>,
 <__main__.karakter at 0x2c0725339a0>,
 <__main__.karakter at 0x2c072533a00>,
 <__main__.karakter at 0x2c072533a60>,
 <__main__.karakter at 0x2c072533ac0>,
 <__main__.karakter at 0x2c072533b20>,
 <__main__.karakter at 0x2c072533b80>,
 <__main__.karakter at 0x2c072533be0>,
 <__main__.karakter at 0x2c072533c40>,
 <__main__.karakter at 0x2c072533ca0>,
 <__main__.karakter at 0x2c072533d00>,
 <__main__.karakter at 0x2c072533d60>,
 <__main__.karakter at 0x2c072533dc0>,
 <__main__.karakter at 0x2c072533e20>,
 <__main__.karakter at 0x2c072533e80>,
 <__main__.karakter at 0x2c072533ee0>,
 <__main__.karakter at 0x2c072533f40>,
 <__main__.karakter at 0x2c072533fa0>,
 <__main__.karakter at 0x2c072533fd0>,
 <__main__.karakter at 0x2c072533130>,
 <__main__.karakter at 0x2c0725330d0>,
 <__main__.karakter at 0x2c072533070>,
 <__main__.karakter at 0x2c0725391c0>,
 <__main__.karakter at 0x2c072539220>,
 <__main__.karakter at 0x2c072539280>,
 <__main__.karakter at 0x2c0725392e0>,
 <__main__.karakter at 0x2c072539340>,
 <__main__.karakter at 0x2c0725393a0>,
 <__main__.karakter at 0x2c072539400>,
 <__main__.karakter at 0x2c072539460>,
 <__main__.karakter at 0x2c0725394c0>,
 <__main__.karakter at 0x2c072539520>,
 <__main__.karakter at 0x2c072539580>,
 <__main__.karakter at 0x2c0725395e0>,
 <__main__.karakter at 0x2c072539640>,
 <__main__.karakter at 0x2c0725396a0>,
 <__main__.karakter at 0x2c072539700>,
 <__main__.karakter at 0x2c072539760>,
 <__main__.karakter at 0x2c0725397c0>,
 <__main__.karakter at 0x2c072539820>,
 <__main__.karakter at 0x2c072539880>,
 <__main__.karakter at 0x2c0725398e0>,
 <__main__.karakter at 0x2c072539940>,
 <__main__.karakter at 0x2c0725399a0>,
 <__main__.karakter at 0x2c072539a00>,
 <__main__.karakter at 0x2c072539a60>,
 <__main__.karakter at 0x2c072539ac0>,
 <__main__.karakter at 0x2c072539b20>,
 <__main__.karakter at 0x2c072539b80>,
 <__main__.karakter at 0x2c072539be0>,
 <__main__.karakter at 0x2c072539c40>,
 <__main__.karakter at 0x2c072539ca0>,
 <__main__.karakter at 0x2c072539d00>,
 <__main__.karakter at 0x2c072539d60>,
 <__main__.karakter at 0x2c072539dc0>,
 <__main__.karakter at 0x2c072539e20>,
 <__main__.karakter at 0x2c072539e80>,
 <__main__.karakter at 0x2c072539ee0>,
 <__main__.karakter at 0x2c072539f40>,
 <__main__.karakter at 0x2c072539fa0>,
 <__main__.karakter at 0x2c072539fd0>,
 <__main__.karakter at 0x2c072539130>,
 <__main__.karakter at 0x2c0725390d0>,
 <__main__.karakter at 0x2c072539070>,
 <__main__.karakter at 0x2c07253e1c0>,
 <__main__.karakter at 0x2c07253e220>,
 <__main__.karakter at 0x2c07253e280>,
 <__main__.karakter at 0x2c07253e2e0>,
 <__main__.karakter at 0x2c07253e340>,
 <__main__.karakter at 0x2c07253e3a0>,
 <__main__.karakter at 0x2c07253e400>,
 <__main__.karakter at 0x2c07253e460>,
 <__main__.karakter at 0x2c07253e4c0>,
 <__main__.karakter at 0x2c07253e520>,
 <__main__.karakter at 0x2c07253e580>,
 <__main__.karakter at 0x2c07253e5e0>,
 <__main__.karakter at 0x2c07253e640>,
 <__main__.karakter at 0x2c07253e6a0>,
 <__main__.karakter at 0x2c07253e700>,
 <__main__.karakter at 0x2c07253e760>,
 <__main__.karakter at 0x2c07253e7c0>,
 <__main__.karakter at 0x2c07253e820>,
 <__main__.karakter at 0x2c07253e880>,
 <__main__.karakter at 0x2c07253e8e0>,
 <__main__.karakter at 0x2c07253e940>,
 <__main__.karakter at 0x2c07253e9a0>,
 <__main__.karakter at 0x2c07253ea00>,
 <__main__.karakter at 0x2c07253ea60>,
 <__main__.karakter at 0x2c07253eac0>,
 <__main__.karakter at 0x2c07253eb20>,
 <__main__.karakter at 0x2c07253eb80>,
 <__main__.karakter at 0x2c07253ebe0>,
 <__main__.karakter at 0x2c07253ec40>,
 <__main__.karakter at 0x2c07253eca0>,
 <__main__.karakter at 0x2c07253ed00>,
 <__main__.karakter at 0x2c07253ed60>,
 <__main__.karakter at 0x2c07253edc0>,
 <__main__.karakter at 0x2c07253ee20>,
 <__main__.karakter at 0x2c07253ee80>,
 <__main__.karakter at 0x2c07253eee0>,
 <__main__.karakter at 0x2c07253ef40>,
 <__main__.karakter at 0x2c07253efa0>,
 <__main__.karakter at 0x2c07253efd0>,
 <__main__.karakter at 0x2c07253e130>,
 <__main__.karakter at 0x2c07253e0d0>,
 <__main__.karakter at 0x2c07253e070>,
 <__main__.karakter at 0x2c0725431c0>,
 <__main__.karakter at 0x2c072543220>,
 <__main__.karakter at 0x2c072543280>,
 <__main__.karakter at 0x2c0725432e0>,
 <__main__.karakter at 0x2c072543340>,
 <__main__.karakter at 0x2c0725433a0>,
 <__main__.karakter at 0x2c072543400>,
 <__main__.karakter at 0x2c072543460>,
 <__main__.karakter at 0x2c0725434c0>,
 <__main__.karakter at 0x2c072543520>,
 <__main__.karakter at 0x2c072543580>,
 <__main__.karakter at 0x2c0725435e0>,
 <__main__.karakter at 0x2c072543640>,
 <__main__.karakter at 0x2c0725436a0>,
 <__main__.karakter at 0x2c072543700>,
 <__main__.karakter at 0x2c072543760>,
 <__main__.karakter at 0x2c0725437c0>,
 <__main__.karakter at 0x2c072543820>,
 <__main__.karakter at 0x2c072543880>,
 <__main__.karakter at 0x2c0725438e0>,
 <__main__.karakter at 0x2c072543940>,
 <__main__.karakter at 0x2c0725439a0>,
 <__main__.karakter at 0x2c072543a00>,
 <__main__.karakter at 0x2c072543a60>,
 <__main__.karakter at 0x2c072543ac0>,
 <__main__.karakter at 0x2c072543b20>,
 <__main__.karakter at 0x2c072543b80>,
 <__main__.karakter at 0x2c072543be0>,
 <__main__.karakter at 0x2c072543c40>,
 <__main__.karakter at 0x2c072543ca0>,
 <__main__.karakter at 0x2c072543d00>,
 <__main__.karakter at 0x2c072543d60>,
 <__main__.karakter at 0x2c072543dc0>,
 <__main__.karakter at 0x2c072543e20>,

In [179]:
day = 1
month = 1
year = 1

while(year < 10):
  if month > 12:
    year += 1
    ageUpList(karakter_list)
    karakter_list, keluarga_list, list_girl, list_boy = updateKeluarga(karakter_list, keluarga_list, list_girl, list_boy)
    month = 1
    day = 1
  if day > 30:
    print(str(day)+"/"+str(month)+"/"+str(year))
    dead(karakter_list)
    gaji(karakter_list)
    cariPasangan(karakter_list)
    month += 1
    day = 1
  karakter_list = daily(karakter_list)
  day += 1
  

n = len(karakter_list)
karakter_info = [[],[],[],[],[],[],[],[],[],[],[],[]]

for i in range(n):
  karakter_info[0].append(karakter_list[i].name)
  karakter_info[1].append(karakter_list[i].age)
  karakter_info[2].append(karakter_list[i].power.atk)
  karakter_info[3].append(karakter_list[i].power.defend)
  karakter_info[4].append(karakter_list[i].power.health)
  karakter_info[5].append(karakter_list[i].power.spd)
  karakter_info[6].append(karakter_list[i].power.stamina)
  karakter_info[7].append(karakter_list[i].coin)
  karakter_info[8].append(karakter_list[i].sex)
  karakter_info[9].append(karakter_list[i].sex_role)
  karakter_info[10].append(karakter_list[i].role)
  karakter_info[11].append(karakter_list[i].pasangan)

df_tes = pd.DataFrame(karakter_info)
df_tes = df_tes.transpose()
df_tes = df_tes.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "Coin", "Kelamin", "Kategori", "Role", "Pasangan"], axis=1)
df_tes

31/1/1
Jamen Mati!!!
31/2/1
31/3/1
31/4/1
31/5/1
31/6/1
31/7/1
31/8/1
31/9/1
31/10/1
31/11/1
31/12/1
Dearis Mati!!!
31/1/2
31/2/2
31/3/2
31/4/2
31/5/2
31/6/2
Aleona Mati!!!
31/7/2
31/8/2
31/9/2
31/10/2
31/11/2
31/12/2
31/1/3
31/2/3
31/3/3
Janesa Mati!!!
31/4/3
31/5/3
31/6/3
31/7/3
Moses Mati!!!
Lore Mati!!!
31/8/3
Derien Mati!!!
31/9/3
31/10/3
31/11/3
Paulet Mati Random
31/12/3
31/1/4
Arkadiusz Mati!!!
Shakari Mati!!!
31/2/4
31/3/4
31/4/4
31/5/4
Jonet Mati!!!
31/6/4
31/7/4
31/8/4
31/9/4
Yazayra Mati!!!
31/10/4
31/11/4
31/12/4
31/1/5
31/2/5
31/3/5
31/4/5
Mellisha Mati!!!
31/5/5
Livee Mati!!!
31/6/5
31/7/5
31/8/5
31/9/5
31/10/5
31/11/5
31/12/5
31/1/6
31/2/6
31/3/6
Quinshawn Mati!!!
31/4/6
Aliciana Mati!!!
31/5/6
31/6/6
31/7/6
Vinnia Mati!!!
31/8/6
31/9/6
Leemarie Mati!!!
31/10/6
Anaisabel Mati!!!
31/11/6
31/12/6
Melodee Mati!!!
Joslyne Mati!!!
31/1/7
Symphanie Mati!!!
Mayson Mati!!!
31/2/7
Roanin Mati!!!
31/3/7
31/4/7
31/5/7
31/6/7
Taccara Mati!!!
31/7/7
31/8/7
Antonita Mati!!!
31/9/7
Jaquelle Mati!!!
31/10/7
31/11/7
Quaterrius Mati!!!
31/12/7
31/1/8
31/2/8
Sariana Mati!!!
31/3/8
Elvena Mati!!!
Evertte Mati!!!
31/4/8
31/5/8
31/6/8
31/7/8
Archer Mati!!!
31/8/8
Jaime Mati!!!
31/9/8
31/10/8
Seriyah Mati!!!
31/11/8
Danieljr Mati!!!
31/12/8
31/1/9
31/2/9
31/3/9
31/4/9
31/5/9
Kotina Mati!!!
Dasa Mati!!!
31/6/9
Jiyan Mati!!!
Anterria Mati!!!
31/7/9
Jorgen Mati!!!
31/8/9
Addysyn Mati!!!
31/9/9
31/10/9
31/11/9
31/12/9

,Name,Age,Atk,Def,HP,Spd,Stamina,Coin,Kelamin,Kategori,Role,Pasangan
0,Carinne,45,1359,1273,7079,620,723,16962,Perempuan,Dewasa Tua,Fighter,None
1,Loice,63,1269,1237,6264,626,666,132417,Laki-laki,Lansia,Fighter,Ericca
2,Draelyn,57,1291,1276,6730,523,660,33331,Laki-laki,Dewasa Tua,Fighter,Ramina
3,Elda,47,1302,1279,6896,517,648,93336,Laki-laki,Dewasa Tua,Fighter,Anamary
4,Shakiem,53,1341,1234,6532,563,683,-18414,Laki-laki,Dewasa Tua,Fighter,Persaeus
...,...,...,...,...,...,...,...,...,...,...,...,...
2133,Monike,1,16,5,211,8,1,750,Perempuan,Anak-anak,Penduduk,None
2134,Latiya,1,19,2,518,7,1,750,Perempuan,Anak-anak,Penduduk,None
2135,Zaylaa,1,20,2,570,6,1,750,Perempuan,Anak-anak,Penduduk,None
2136,Carianne,1,15,20,518,3,1,750,Perempuan,Anak-anak,Penduduk,None
2137,Sheryll,1,17,18,904,0,1,750,Perempuan,Anak-anak,Penduduk,None

In [180]:
df_tes.loc[df_tes["Coin"] < 0].sort_values("Coin")

,Name,Age,Atk,Def,HP,Spd,Stamina,Coin,Kelamin,Kategori,Role,Pasangan
730,Octavio,40,1234,1281,6711,583,581,-145743,Perempuan,Dewasa Tua,Fighter,Audre
1113,Shayde,21,578,596,3198,276,253,-106890,Laki-laki,Dewasa Muda,Penduduk,None
584,Tomoya,37,1193,1142,6240,483,531,-105067,Laki-laki,Dewasa Tua,Fighter,Cabria
1073,Abriel,22,639,631,3600,307,278,-102142,Perempuan,Dewasa Muda,Penduduk,None
1028,Kaliyah,23,615,639,3848,287,254,-101465,Laki-laki,Dewasa Muda,Penduduk,Kaylor
...,...,...,...,...,...,...,...,...,...,...,...,...
1619,Taide,12,169,165,977,78,52,-936,Perempuan,Remaja,Penduduk,None
296,Oralia,58,1335,1306,6736,570,693,-377,Laki-laki,Dewasa Tua,Fighter,Leksi
1559,Nafeesha,12,138,153,1366,81,42,-374,Perempuan,Remaja,Penduduk,None
1555,Katrica,12,161,163,1720,74,41,-270,Perempuan,Remaja,Penduduk,None
521,Remick,84,1288,1267,6391,470,563,-198,Laki-laki,Lansia,Fighter,Maygen

In [181]:
df_tes.loc[df_tes["Coin"] > 0].sort_values("Coin")

,Name,Age,Atk,Def,HP,Spd,Stamina,Coin,Kelamin,Kategori,Role,Pasangan
1575,Yulemni,12,155,121,1644,72,45,70,Perempuan,Remaja,Penduduk,None
803,Linken,41,1299,1284,6664,537,555,170,Laki-laki,Dewasa Tua,Fighter,Lauda
553,Syann,58,1300,1190,6748,532,658,295,Perempuan,Dewasa Tua,Fighter,None
483,Leksi,67,1309,1284,6427,611,699,302,Perempuan,Lansia,Fighter,Oralia
1583,Nyelah,12,126,147,1475,70,36,429,Perempuan,Remaja,Penduduk,None
...,...,...,...,...,...,...,...,...,...,...,...,...
671,Star,46,1291,1284,7045,571,701,277982,Laki-laki,Dewasa Tua,Prajurit,None
187,Dalys,50,1262,1300,6857,545,672,373415,Perempuan,Dewasa Tua,Panglima,Wahaj
120,Tyonna,55,1303,1335,6989,539,608,408787,Perempuan,Dewasa Tua,Panglima,Derrald
743,Armone,67,1292,1294,6660,524,676,417707,Laki-laki,Lansia,Panglima,Heloise
615,Taevin,75,1273,1253,6760,538,578,944674,Laki-laki,Lansia,King,Karmel

In [182]:
df_tes.sort_values("Age")

,Name,Age,Atk,Def,HP,Spd,Stamina,Coin,Kelamin,Kategori,Role,Pasangan
2137,Sheryll,1,17,18,904,0,1,750,Perempuan,Anak-anak,Penduduk,None
2106,Abdurahman,1,19,12,790,6,1,750,Laki-laki,Anak-anak,Penduduk,None
2105,Paten,1,9,16,664,6,1,750,Laki-laki,Anak-anak,Penduduk,None
2104,Phill,1,10,2,265,9,1,750,Laki-laki,Anak-anak,Penduduk,None
2103,Soon,1,18,0,457,8,1,750,Perempuan,Anak-anak,Penduduk,None
...,...,...,...,...,...,...,...,...,...,...,...,...
674,Katie,101,1340,1280,6542,549,572,137560,Perempuan,Lansia,Prajurit,sapudin
797,Demaurie,101,1314,1317,6273,578,595,36512,Laki-laki,Lansia,Fighter,Elfreda
741,Laverl,101,1395,1264,6893,536,541,50144,Laki-laki,Lansia,Fighter,Jaquandra
632,Quaran,102,1269,1250,6684,518,621,74558,Laki-laki,Lansia,Fighter,Juliahnna
713,Wahaj,102,1291,1252,6134,560,566,66094,Laki-laki,Lansia,Fighter,Dalys

In [183]:
count = 0
for i in keluarga_list:
    if len(i.anak) > 3:
        print(i.anak)
        count += 1
print(count)

[<__main__.karakter object at 0x000002C0738350D0>, <__main__.karakter object at 0x000002C0738EE100>, <__main__.karakter object at 0x000002C0738FCE20>, <__main__.karakter object at 0x000002C073943D00>]
[<__main__.karakter object at 0x000002C0725D0D90>, <__main__.karakter object at 0x000002C0737FEF70>, <__main__.karakter object at 0x000002C073864190>, <__main__.karakter object at 0x000002C0739042E0>, <__main__.karakter object at 0x000002C0717C5AC0>]
[<__main__.karakter object at 0x000002C0725D0E20>, <__main__.karakter object at 0x000002C07385BA90>, <__main__.karakter object at 0x000002C0717DA0A0>, <__main__.karakter object at 0x000002C073835370>, <__main__.karakter object at 0x000002C072573640>, <__main__.karakter object at 0x000002C0739C3F70>]
[<__main__.karakter object at 0x000002C073809EB0>, <__main__.karakter object at 0x000002C0738643A0>, <__main__.karakter object at 0x000002C0738CC850>, <__main__.karakter object at 0x000002C073835CD0>, <__main__.karakter object at 0x000002C0739047C0>]
[<__main__.karakter object at 0x000002C0737FEFD0>, <__main__.karakter object at 0x000002C070E597F0>, <__main__.karakter object at 0x000002C073835A60>, <__main__.karakter object at 0x000002C072549640>, <__main__.karakter object at 0x000002C073868550>]
[<__main__.karakter object at 0x000002C073809E50>, <__main__.karakter object at 0x000002C0737FEBB0>, <__main__.karakter object at 0x000002C07385BAC0>, <__main__.karakter object at 0x000002C070E59C10>]
[<__main__.karakter object at 0x000002C0725D0E80>, <__main__.karakter object at 0x000002C0717DA610>, <__main__.karakter object at 0x000002C073864400>, <__main__.karakter object at 0x000002C0717DA580>, <__main__.karakter object at 0x000002C07390D100>, <__main__.karakter object at 0x000002C0739C3730>]
[<__main__.karakter object at 0x000002C0725D7AC0>, <__main__.karakter object at 0x000002C0738CC970>, <__main__.karakter object at 0x000002C07390D340>, <__main__.karakter object at 0x000002C0739A3E50>]
[<__main__.karakter object at 0x000002C0725D0EE0>, <__main__.karakter object at 0x000002C0725D7B80>, <__main__.karakter object at 0x000002C0717507C0>, <__main__.karakter object at 0x000002C0738CC9D0>, <__main__.karakter object at 0x000002C0738F64F0>, <__main__.karakter object at 0x000002C072579730>, <__main__.karakter object at 0x000002C07176EB80>, <__main__.karakter object at 0x000002C073A30BB0>]
[<__main__.karakter object at 0x000002C0725D7BE0>, <__main__.karakter object at 0x000002C07385BB20>, <__main__.karakter object at 0x000002C071750250>, <__main__.karakter object at 0x000002C0738F6490>, <__main__.karakter object at 0x000002C073904820>, <__main__.karakter object at 0x000002C07390D6A0>, <__main__.karakter object at 0x000002C0738683D0>]
[<__main__.karakter object at 0x000002C0738097F0>, <__main__.karakter object at 0x000002C073835D30>, <__main__.karakter object at 0x000002C0738EED90>, <__main__.karakter object at 0x000002C07390D700>]
[<__main__.karakter object at 0x000002C07385BBE0>, <__main__.karakter object at 0x000002C071750040>, <__main__.karakter object at 0x000002C0738F6430>, <__main__.karakter object at 0x000002C072573E20>]
[<__main__.karakter object at 0x000002C0737FEE50>, <__main__.karakter object at 0x000002C07385BC40>, <__main__.karakter object at 0x000002C073864460>, <__main__.karakter object at 0x000002C072553820>, <__main__.karakter object at 0x000002C0738F3220>, <__main__.karakter object at 0x000002C0738FCA00>]
[<__main__.karakter object at 0x000002C07385BCA0>, <__main__.karakter object at 0x000002C0725A61C0>, <__main__.karakter object at 0x000002C073835DC0>, <__main__.karakter object at 0x000002C072549C70>, <__main__.karakter object at 0x000002C073A196A0>]
[<__main__.karakter object at 0x000002C07385BD00>, <__main__.karakter object at 0x000002C0738F60A0>, <__main__.karakter object at 0x000002C073912C70>, <__main__.karakter object at 0x000002C0739A3F40>]
[<__main__.karakter object at 0x000002C0737FEBE0>, <__main__.karakter object at 0x000002C073835EE0>, <__main__.karakter object at 0x000002C073814BE0>, <__main__.karakter object at 0x000002C0738F6100>, <__main__.karakter object at 0x000002C0712C4940>]
[<__main__.karakter object at 0x000002C0717503A0>, <__main__.karakter object at 0x000002C072569070>, <__main__.karakter object at 0x000002C073835F40>, <__main__.karakter object at 0x000002C073A19850>, <__main__.karakter object at 0x000002C072563280>]
[<__main__.karakter object at 0x000002C0738F3280>, <__main__.karakter object at 0x000002C073868250>, <__main__.karakter object at 0x000002C0739C3280>, <__main__.karakter object at 0x000002C073A28070>]
[<__main__.karakter object at 0x000002C07385BD60>, <__main__.karakter object at 0x000002C0738644C0>, <__main__.karakter object at 0x000002C073814C40>, <__main__.karakter object at 0x000002C0738FCEE0>, <__main__.karakter object at 0x000002C073904880>, <__main__.karakter object at 0x000002C0725638E0>, <__main__.karakter object at 0x000002C073A309A0>]
[<__main__.karakter object at 0x000002C0725D7C40>, <__main__.karakter object at 0x000002C0737FC190>, <__main__.karakter object at 0x000002C0738F32E0>, <__main__.karakter object at 0x000002C07390D7C0>]
[<__main__.karakter object at 0x000002C0737FC1F0>, <__main__.karakter object at 0x000002C0738F3340>, <__main__.karakter object at 0x000002C073943040>, <__main__.karakter object at 0x000002C0739C3C10>]
[<__main__.karakter object at 0x000002C0725A4EB0>, <__main__.karakter object at 0x000002C073814D60>, <__main__.karakter object at 0x000002C0738F33A0>, <__main__.karakter object at 0x000002C0738FCF40>, <__main__.karakter object at 0x000002C073868D30>]
[<__main__.karakter object at 0x000002C0725D7CA0>, <__main__.karakter object at 0x000002C07385BE80>, <__main__.karakter object at 0x000002C073864520>, <__main__.karakter object at 0x000002C071750AF0>, <__main__.karakter object at 0x000002C0725A4BB0>, <__main__.karakter object at 0x000002C073814DC0>, <__main__.karakter object at 0x000002C0738F3400>, <__main__.karakter object at 0x000002C0738F6880>, <__main__.karakter object at 0x000002C0739048E0>, <__main__.karakter object at 0x000002C07390D820>, <__main__.karakter object at 0x000002C0739A3E80>]
[<__main__.karakter object at 0x000002C0725D7D00>, <__main__.karakter object at 0x000002C0737FC250>, <__main__.karakter object at 0x000002C073A19B50>, <__main__.karakter object at 0x000002C073A30B50>]
[<__main__.karakter object at 0x000002C0725D0730>, <__main__.karakter object at 0x000002C0738FCE50>, <__main__.karakter object at 0x000002C073868130>, <__main__.karakter object at 0x000002C073A19BB0>, <__main__.karakter object at 0x000002C073A28A90>]
[<__main__.karakter object at 0x000002C073864580>, <__main__.karakter object at 0x000002C0738F3460>, <__main__.karakter object at 0x000002C0738FCD90>, <__main__.karakter object at 0x000002C07390D880>, <__main__.karakter object at 0x000002C0739A3070>, <__main__.karakter object at 0x000002C07178B040>]
[<__main__.karakter object at 0x000002C0737FC2B0>, <__main__.karakter object at 0x000002C0738355B0>, <__main__.karakter object at 0x000002C073814AF0>, <__main__.karakter object at 0x000002C073904940>, <__main__.karakter object at 0x000002C0739A3F10>]
[<__main__.karakter object at 0x000002C0725D7D60>, <__main__.karakter object at 0x000002C073809DC0>, <__main__.karakter object at 0x000002C0738F3520>, <__main__.karakter object at 0x000002C0739001C0>]
[<__main__.karakter object at 0x000002C0738F6940>, <__main__.karakter object at 0x000002C0739A10A0>, <__main__.karakter object at 0x000002C073868520>, <__main__.karakter object at 0x000002C073946D30>]
[<__main__.karakter object at 0x000002C07385BEE0>, <__main__.karakter object at 0x000002C0738646A0>, <__main__.karakter object at 0x000002C0738F69A0>, <__main__.karakter object at 0x000002C073900220>]
[<__main__.karakter object at 0x000002C0725D7DC0>, <__main__.karakter object at 0x000002C073864700>, <__main__.karakter object at 0x000002C0717502B0>, <__main__.karakter object at 0x000002C0738F3580>, <__main__.karakter object at 0x000002C0739A1220>]
[<__main__.karakter object at 0x000002C073864760>, <__main__.karakter object at 0x000002C073900280>, <__main__.karakter object at 0x000002C0739A1280>, <__main__.karakter object at 0x000002C073A3E130>]
[<__main__.karakter object at 0x000002C07390D940>, <__main__.karakter object at 0x000002C0739C3FA0>, <__main__.karakter object at 0x000002C073A38700>, <__main__.karakter object at 0x000002C073A30D30>]
[<__main__.karakter object at 0x000002C0737FC310>, <__main__.karakter object at 0x000002C0738F35E0>, <__main__.karakter object at 0x000002C0739049A0>, <__main__.karakter object at 0x000002C0739A12E0>]
[<__main__.karakter object at 0x000002C07385BF40>, <__main__.karakter object at 0x000002C0738CC100>, <__main__.karakter object at 0x000002C0738F3640>, <__main__.karakter object at 0x000002C0738F6A00>, <__main__.karakter object at 0x000002C0739002E0>, <__main__.karakter object at 0x000002C07390DA00>]
[<__main__.karakter object at 0x000002C0725D7E80>, <__main__.karakter object at 0x000002C073864820>, <__main__.karakter object at 0x000002C073904A60>, <__main__.karakter object at 0x000002C0739437F0>, <__main__.karakter object at 0x000002C073A30DF0>]
[<__main__.karakter object at 0x000002C07385BFA0>, <__main__.karakter object at 0x000002C0725A4AF0>, <__main__.karakter object at 0x000002C0738F36A0>, <__main__.karakter object at 0x000002C07390DA60>, <__main__.karakter object at 0x000002C0739A1340>, <__main__.karakter object at 0x000002C0739AA1C0>]
[<__main__.karakter object at 0x000002C0725D7EE0>, <__main__.karakter object at 0x000002C073814F40>, <__main__.karakter object at 0x000002C073900340>, <__main__.karakter object at 0x000002C07390DAC0>, <__main__.karakter object at 0x000002C0739AA220>, <__main__.karakter object at 0x000002C073A28370>]
[<__main__.karakter object at 0x000002C0725D7F40>, <__main__.karakter object at 0x000002C073904AC0>, <__main__.karakter object at 0x000002C073868A90>, <__main__.karakter object at 0x000002C073A43220>]
[<__main__.karakter object at 0x000002C07385BFD0>, <__main__.karakter object at 0x000002C0725A4850>, <__main__.karakter object at 0x000002C0738CCA60>, <__main__.karakter object at 0x000002C073912040>, <__main__.karakter object at 0x000002C0739A1400>, <__main__.karakter object at 0x000002C073A3A070>]
[<__main__.karakter object at 0x000002C073809700>, <__main__.karakter object at 0x000002C0737FC4F0>, <__main__.karakter object at 0x000002C073814C10>, <__main__.karakter object at 0x000002C0739003A0>, <__main__.karakter object at 0x000002C073912130>]
[<__main__.karakter object at 0x000002C071782160>, <__main__.karakter object at 0x000002C0725A4DC0>, <__main__.karakter object at 0x000002C0739AA280>, <__main__.karakter object at 0x000002C073A43280>]
[<__main__.karakter object at 0x000002C071750F40>, <__main__.karakter object at 0x000002C073835F10>, <__main__.karakter object at 0x000002C0738F37C0>, <__main__.karakter object at 0x000002C0739AA2E0>, <__main__.karakter object at 0x000002C073A30EB0>, <__main__.karakter object at 0x000002C073A3A040>]
[<__main__.karakter object at 0x000002C07385BA30>, <__main__.karakter object at 0x000002C071113B20>, <__main__.karakter object at 0x000002C073835280>, <__main__.karakter object at 0x000002C0739171C0>, <__main__.karakter object at 0x000002C073A28430>]
[<__main__.karakter object at 0x000002C0738F3820>, <__main__.karakter object at 0x000002C0738F6AC0>, <__main__.karakter object at 0x000002C073904B80>, <__main__.karakter object at 0x000002C0739AA340>, <__main__.karakter object at 0x000002C0739438B0>]
[<__main__.karakter object at 0x000002C07385B7C0>, <__main__.karakter object at 0x000002C0738648E0>, <__main__.karakter object at 0x000002C073917220>, <__main__.karakter object at 0x000002C0739A1460>, <__main__.karakter object at 0x000002C0739C31F0>]
[<__main__.karakter object at 0x000002C0737FE190>, <__main__.karakter object at 0x000002C07385E280>, <__main__.karakter object at 0x000002C0725A4070>, <__main__.karakter object at 0x000002C073835640>, <__main__.karakter object at 0x000002C0739A14C0>]
[<__main__.karakter object at 0x000002C0737FE1F0>, <__main__.karakter object at 0x000002C0737FC610>, <__main__.karakter object at 0x000002C0739A1520>, <__main__.karakter object at 0x000002C073946CA0>]
[<__main__.karakter object at 0x000002C0737FE2B0>, <__main__.karakter object at 0x000002C0737FC670>, <__main__.karakter object at 0x000002C073900460>, <__main__.karakter object at 0x000002C073917280>]
[<__main__.karakter object at 0x000002C0737FE310>, <__main__.karakter object at 0x000002C0738F3940>, <__main__.karakter object at 0x000002C0738F6BE0>, <__main__.karakter object at 0x000002C0739004C0>, <__main__.karakter object at 0x000002C07390DBE0>, <__main__.karakter object at 0x000002C0739A15E0>, <__main__.karakter object at 0x000002C073A30F10>]
[<__main__.karakter object at 0x000002C0737FC6D0>, <__main__.karakter object at 0x000002C07385E2E0>, <__main__.karakter object at 0x000002C073864A00>, <__main__.karakter object at 0x000002C071113CA0>, <__main__.karakter object at 0x000002C0738F6C40>]
[<__main__.karakter object at 0x000002C0737FC730>, <__main__.karakter object at 0x000002C073864A60>, <__main__.karakter object at 0x000002C073814E20>, <__main__.karakter object at 0x000002C0738F6CA0>, <__main__.karakter object at 0x000002C07390DC40>, <__main__.karakter object at 0x000002C0739172E0>, <__main__.karakter object at 0x000002C0739AA400>]
[<__main__.karakter object at 0x000002C0737FC790>, <__main__.karakter object at 0x000002C0738F39A0>, <__main__.karakter object at 0x000002C0738F6D00>, <__main__.karakter object at 0x000002C073904BE0>, <__main__.karakter object at 0x000002C073917340>, <__main__.karakter object at 0x000002C073A30F70>, <__main__.karakter object at 0x000002C073A43340>]
[<__main__.karakter object at 0x000002C0737FC7F0>, <__main__.karakter object at 0x000002C071750670>, <__main__.karakter object at 0x000002C0725A4760>, <__main__.karakter object at 0x000002C0738F3A00>, <__main__.karakter object at 0x000002C07390DCA0>, <__main__.karakter object at 0x000002C073A30070>, <__main__.karakter object at 0x000002C073A3AEB0>]
[<__main__.karakter object at 0x000002C0725A42B0>, <__main__.karakter object at 0x000002C0717F2460>, <__main__.karakter object at 0x000002C073900520>, <__main__.karakter object at 0x000002C073A19DC0>]
[<__main__.karakter object at 0x000002C073864AC0>, <__main__.karakter object at 0x000002C0738CC820>, <__main__.karakter object at 0x000002C07390DD00>, <__main__.karakter object at 0x000002C0739C3250>]
[<__main__.karakter object at 0x000002C0737FC850>, <__main__.karakter object at 0x000002C07385E400>, <__main__.karakter object at 0x000002C073946F40>, <__main__.karakter object at 0x000002C073A19160>]
[<__main__.karakter object at 0x000002C0738CCB50>, <__main__.karakter object at 0x000002C073814A90>, <__main__.karakter object at 0x000002C0738F3A60>, <__main__.karakter object at 0x000002C0739A1640>, <__main__.karakter object at 0x000002C073A433A0>]
[<__main__.karakter object at 0x000002C07385E460>, <__main__.karakter object at 0x000002C073864B20>, <__main__.karakter object at 0x000002C073814E80>, <__main__.karakter object at 0x000002C073904CA0>, <__main__.karakter object at 0x000002C0739173A0>]
[<__main__.karakter object at 0x000002C0725A4520>, <__main__.karakter object at 0x000002C0738CCB80>, <__main__.karakter object at 0x000002C07390DD60>, <__main__.karakter object at 0x000002C073917400>]
[<__main__.karakter object at 0x000002C0737FC8B0>, <__main__.karakter object at 0x000002C0738CCE20>, <__main__.karakter object at 0x000002C0739005E0>, <__main__.karakter object at 0x000002C0739AA460>]
[<__main__.karakter object at 0x000002C073900640>, <__main__.karakter object at 0x000002C073904D00>, <__main__.karakter object at 0x000002C07390DDC0>, <__main__.karakter object at 0x000002C073943A00>]
[<__main__.karakter object at 0x000002C073864BE0>, <__main__.karakter object at 0x000002C073900700>, <__main__.karakter object at 0x000002C073917460>, <__main__.karakter object at 0x000002C073946400>]
[<__main__.karakter object at 0x000002C0738F6DC0>, <__main__.karakter object at 0x000002C073900760>, <__main__.karakter object at 0x000002C073904DC0>, <__main__.karakter object at 0x000002C0739AA4C0>]
[<__main__.karakter object at 0x000002C0737FC970>, <__main__.karakter object at 0x000002C0738F3B80>, <__main__.karakter object at 0x000002C0739007C0>, <__main__.karakter object at 0x000002C073904E20>, <__main__.karakter object at 0x000002C0739AA520>, <__main__.karakter object at 0x000002C0739434C0>]
[<__main__.karakter object at 0x000002C07385E4C0>, <__main__.karakter object at 0x000002C073864C40>, <__main__.karakter object at 0x000002C0738CC4F0>, <__main__.karakter object at 0x000002C073814400>, <__main__.karakter object at 0x000002C0739A16A0>]
[<__main__.karakter object at 0x000002C073864CA0>, <__main__.karakter object at 0x000002C071767E80>, <__main__.karakter object at 0x000002C0738EE1C0>, <__main__.karakter object at 0x000002C073904EE0>, <__main__.karakter object at 0x000002C073946F10>, <__main__.karakter object at 0x000002C073943670>]
[<__main__.karakter object at 0x000002C071767130>, <__main__.karakter object at 0x000002C0738F6E80>, <__main__.karakter object at 0x000002C073917520>, <__main__.karakter object at 0x000002C0739A1700>]
[<__main__.karakter object at 0x000002C073864D00>, <__main__.karakter object at 0x000002C0725A4460>, <__main__.karakter object at 0x000002C0738EE220>, <__main__.karakter object at 0x000002C073900820>, <__main__.karakter object at 0x000002C07390DFA0>]
[<__main__.karakter object at 0x000002C0738EE280>, <__main__.karakter object at 0x000002C0738F6EE0>, <__main__.karakter object at 0x000002C07390DFD0>, <__main__.karakter object at 0x000002C0739A1760>]
[<__main__.karakter object at 0x000002C0725A45E0>, <__main__.karakter object at 0x000002C0738CC0A0>, <__main__.karakter object at 0x000002C0717F26A0>, <__main__.karakter object at 0x000002C0739008E0>, <__main__.karakter object at 0x000002C073904FA0>, <__main__.karakter object at 0x000002C0739AA580>]
[<__main__.karakter object at 0x000002C07385E580>, <__main__.karakter object at 0x000002C071767100>, <__main__.karakter object at 0x000002C0738F3BE0>, <__main__.karakter object at 0x000002C073900940>, <__main__.karakter object at 0x000002C0739A1820>, <__main__.karakter object at 0x000002C071796760>, <__main__.karakter object at 0x000002C073943D30>, <__main__.karakter object at 0x000002C073A19E80>]
[<__main__.karakter object at 0x000002C07385E6A0>, <__main__.karakter object at 0x000002C073864D60>, <__main__.karakter object at 0x000002C0725A48B0>, <__main__.karakter object at 0x000002C0738CC2E0>, <__main__.karakter object at 0x000002C0738EE340>]
[<__main__.karakter object at 0x000002C073864DC0>, <__main__.karakter object at 0x000002C071767400>, <__main__.karakter object at 0x000002C07390D3D0>, <__main__.karakter object at 0x000002C0739A18E0>, <__main__.karakter object at 0x000002C0739AA5E0>, <__main__.karakter object at 0x000002C073A43430>]
[<__main__.karakter object at 0x000002C073864E20>, <__main__.karakter object at 0x000002C0738EE3A0>, <__main__.karakter object at 0x000002C0738F3C40>, <__main__.karakter object at 0x000002C0739A1940>]
[<__main__.karakter object at 0x000002C07385E7C0>, <__main__.karakter object at 0x000002C071767A30>, <__main__.karakter object at 0x000002C0725A4370>, <__main__.karakter object at 0x000002C0738CCCD0>, <__main__.karakter object at 0x000002C0739009A0>, <__main__.karakter object at 0x000002C0739046D0>]
[<__main__.karakter object at 0x000002C0725A44F0>, <__main__.karakter object at 0x000002C0738EE400>, <__main__.karakter object at 0x000002C0739175E0>, <__main__.karakter object at 0x000002C073A38C10>]
[<__main__.karakter object at 0x000002C0738CC220>, <__main__.karakter object at 0x000002C073900A00>, <__main__.karakter object at 0x000002C073904790>, <__main__.karakter object at 0x000002C073917640>, <__main__.karakter object at 0x000002C073A28E50>, <__main__.karakter object at 0x000002C073A43550>]

In [184]:
len(keluarga_list)

435

In [185]:
len(keluarga_list)*2

870

# **Turnamen System**

In [ ]:
random.shuffle(karakter_list)
RoundOf64 = []
for i in range(0,len(karakter_list),2):
  win_name = duel(karakter_list[i],karakter_list[i+1])
  print(karakter_list[i].name+" vs "+karakter_list[i+1].name+" ---> "+win_name)
  print(" ")
  if karakter_list[i].name == win_name:
    RoundOf64.append(karakter_list[i])
  else:
    RoundOf64.append(karakter_list[i+1])

Putu Winner
Putu vs Ayu ---> Putu

Muhamad Winner
Ratih vs Muhamad ---> Muhamad

Noah Winner
William vs Noah ---> Noah

Dina Winner
Amalia vs Dina ---> Dina

Kusuma Winner
Kartika vs Kusuma ---> Kusuma

Theodore Winner
Angga vs Theodore ---> Theodore

Retno Winner
Mason vs Retno ---> Retno

Prima Winner
Rizki vs Prima ---> Prima

Mateo Winner
Fajar vs Mateo ---> Mateo

Irma Winner
Irma vs Amelia ---> Irma

James Winner
Aditya vs James ---> James

Rina Winner
Maya vs Rina ---> Rina

Novita Winner
Novita vs Ahmad ---> Novita

Ratna Winner
Ratna vs Ethan ---> Ratna

Ari Winner
Diana vs Ari ---> Ari

Ika Winner
Hendra vs Ika ---> Ika

Logan Winner
Logan vs Wulan ---> Logan

Astuti Winner
Astuti vs Wulandari ---> Astuti

Muhammad Winner
Muhammad vs Fitria ---> Muhammad

Diah Winner
Indra vs Diah ---> Diah

Levi Winner
Levi vs Michael ---> Levi

Maria Winner
Yunita vs Maria ---> Maria

Rahayu Winner
Agung vs Rahayu ---> Rahayu

Citra Winner
Arif vs Citra ---> Citra

Raden Winner
Arief vs Raden ---> Raden

Oliver Winner
Owen vs Oliver ---> Oliver

Handayani Winner
Indah vs Handayani ---> Handayani

Rahmawati Winner
Puspita vs Rahmawati ---> Rahmawati

Liam Winner
Elijah vs Liam ---> Liam

Sari Winner
Sari vs Wahyuni ---> Sari

Puji Winner
Puji vs Lucas ---> Puji

Gerald Winner
Gerald vs Sebastian ---> Gerald

Adi Winner
Fitri vs Adi ---> Adi

Aiden Winner
Eva vs Aiden ---> Aiden

Budi Winner
Samuel vs Budi ---> Budi

Setiawan Winner
Henry vs Setiawan ---> Setiawan

Bayu Winner
Bayu vs Sri ---> Bayu

Nugroho Winner
Lestari vs Nugroho ---> Nugroho

Kurniawan Winner
Kurniawan vs Endah ---> Kurniawan

Devi Winner
Devi vs Rizky ---> Devi

Daniel Winner
Daniel vs Kurnia ---> Daniel

Ni Winner
Ni vs Abdul ---> Ni

Anita Winner
Alexander vs Anita ---> Anita

Eka Winner
Munaroh vs Eka ---> Eka

Widya Winner
Drando vs Widya ---> Widya

Hadi Winner
Saputra vs Hadi ---> Hadi

Putri Winner
Putri vs Made ---> Putri

Ade Winner
Farras vs Ade ---> Ade

Eko Winner
Eko vs Benjamin ---> Eko

Bagus Winner
Dyah vs Bagus ---> Bagus

Anggraini Winner
Anggraini vs Utami ---> Anggraini

Rini Winner
Dwi vs Rini ---> Rini

Putra Winner
Novi vs Putra ---> Putra

Azka Winner
Andi vs Azka ---> Azka

Ria Winner
Ria vs Intan ---> Ria

Surya Winner
Surya vs Siti ---> Surya

Hidayat Winner
Wahyu vs Hidayat ---> Hidayat

Tri Winner
Jack vs Tri ---> Tri

Dian Winner
Dian vs Yulia ---> Dian

Dewi Winner
Achmad vs Dewi ---> Dewi

Plakasa Winner
Plakasa vs Aulia ---> Plakasa

Jacob Winner
Jacob vs Nurul ---> Jacob

Pratiwi Winner
Agus vs Pratiwi ---> Pratiwi

Ilham Winner
Agustina vs Ilham ---> Ilham

In [ ]:
RoundOf32 = []
for i in range(0,len(RoundOf64),2):
  win_name = duel(RoundOf64[i],RoundOf64[i+1])
  print(RoundOf64[i].name+" vs "+RoundOf64[i+1].name+" ---> "+win_name)
  print(" ")
  if RoundOf64[i].name == win_name:
    RoundOf32.append(RoundOf64[i])
  else:
    RoundOf32.append(RoundOf64[i+1])

Putu Winner
Putu vs Muhamad ---> Putu

Noah Winner
Noah vs Dina ---> Noah

Theodore Winner
Kusuma vs Theodore ---> Theodore

Prima Winner
Retno vs Prima ---> Prima

Mateo Winner
Mateo vs Irma ---> Mateo

James Winner
James vs Rina ---> James

Ratna Winner
Novita vs Ratna ---> Ratna

Ika Winner
Ari vs Ika ---> Ika

Logan Winner
Logan vs Astuti ---> Logan

Diah Winner
Muhammad vs Diah ---> Diah

Maria Winner
Levi vs Maria ---> Maria

Citra Winner
Rahayu vs Citra ---> Citra

Oliver Winner
Raden vs Oliver ---> Oliver

Handayani Winner
Handayani vs Rahmawati ---> Handayani

Sari Winner
Liam vs Sari ---> Sari

Puji Winner
Puji vs Gerald ---> Puji

Adi Winner
Adi vs Aiden ---> Adi

Setiawan Winner
Budi vs Setiawan ---> Setiawan

Nugroho Winner
Bayu vs Nugroho ---> Nugroho

Devi Winner
Kurniawan vs Devi ---> Devi

Ni Winner
Daniel vs Ni ---> Ni

Anita Winner
Anita vs Eka ---> Anita

Hadi Winner
Widya vs Hadi ---> Hadi

Putri Winner
Putri vs Ade ---> Putri

Eko Winner
Eko vs Bagus ---> Eko

Rini Winner
Anggraini vs Rini ---> Rini

Azka Winner
Putra vs Azka ---> Azka

Ria Winner
Ria vs Surya ---> Ria

Hidayat Winner
Hidayat vs Tri ---> Hidayat

Dian Winner
Dian vs Dewi ---> Dian

Plakasa Winner
Plakasa vs Jacob ---> Plakasa

Ilham Winner
Pratiwi vs Ilham ---> Ilham

In [ ]:
RoundOf16 = []
for i in range(0,len(RoundOf32),2):
  win_name = duel(RoundOf32[i],RoundOf32[i+1])
  print(RoundOf32[i].name+" vs "+RoundOf32[i+1].name+" ---> "+win_name)
  print(" ")
  if RoundOf32[i].name == win_name:
    RoundOf16.append(RoundOf32[i])
  else:
    RoundOf16.append(RoundOf32[i+1])

Putu Winner
Putu vs Noah ---> Putu

Theodore Winner
Theodore vs Prima ---> Theodore

James Winner
Mateo vs James ---> James

Ika Winner
Ratna vs Ika ---> Ika

Logan Winner
Logan vs Diah ---> Logan

Maria Winner
Maria vs Citra ---> Maria

Handayani Winner
Oliver vs Handayani ---> Handayani

Puji Winner
Sari vs Puji ---> Puji

Adi Winner
Adi vs Setiawan ---> Adi

Nugroho Winner
Nugroho vs Devi ---> Nugroho

Ni Winner
Ni vs Anita ---> Ni

Hadi Winner
Hadi vs Putri ---> Hadi

Rini Winner
Eko vs Rini ---> Rini

Ria Winner
Azka vs Ria ---> Ria

Hidayat Winner
Hidayat vs Dian ---> Hidayat

Plakasa Winner
Plakasa vs Ilham ---> Plakasa

In [ ]:
QuarterFinal = []
for i in range(0,len(RoundOf16),2):
  win_name = duel(RoundOf16[i],RoundOf16[i+1])
  print(RoundOf16[i].name+" vs "+RoundOf16[i+1].name+" ---> "+win_name)
  print(" ")
  if RoundOf16[i].name == win_name:
    QuarterFinal.append(RoundOf16[i])
  else:
    QuarterFinal.append(RoundOf16[i+1])

Putu Winner
Putu vs Theodore ---> Putu

Ika Winner
James vs Ika ---> Ika

Logan Winner
Logan vs Maria ---> Logan

Puji Winner
Handayani vs Puji ---> Puji

Adi Winner
Adi vs Nugroho ---> Adi

Ni Winner
Ni vs Hadi ---> Ni

Rini Winner
Rini vs Ria ---> Rini

Hidayat Winner
Hidayat vs Plakasa ---> Hidayat

In [ ]:
SemiFinal = []
for i in range(0,len(QuarterFinal),2):
  win_name = duel(QuarterFinal[i],QuarterFinal[i+1])
  print(QuarterFinal[i].name+" vs "+QuarterFinal[i+1].name+" ---> "+win_name)
  print(" ")
  if QuarterFinal[i].name == win_name:
    SemiFinal.append(QuarterFinal[i])
  else:
    SemiFinal.append(QuarterFinal[i+1])

Putu Winner
Putu vs Ika ---> Putu

Puji Winner
Logan vs Puji ---> Puji

Adi Winner
Adi vs Ni ---> Adi

Hidayat Winner
Rini vs Hidayat ---> Hidayat

In [ ]:
Final = []
for i in range(0,len(SemiFinal),2):
  win_name = duel(SemiFinal[i],SemiFinal[i+1])
  print(SemiFinal[i].name+" vs "+SemiFinal[i+1].name+" ---> "+win_name)
  print(" ")
  if SemiFinal[i].name == win_name:
    Final.append(SemiFinal[i])
  else:
    Final.append(SemiFinal[i+1])

Putu Winner
Putu vs Puji ---> Putu

Adi Winner
Adi vs Hidayat ---> Adi

In [ ]:
win_name = duel(Final[0],Final[1])
print(Final[0].name+" vs "+Final[1].name+" ---> "+win_name)
print(" ")

Adi Winner
Putu vs Adi ---> Adi

# **System AI Character Class (First Creation)**

In [11]:
karakter_list = []
karakter_info = [[],[],[],[],[],[],[],[],[],[],[],[]]
for i in range(6000):
  if i < 2400:
    umur = random.randint(15, 40)
  else:
    umur = random.randint(1, 99)
  karakter_list.append(karakter("user-"+str(i+1),umur))
  karakter_info[0].append(karakter_list[i].name)
  karakter_info[1].append(karakter_list[i].age)
  karakter_info[2].append(karakter_list[i].power.atk)
  karakter_info[3].append(karakter_list[i].power.defend)
  karakter_info[4].append(karakter_list[i].power.health)
  karakter_info[5].append(karakter_list[i].power.spd)
  karakter_info[6].append(karakter_list[i].power.stamina)
  karakter_info[7].append(0)
  karakter_info[8].append(0)
  karakter_info[9].append("-")
  karakter_info[10].append(karakter_list[i].sex)
  karakter_info[11].append(karakter_list[i].sex_role)
df = pd.DataFrame(karakter_info)
df = df.transpose()
df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose", "Class", "Kelamin", "Kategori"], axis=1)
df

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Class,Kelamin,Kategori
0,user-1,29,3,6,712,10,79,0,0,-,Laki-laki,Dewasa Tua
1,user-2,24,16,11,893,4,138,0,0,-,Laki-laki,Dewasa Muda
2,user-3,35,17,7,216,7,108,0,0,-,Perempuan,Dewasa Tua
3,user-4,25,12,5,263,2,131,0,0,-,Laki-laki,Dewasa Tua
4,user-5,37,12,0,525,7,84,0,0,-,Perempuan,Dewasa Tua
...,...,...,...,...,...,...,...,...,...,...,...,...
5995,user-5996,58,1,6,626,8,19,0,0,-,Laki-laki,Lansia
5996,user-5997,10,19,6,228,0,49,0,0,-,Perempuan,Remaja
5997,user-5998,79,20,3,284,2,7,0,0,-,Laki-laki,Lansia
5998,user-5999,91,20,13,793,8,4,0,0,-,Perempuan,Lansia
5999,user-6000,92,5,19,968,1,4,0,0,-,Laki-laki,Lansia

In [12]:
df.loc[df["Kategori"] == "Remaja"]

,Name,Age,Atk,Def,HP,Spd,Stamina,win,Lose,Class,Kelamin,Kategori
2426,user-2427,11,17,18,303,1,24,0,0,-,Laki-laki,Remaja
2427,user-2428,14,10,10,869,4,52,0,0,-,Laki-laki,Remaja
2436,user-2437,8,8,8,666,2,23,0,0,-,Laki-laki,Remaja
2445,user-2446,9,4,20,621,10,18,0,0,-,Laki-laki,Remaja
2450,user-2451,13,9,10,217,0,26,0,0,-,Perempuan,Remaja
...,...,...,...,...,...,...,...,...,...,...,...,...
5958,user-5959,7,6,10,928,2,16,0,0,-,Laki-laki,Remaja
5983,user-5984,11,6,17,805,9,21,0,0,-,Laki-laki,Remaja
5984,user-5985,14,15,16,380,1,42,0,0,-,Perempuan,Remaja
5989,user-5990,11,13,17,548,10,42,0,0,-,Perempuan,Remaja
5996,user-5997,10,19,6,228,0,49,0,0,-,Perempuan,Remaja

In [13]:
# 6000 orang
# 200x Duel
# Waktu Executing : 17 menit

In [14]:
df_duel = df.loc[df["Age"] >= 10]
df_duel.reset_index()
lis_temp = list(df_duel["Name"])
karakter_list_duel = [char for char in karakter_list if char.name in lis_temp]
# for char in karakter_list:
#   if char.name in lis_temp:
#     karakter_list_duel.append(char)

for j in range(200):
  random.shuffle(karakter_list_duel)
  for i in range(0,len(karakter_list_duel),2):
    if(i+1 != len(karakter_list_duel)):
      win_name = duel(karakter_list_duel[i],karakter_list_duel[i+1])
      if karakter_list_duel[i].name == win_name:
        lose_name = karakter_list_duel[i+1].name
      else:
        lose_name = karakter_list_duel[i].name

      idx = df_duel[df_duel['Name']==win_name].index.values
      df_duel.at[idx[0],'win'] += 1

      idx = df_duel[df_duel['Name']==lose_name].index.values
      df_duel.at[idx[0],'Lose'] += 1

KeyboardInterrupt:

In [ ]:
df_duel.sort_values("win")

In [ ]:
df_merge = pd.merge(df, df_duel, how="left", on=["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "Class", "Kelamin", "Kategori"])
df_merge = df_merge.drop(["win_x", "Lose_x"], axis=1)
df_merge = df_merge.rename(columns={"win_y":"Win", "Lose_y":"Lose"})
df_merge = df_merge.fillna(0)
df_merge

           Name  Age  Atk  Def   HP  ...  Class    Kelamin     Kategori  Win Lose
0        user-1   37   20   11  729  ...      -  Laki-laki   Dewasa Tua  191    9
1        user-2   15    3   20  639  ...      -  Perempuan  Dewasa Muda   43  157
2        user-3   18    3   15  464  ...      -  Laki-laki  Dewasa Muda   19  181
3        user-4   16   18   20  498  ...      -  Perempuan  Dewasa Muda  151   49
4        user-5   40   19    2  292  ...      -  Laki-laki       Lansia   89  111
...         ...  ...  ...  ...  ...  ...    ...        ...          ...  ...  ...
5995  user-5996   44    9    3  758  ...      -  Perempuan       Lansia  113   87
5996  user-5997   64   13   16  755  ...      -  Perempuan       Lansia  167   33
5997  user-5998   30   13   10  400  ...      -  Laki-laki   Dewasa Tua  112   88
5998  user-5999   21    4   19  260  ...      -  Perempuan  Dewasa Muda   27  173
5999  user-6000    2   16    4  703  ...      -  Laki-laki    Anak-anak    0    0

[6000 rows x 12 columns]

In [ ]:
df_merge.loc[df_merge["Win"] < 95]

           Name  Age  Atk  Def   HP  ...  Class    Kelamin     Kategori Win Lose
1        user-2   15    3   20  639  ...      -  Perempuan  Dewasa Muda  43  157
2        user-3   18    3   15  464  ...      -  Laki-laki  Dewasa Muda  19  181
4        user-5   40   19    2  292  ...      -  Laki-laki       Lansia  89  111
11      user-12   15    3   14  724  ...      -  Laki-laki  Dewasa Muda  40  160
16      user-17   38   17    3  284  ...      -  Perempuan   Dewasa Tua  85  115
...         ...  ...  ...  ...  ...  ...    ...        ...          ...  ..  ...
5987  user-5988   17    1   13  332  ...      -  Perempuan  Dewasa Muda   2  198
5988  user-5989   56    3    1  417  ...      -  Laki-laki       Lansia  16  184
5993  user-5994    4    8   14  856  ...      -  Perempuan    Anak-anak   0    0
5998  user-5999   21    4   19  260  ...      -  Perempuan  Dewasa Muda  27  173
5999  user-6000    2   16    4  703  ...      -  Laki-laki    Anak-anak   0    0

[3003 rows x 12 columns]

In [ ]:
df_non = df_merge.loc[df_merge["Win"] < 95]
df_non = df_non.replace({"-":"non-fighter"})
df_non

           Name  Age  Atk  Def  ...    Kelamin     Kategori  Win Lose
1        user-2   15    3   20  ...  Perempuan  Dewasa Muda   43  157
2        user-3   18    3   15  ...  Laki-laki  Dewasa Muda   19  181
4        user-5   40   19    2  ...  Laki-laki       Lansia   89  111
11      user-12   15    3   14  ...  Laki-laki  Dewasa Muda   40  160
16      user-17   38   17    3  ...  Perempuan   Dewasa Tua   85  115
...         ...  ...  ...  ...  ...        ...          ...  ...  ...
5987  user-5988   17    1   13  ...  Perempuan  Dewasa Muda    2  198
5988  user-5989   56    3    1  ...  Laki-laki       Lansia   16  184
5993  user-5994    4    8   14  ...  Perempuan    Anak-anak    0    0
5998  user-5999   21    4   19  ...  Perempuan  Dewasa Muda   27  173
5999  user-6000    2   16    4  ...  Laki-laki    Anak-anak    0    0

[3003 rows x 12 columns]

In [ ]:
df_merge = pd.merge(df_non, df_merge, how="right", on=["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "Win", "Lose", "Kelamin", "Kategori"])
df_merge = df_merge.drop(["Class_y"], axis=1)
df_merge = df_merge.rename(columns={"Class_x":"Class"})
df_merge = df_merge.fillna("fighter")
df_merge

           Name  Age  Atk  Def  ...    Kelamin     Kategori  Win Lose
0        user-1   37   20   11  ...  Laki-laki   Dewasa Tua  191    9
1        user-2   15    3   20  ...  Perempuan  Dewasa Muda   43  157
2        user-3   18    3   15  ...  Laki-laki  Dewasa Muda   19  181
3        user-4   16   18   20  ...  Perempuan  Dewasa Muda  151   49
4        user-5   40   19    2  ...  Laki-laki       Lansia   89  111
...         ...  ...  ...  ...  ...        ...          ...  ...  ...
5995  user-5996   44    9    3  ...  Perempuan       Lansia  113   87
5996  user-5997   64   13   16  ...  Perempuan       Lansia  167   33
5997  user-5998   30   13   10  ...  Laki-laki   Dewasa Tua  112   88
5998  user-5999   21    4   19  ...  Perempuan  Dewasa Muda   27  173
5999  user-6000    2   16    4  ...  Laki-laki    Anak-anak    0    0

[6000 rows x 12 columns]

In [ ]:
dataset = df_merge.drop(["Name","Win","Lose",'Kelamin','Kategori'], axis=1)
dataset

      Age  Atk  Def   HP  Spd  Stamina        Class
0      37   20   11  729   10      148      fighter
1      15    3   20  639    6      144  non-fighter
2      18    3   15  464   10      117  non-fighter
3      16   18   20  498    3       80      fighter
4      40   19    2  292    6      126  non-fighter
...   ...  ...  ...  ...  ...      ...          ...
5995   44    9    3  758    8       67      fighter
5996   64   13   16  755    2       13      fighter
5997   30   13   10  400   10      148      fighter
5998   21    4   19  260    9      131  non-fighter
5999    2   16    4  703    2        3  non-fighter

[6000 rows x 7 columns]

In [ ]:
# Pre-Processing
dataset_pre = dataset.replace({"non-fighter":0, "fighter":1})
dataset_pre_target = dataset_pre["Class"]
dataset_pre_data = dataset_pre.drop(["Class"], axis=1)

In [ ]:
# Normalisasi

d = preprocessing.normalize(dataset_pre_data, axis=0)
dataset_normal = pd.DataFrame(d, columns=["Age","Atk","Def","HP","Spd","Stamina"])
dataset_normal

           Age       Atk       Def        HP       Spd   Stamina
0     0.010014  0.021572  0.012047  0.014673  0.021516  0.020912
1     0.004060  0.003236  0.021903  0.012862  0.012910  0.020347
2     0.004871  0.003236  0.016428  0.009339  0.021516  0.016532
3     0.004330  0.019415  0.021903  0.010024  0.006455  0.011304
4     0.010825  0.020494  0.002190  0.005877  0.012910  0.017803
...        ...       ...       ...       ...       ...       ...
5995  0.011908  0.009708  0.003286  0.015257  0.017213  0.009467
5996  0.017321  0.014022  0.017523  0.015197  0.004303  0.001837
5997  0.008119  0.014022  0.010952  0.008051  0.021516  0.020912
5998  0.005683  0.004314  0.020808  0.005233  0.019364  0.018510
5999  0.000541  0.017258  0.004381  0.014150  0.004303  0.000424

[6000 rows x 6 columns]

In [ ]:
# Split Data

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(dataset_normal, dataset_pre_target, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
# Tuning Parameters
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END .......C=0.1, gamma=10, kernel=rbf;, score=0.505 total time=   0.8s
[CV 2/5] END .......C=0.1, gamma=10, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .......C=0.1, gamma=10, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .......C=0.1, gamma=10, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .......C=0.1, gamma=10, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.8s
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .........C=1, gamma=10, kernel=rbf;, score=0.881 total time=   0.6s
[CV 2/5] END .........C=1, gamma=10, kernel=rbf;, score=0.882 total time=   0.6s
[CV 3/5] END .........C=1, gamma=10, kernel=rbf;, score=0.880 total time=   0.6s
[CV 4/5] END .........C=1, gamma=10, kernel=rbf;, score=0.840 total time=   0.5s
[CV 5/5] END .........C=1, gamma=10, kernel=rbf;, score=0.874 total time=   0.6s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ........C=10, gamma=10, kernel=rbf;, score=0.902 total time=   0.3s
[CV 2/5] END ........C=10, gamma=10, kernel=rbf;, score=0.914 total time=   0.3s
[CV 3/5] END ........C=10, gamma=10, kernel=rbf;, score=0.901 total time=   0.3s
[CV 4/5] END ........C=10, gamma=10, kernel=rbf;, score=0.879 total time=   0.3s
[CV 5/5] END ........C=10, gamma=10, kernel=rbf;, score=0.918 total time=   0.3s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.880 total time=   0.6s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.883 total time=   0.5s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.880 total time=   0.6s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.840 total time=   0.5s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.874 total time=   0.6s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END .......C=100, gamma=10, kernel=rbf;, score=0.905 total time=   0.2s
[CV 2/5] END .......C=100, gamma=10, kernel=rbf;, score=0.914 total time=   0.2s
[CV 3/5] END .......C=100, gamma=10, kernel=rbf;, score=0.911 total time=   0.2s
[CV 4/5] END .......C=100, gamma=10, kernel=rbf;, score=0.883 total time=   0.2s
[CV 5/5] END .......C=100, gamma=10, kernel=rbf;, score=0.918 total time=   0.2s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.898 total time=   0.3s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.914 total time=   0.3s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.900 total time=   0.3s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.879 total time=   0.3s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.918 total time=   0.3s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.5s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.883 total time=   0.6s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.6s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.840 total time=   0.6s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.874 total time=   0.6s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.8s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.913 total time=   0.2s
[CV 2/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.933 total time=   0.2s
[CV 3/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.923 total time=   0.2s
[CV 4/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.904 total time=   0.2s
[CV 5/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.939 total time=   0.2s
[CV 1/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.902 total time=   0.2s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.908 total time=   0.2s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.908 total time=   0.2s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.879 total time=   0.2s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.913 total time=   0.2s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.898 total time=   0.3s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.914 total time=   0.3s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.900 total time=   0.3s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.879 total time=   0.3s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.918 total time=   0.3s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.881 total time=   0.5s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.882 total time=   0.6s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.881 total time=   0.6s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.840 total time=   0.5s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.874 total time=   0.6s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.7s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.505 total time=   0.8s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.504 total time=   0.7s

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [ ]:
filename = 'svm_first_model.sav'
joblib.dump(grid, filename)

['svm_first_model.sav']

In [ ]:
y_pred = grid.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.93       886
           1       0.92      0.93      0.93       914

    accuracy                           0.93      1800
   macro avg       0.93      0.93      0.93      1800
weighted avg       0.93      0.93      0.93      1800


# **Character Class Automatic Test System**

In [ ]:
nama = "Gerald Plakasa Drando Dwi Azka Muhammad Farras Dewi Tri Dian Sri Putri Eka Sari Ayu Wahyu Indah Siti Ika Agus Fitri Ratna Andi Agung Ahmad Kurniawan Ilham Budi Adi Eko Nurul Putra Ni Arif Puspita Ari Indra Dyah Rizki Maria Ratih Pratiwi Kartika Wulandari Fajar Bayu Lestari Anita Muhamad Kusuma Rahmawati Fitria Retno Kurnia Novita Aditya Ria Nugroho Putu Handayani Rahayu Yunita Rina Ade Widya Intan Diah Agustina Made Abdul Setiawan Rizky Rini Wahyuni Yulia Maya Puji Utami Amalia Dina Devi Citra Arief Munaroh Bagus Hidayat Hendra Eva Endah Raden Novi Irma Astuti Achmad Aulia Surya Amelia Prima Angga Hadi Diana Anggraini Wulan Saputra Liam Noah Oliver Elijah William James Benjamin Lucas Henry Alexander Mason Michael Ethan Daniel Jacob Logan Levi Sebastian Mateo Jack Owen Theodore Aiden Samuel"
names = nama.split()

In [ ]:
karakter_list = []
karakter_info = [[],[],[],[],[],[],[]]
for i in range(len(names)):
  umur = random.randint(1, 99)
  karakter_list.append(karakter(names[i],umur))
  karakter_info[0].append(karakter_list[i].name)
  karakter_info[1].append(karakter_list[i].age)
  karakter_info[2].append(karakter_list[i].power.atk)
  karakter_info[3].append(karakter_list[i].power.defend)
  karakter_info[4].append(karakter_list[i].power.health)
  karakter_info[5].append(karakter_list[i].power.spd)
  karakter_info[6].append(karakter_list[i].power.stamina)
  
df = pd.DataFrame(karakter_info).transpose()
df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina"], axis=1)
df_temp = df.copy().drop(["Name"], axis = 1)
d = preprocessing.normalize(df_temp, axis=0)
df_normal = pd.DataFrame(d, columns=["Age","Atk","Def","HP","Spd","Stamina"])
hasil = grid.predict(df_normal)

df["Class"] = hasil
df["Class"] = df["Class"].replace({0:"non-fighter", 1:"fighter"})
df

         Name Age Atk Def   HP Spd Stamina        Class
0      Gerald  49  13  18  522   1      38  non-fighter
1     Plakasa  34   4   5  487   8     125  non-fighter
2      Drando  33  15  15  263   3     147  non-fighter
3         Dwi  88   4   7  209   9       9  non-fighter
4        Azka  22  19  10  522   6      86      fighter
..        ...  ..  ..  ..  ...  ..     ...          ...
123      Jack  75   1  11  916   1      10  non-fighter
124      Owen  43   4   6  879   0      86  non-fighter
125  Theodore   5  19  16  775   2      15  non-fighter
126     Aiden  88  17   1  485   3       4  non-fighter
127    Samuel  97   4  12  987   6       4  non-fighter

[128 rows x 8 columns]

In [ ]:
df_fighter = df.loc[df["Class"] == "fighter"]
df_fighter

         Name Age Atk Def   HP Spd Stamina    Class
4        Azka  22  19  10  522   6      86  fighter
6      Farras   9  16  12  670   0      45  fighter
8         Tri  49  14   7  599   3      49  fighter
12        Eka  36  14   0  339   6      80  fighter
13       Sari  25  18   4  672   1      86  fighter
14        Ayu  14  13   8  213   0      71  fighter
15      Wahyu  10   2   0  331   0      50  fighter
16      Indah  26  12  11  468   6      97  fighter
20      Fitri  11   9   3  959   1      37  fighter
21      Ratna  44   7   9  442   3      70  fighter
22       Andi  35   6  11  589   0      99  fighter
26      Ilham  77  13   2  606   0      10  fighter
36      Indra  48  14   4  944   6      43  fighter
37       Dyah   5   6   4  442   4      22  fighter
38      Rizki  52   3   2  877   5      19  fighter
41    Pratiwi  81  10   4  339   0       6  fighter
46    Lestari   9  12  14  299   0      43  fighter
56        Ria  71   5   1  668   2       7  fighter
57    Nugroho  65  17   6  815   1      10  fighter
61     Yunita   2   9   2  949   0       6  fighter
67   Agustina  31  12   2  396   2     131  fighter
75       Maya   5   3   2  761   5      20  fighter
79       Dina  36  12   2  362   1      94  fighter
81      Citra  48  12  11  842   4      24  fighter
88      Endah  46  10   8  423   6      73  fighter
89      Raden  59  20   8  958   0      15  fighter
90       Novi  48  16   5  568   2      45  fighter
91       Irma  13   8   5  853   2      52  fighter
96     Amelia  47  10   7  947   7      56  fighter
100     Diana  80   9   6  375   0       5  fighter
104      Liam   6  15   4  204   0      28  fighter
106    Oliver  12  10  19  551   1      50  fighter
114     Mason  25  12  14  502   3      88  fighter
116     Ethan  55  12   7  962   7      10  fighter
119     Logan  48  18   2  665   0      33  fighter

In [ ]:
df_fighter.sort_values("Age")

         Name Age Atk Def   HP Spd Stamina    Class
61     Yunita   2   9   2  949   0       6  fighter
37       Dyah   5   6   4  442   4      22  fighter
75       Maya   5   3   2  761   5      20  fighter
104      Liam   6  15   4  204   0      28  fighter
6      Farras   9  16  12  670   0      45  fighter
46    Lestari   9  12  14  299   0      43  fighter
15      Wahyu  10   2   0  331   0      50  fighter
20      Fitri  11   9   3  959   1      37  fighter
106    Oliver  12  10  19  551   1      50  fighter
91       Irma  13   8   5  853   2      52  fighter
14        Ayu  14  13   8  213   0      71  fighter
4        Azka  22  19  10  522   6      86  fighter
13       Sari  25  18   4  672   1      86  fighter
114     Mason  25  12  14  502   3      88  fighter
16      Indah  26  12  11  468   6      97  fighter
67   Agustina  31  12   2  396   2     131  fighter
22       Andi  35   6  11  589   0      99  fighter
12        Eka  36  14   0  339   6      80  fighter
79       Dina  36  12   2  362   1      94  fighter
21      Ratna  44   7   9  442   3      70  fighter
88      Endah  46  10   8  423   6      73  fighter
96     Amelia  47  10   7  947   7      56  fighter
90       Novi  48  16   5  568   2      45  fighter
119     Logan  48  18   2  665   0      33  fighter
36      Indra  48  14   4  944   6      43  fighter
81      Citra  48  12  11  842   4      24  fighter
8         Tri  49  14   7  599   3      49  fighter
38      Rizki  52   3   2  877   5      19  fighter
116     Ethan  55  12   7  962   7      10  fighter
89      Raden  59  20   8  958   0      15  fighter
57    Nugroho  65  17   6  815   1      10  fighter
56        Ria  71   5   1  668   2       7  fighter
26      Ilham  77  13   2  606   0      10  fighter
100     Diana  80   9   6  375   0       5  fighter
41    Pratiwi  81  10   4  339   0       6  fighter

# **System AI Character Class (After 10 y.o)**

In [ ]:
karakter_list = []
for i in range(1000):
  karakter_list.append(karakter("user-"+str(i+1),1))

day = 1
month = 1
year = 1

while(year < 10):
  if month > 12:
    year += 1
    ageUpList(karakter_list)
    month = 1
    day = 1
  if day > 30:
    month += 1
    day = 1
  karakter_list = daily(karakter_list)
  day += 1

karakter_info = [[],[],[],[],[],[],[],[],[],[],[]]
for i in range(len(karakter_list)):
  
  karakter_info[0].append(karakter_list[i].name)
  karakter_info[1].append(karakter_list[i].age)
  karakter_info[2].append(karakter_list[i].power.atk)
  karakter_info[3].append(karakter_list[i].power.defend)
  karakter_info[4].append(karakter_list[i].power.health)
  karakter_info[5].append(karakter_list[i].power.spd)
  karakter_info[6].append(karakter_list[i].power.stamina)
  karakter_info[7].append(0)
  karakter_info[8].append(0)
  karakter_info[9].append("-")
  karakter_info[10].append(karakter_list[i].coin)
df = pd.DataFrame(karakter_info)
df = df.transpose()
df = df.set_axis(["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose", "Class", "Coin"], axis=1)
df

          Name Age Atk  Def    HP Spd Stamina win Lose Class  Coin
0       user-1  10  86   90  1121  46      13   0    0     -   -26
1       user-2  10  59   94   723  51      15   0    0     -   134
2       user-3  10  67   51   975  48       9   0    0     -    68
3       user-4  10  67   86  1116  37      16   0    0     -   -37
4       user-5  10  64   66  1086  56       9   0    0     -    36
..         ...  ..  ..  ...   ...  ..     ...  ..  ...   ...   ...
995   user-996  10  72   81   753  43      11   0    0     -    -2
996   user-997  10  79   85   762  59      13   0    0     -  -117
997   user-998  10  80  109  1497  60      14   0    0     -    35
998   user-999  10  79   67  1325  62      16   0    0     -    36
999  user-1000  10  89   71  1081  46      12   0    0     -    53

[1000 rows x 11 columns]

In [ ]:
df.sort_values("Coin")

         Name Age  Atk  Def    HP Spd Stamina win Lose Class  Coin
776  user-777  10   89   87   840  56      13   0    0     -  -124
979  user-980  10  103  107  1363  52      10   0    0     -  -120
996  user-997  10   79   85   762  59      13   0    0     -  -117
773  user-774  10   93   94   975  58      12   0    0     -  -106
814  user-815  10   85  104   838  56      16   0    0     -  -104
..        ...  ..  ...  ...   ...  ..     ...  ..  ...   ...   ...
442  user-443  10   89   81  1503  44      15   0    0     -   699
378  user-379  10  102   87   900  41      11   0    0     -   702
272  user-273  10   82   49   766  51      15   0    0     -   706
439  user-440  10   94  105  1235  64      15   0    0     -   711
611  user-612  10  102  108  1352  63      14   0    0     -   744

[1000 rows x 11 columns]

In [ ]:
df.loc[df["Coin"] > 0]

          Name Age  Atk  Def    HP Spd Stamina win Lose Class Coin
1       user-2  10   59   94   723  51      15   0    0     -  134
2       user-3  10   67   51   975  48       9   0    0     -   68
4       user-5  10   64   66  1086  56       9   0    0     -   36
5       user-6  10   64   74  1337  53      16   0    0     -   36
6       user-7  10   65   62   964  48      12   0    0     -    9
..         ...  ..  ...  ...   ...  ..     ...  ..  ...   ...  ...
992   user-993  10   64   80   676  43      18   0    0     -   65
994   user-995  10  109   70  1310  40      15   0    0     -  652
997   user-998  10   80  109  1497  60      14   0    0     -   35
998   user-999  10   79   67  1325  62      16   0    0     -   36
999  user-1000  10   89   71  1081  46      12   0    0     -   53

[575 rows x 11 columns]

In [ ]:
df = df.drop("Coin", axis=1)
df_duel = df.copy()
karakter_list_duel = karakter_list

for j in range(200):
  random.shuffle(karakter_list_duel)
  for i in range(0,len(karakter_list_duel),2):
    if(i+1 != len(karakter_list_duel)):
      win_name = duel(karakter_list_duel[i],karakter_list_duel[i+1])
      if karakter_list_duel[i].name == win_name:
        lose_name = karakter_list_duel[i+1].name
      else:
        lose_name = karakter_list_duel[i].name

      idx = df_duel[df_duel['Name']==win_name].index.values
      df_duel.at[idx[0],'win'] += 1

      idx = df_duel[df_duel['Name']==lose_name].index.values
      df_duel.at[idx[0],'Lose'] += 1

In [ ]:
df_duel.sort_values("win")

         Name Age  Atk  Def    HP Spd Stamina  win Lose Class
250  user-251  10   53   68   684  62      11    0  200     -
445  user-446  10   55   51   605  46      11    0  200     -
730  user-731  10   41   58   727  42      16    1  199     -
14    user-15  10   66   80   612  47       9    3  197     -
809  user-810  10   57   71   749  51      16    4  196     -
..        ...  ..  ...  ...   ...  ..     ...  ...  ...   ...
611  user-612  10  102  108  1352  63      14  196    4     -
504  user-505  10   95   93  1458  47      13  197    3     -
891  user-892  10   96   92  1508  42      11  197    3     -
979  user-980  10  103  107  1363  52      10  198    2     -
835  user-836  10  105   90  1571  71      11  198    2     -

[1000 rows x 10 columns]

In [ ]:
df_non = df_duel.loc[df_duel["win"] < 96]
df_non = df_non.replace({"-":"non-fighter"})
df_non

         Name  Age  Atk  Def    HP  Spd  Stamina  win  Lose        Class
1      user-2   10   59   94   723   51       15   11   189  non-fighter
2      user-3   10   67   51   975   48        9   17   183  non-fighter
3      user-4   10   67   86  1116   37       16   89   111  non-fighter
4      user-5   10   64   66  1086   56        9   43   157  non-fighter
5      user-6   10   64   74  1337   53       16   93   107  non-fighter
..        ...  ...  ...  ...   ...  ...      ...  ...   ...          ...
991  user-992   10   61   70  1291   37        9   67   133  non-fighter
992  user-993   10   64   80   676   43       18    8   192  non-fighter
993  user-994   10   97   73   791   49       17   60   140  non-fighter
995  user-996   10   72   81   753   43       11   28   172  non-fighter
996  user-997   10   79   85   762   59       13   42   158  non-fighter

[475 rows x 10 columns]

In [ ]:
df_merge = pd.merge(df_non, df_duel, how="right", on=["Name", "Age", "Atk", "Def", "HP", "Spd", "Stamina", "win", "Lose"])
df_merge = df_merge.drop(["Class_y"], axis=1)
df_merge = df_merge.rename(columns={"Class_x":"Class"})
df_merge = df_merge.fillna("fighter")
df_merge

          Name   Age   Atk    Def  ...  Stamina    win   Lose        Class
0       user-1  10.0  86.0   90.0  ...     13.0  132.0   68.0      fighter
1       user-2  10.0  59.0   94.0  ...     15.0   11.0  189.0  non-fighter
2       user-3  10.0  67.0   51.0  ...      9.0   17.0  183.0  non-fighter
3       user-4  10.0  67.0   86.0  ...     16.0   89.0  111.0  non-fighter
4       user-5  10.0  64.0   66.0  ...      9.0   43.0  157.0  non-fighter
..         ...   ...   ...    ...  ...      ...    ...    ...          ...
995   user-996  10.0  72.0   81.0  ...     11.0   28.0  172.0  non-fighter
996   user-997  10.0  79.0   85.0  ...     13.0   42.0  158.0  non-fighter
997   user-998  10.0  80.0  109.0  ...     14.0  185.0   15.0      fighter
998   user-999  10.0  79.0   67.0  ...     16.0  115.0   85.0      fighter
999  user-1000  10.0  89.0   71.0  ...     12.0  113.0   87.0      fighter

[1000 rows x 10 columns]

In [ ]:
dataset = df_merge.drop(["Name","win","Lose","Age"], axis=1)
dataset

      Atk    Def      HP   Spd  Stamina        Class
0    86.0   90.0  1121.0  46.0     13.0      fighter
1    59.0   94.0   723.0  51.0     15.0  non-fighter
2    67.0   51.0   975.0  48.0      9.0  non-fighter
3    67.0   86.0  1116.0  37.0     16.0  non-fighter
4    64.0   66.0  1086.0  56.0      9.0  non-fighter
..    ...    ...     ...   ...      ...          ...
995  72.0   81.0   753.0  43.0     11.0  non-fighter
996  79.0   85.0   762.0  59.0     13.0  non-fighter
997  80.0  109.0  1497.0  60.0     14.0      fighter
998  79.0   67.0  1325.0  62.0     16.0      fighter
999  89.0   71.0  1081.0  46.0     12.0      fighter

[1000 rows x 6 columns]

In [ ]:
# Pre-Processing

dataset_pre = dataset.replace({"non-fighter":0, "fighter":1})
dataset_pre_target = dataset_pre["Class"]
dataset_pre_data = dataset_pre.drop(["Class"], axis=1)

In [ ]:
dt_test = dataset_pre_data.copy()
print("Max : "+str(dt_test.max()))
print("Max : "+str(dt_test.min()))
normalized_df=(dt_test-dt_test.min())/(dt_test.max()-dt_test.min())
normalized_df

Max : Atk         112.0
Def         119.0
HP         1571.0
Spd          72.0
Stamina      23.0
dtype: float64
Max : Atk         41.0
Def         36.0
HP         605.0
Spd         27.0
Stamina      4.0
dtype: float64

          Atk       Def        HP       Spd   Stamina
0    0.633803  0.650602  0.534161  0.422222  0.473684
1    0.253521  0.698795  0.122153  0.533333  0.578947
2    0.366197  0.180723  0.383023  0.466667  0.263158
3    0.366197  0.602410  0.528986  0.222222  0.631579
4    0.323944  0.361446  0.497930  0.644444  0.263158
..        ...       ...       ...       ...       ...
995  0.436620  0.542169  0.153209  0.355556  0.368421
996  0.535211  0.590361  0.162526  0.711111  0.473684
997  0.549296  0.879518  0.923395  0.733333  0.526316
998  0.535211  0.373494  0.745342  0.777778  0.631579
999  0.676056  0.421687  0.492754  0.422222  0.421053

[1000 rows x 5 columns]

In [ ]:
# Normalisasi

d = preprocessing.normalize(dataset_pre_data, axis=0)
dataset_normal = pd.DataFrame(d, columns=["Atk","Def","HP","Spd","Stamina"])
dataset_normal

          Atk       Def        HP       Spd   Stamina
0    0.033662  0.035566  0.031083  0.029439  0.029615
1    0.023093  0.037147  0.020047  0.032639  0.034172
2    0.026225  0.020154  0.027035  0.030719  0.020503
3    0.026225  0.033986  0.030944  0.023679  0.036450
4    0.025050  0.026082  0.030112  0.035839  0.020503
..        ...       ...       ...       ...       ...
995  0.028182  0.032010  0.020879  0.027519  0.025059
996  0.030922  0.033591  0.021129  0.037759  0.029615
997  0.031313  0.043075  0.041508  0.038399  0.031893
998  0.030922  0.026477  0.036739  0.039679  0.036450
999  0.034836  0.028058  0.029974  0.029439  0.027337

[1000 rows x 5 columns]

In [ ]:
# Split Data

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(dataset_normal, dataset_pre_target, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
# Tuning Parameters
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid_2 = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid_2.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s

[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV] ........... C=1, gamma=10, kernel=rbf, score=0.607, total=   0.0s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV] ........... C=1, gamma=10, kernel=rbf, score=0.550, total=   0.0s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV] ........... C=1, gamma=10, kernel=rbf, score=0.600, total=   0.0s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV] ........... C=1, gamma=10, kernel=rbf, score=0.564, total=   0.0s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV] ........... C=1, gamma=10, kernel=rbf, score=0.600, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.957, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.979, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.936, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.943, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.886, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.607, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.550, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.600, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.564, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.600, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] ......... C=100, gamma=10, kernel=rbf, score=0.971, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] ......... C=100, gamma=10, kernel=rbf, score=0.964, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] ......... C=100, gamma=10, kernel=rbf, score=0.957, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] ......... C=100, gamma=10, kernel=rbf, score=0.957, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] ......... C=100, gamma=10, kernel=rbf, score=0.936, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.957, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.979, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.936, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.943, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.886, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.607, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.550, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.600, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.564, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.600, total=   0.0s
[CV] C=100, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=100, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=100, gamma=0.01, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=100, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=100, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=100, gamma=0.01, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=100, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=100, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=100, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=100, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=100, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.986, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.971, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.964, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.971, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.929, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.971, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.964, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.957, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.957, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.936, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.957, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.979, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.936, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.943, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.886, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.607, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.550, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.600, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.564, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.600, total=   0.0s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.529, total=   0.0s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.521, total=   0.0s

[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:    2.4s finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [ ]:
#Predict the response for test dataset
y_pred = grid_2.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       142
           1       0.99      0.95      0.97       158

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300

In [2]:
import pandas as pd
pd.dataFrame({"name1":panglima_names, "power1":[0]*len(panglima_names), "timestamp1":[0]*len(panglima_names),
                                "name2":panglima_names, "power2":[0]*len(panglima_names), "timestamp2":[0]*len(panglima_names),
                                "name3":panglima_names, "power3":[0]*len(panglima_names), "timestamp3":[0]*len(panglima_names),
                                "name4":panglima_names, "power4":[0]*len(panglima_names), "timestamp4":[0]*len(panglima_names),
                                "name5":panglima_names, "power5":panglima_list, "timestamp5":timestime_list})

AttributeError: module 'pandas' has no attribute 'dataFrame'